### ISSUE TITLE
Prebuilt Stable Releases for Ubuntu

### ISSUE THREAD

**Issue by MuTaTeD** [xournalpp/xournalpp#1013]
Hi,
The pre-built releases for Ubuntu (.deb) are available for the Master channel (as per the installation instructions in the Readme file), Can you provide ppa and or .deb releases for Stable channel for 1.0.8 since only source code is available for Linux versions...

**Comment by andreasb242** [comment]
I have to check this - but it should be relative easy, we only need to think to merge our stable branch if we create a release

**Comment by LittleHuba** [comment]
I assume this can be closed as we do provide .deb releases in our nightly pipeline now. As the normal release pipeline will be based on this one it will be fixed for all releases.

**Comment by Technius** [comment]
We currently have stable releases for 16.04 but not 18.04 (which most users have already moved to).

**Comment by bittner** [comment]
Just a (maybe stupid) question: Please excuse!

There is the [xournal](https://packages.ubuntu.com/search?keywords=xournal) Ubuntu package, which is currently version 0.4.8, in other words, hopelessly outdated:
```console
$ dpkg -l xournal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name         Version              Architecture    Description
+++-============-===============-====================-=================================
ii  xournal      1:0.4.8-1build1      amd64           GTK+ Application for note taking
```
On flatpack there seem to be two packages, the outdated "xournal" package and the "xournalpp":
```console
$ flatpak search xournal
Application ID                 Version    Branch Remotes Description                                                                
net.sourceforge.xournal        0.4.8.2016 stable flathub Application for notetaking, sketching, and keeping a journal using a stylus
com.github.xournalpp.xournalpp 1.0.16     stable flathub Take handwritten notes
```
I only found out by accident (two [videos on YouTube](https://www.youtube.com/watch?v=BB8LFZtSc1g)) that the Xournal project (seems to have evolved, the source code is finally available on GitHub, contributions are easier and actually happening, and) has a "++" version that has new, long-awaited features.

Are there any efforts ongoing or planned to reduce the confusion and update the old package or remove it from the package index?

**Comment by Technius** [comment]
Xournal and Xournal++ are different projects maintained by a different set of people. Xournal++ (this project) is a fork and modern C++ port of Xournal (the one hosted on SourceForge, written in C) with more features. Xournal++ is not 100% stable and modern yet, as evidenced by our issue tracker, but we're working on it.

**Comment by jug007** [comment]
Would be cool if the PPA could have a stable version. Kind of annoying to get an update notification every day, just for this one package.

**Comment by Technius** [comment]
I agree. @andreasb242 can help set this up.

**Comment by apandada1** [comment]
I have made a stable PPA for Xournal++. https://launchpad.net/~apandada1/+archive/ubuntu/xournalpp-stable
```
sudo add-apt-repository ppa:apandada1/xournalpp-stable
sudo apt-get update
sudo apt install xournalpp
```      
How to make such a PPA without manually building it in computer and uploading?
1. I created a [new Launchpad packaging recipe](https://code.launchpad.net/~apandada1/+recipe/xournalpp-stable) from [this source](https://code.launchpad.net/~andreasbutti/xournalpp/+git/xournalpp).
2. Then I noted the full git commit address (`535d261d364f5925dec1ae3966a067883e53281e`) of the [latest stable release](https://github.com/xournalpp/xournalpp/commit/535d261d364f5925dec1ae3966a067883e53281e).
3. I edited the packaging recipe to the following, to build that specific commit.
```
# git-build-recipe format 0.4 deb-version {debupstream}-0~{revtime}
lp:xournalpp 535d261d364f5925dec1ae3966a067883e53281e
```
4. I noticed that the `debian/changelog` had an old version number (1.0.6), so I manually bumped the version number to 1.0.18 using the packaging recipe. I also removed `{revtime}` from the version number.
The new packaging recipe is,
```
# git-build-recipe format 0.4 deb-version 1.0.18-1
lp:xournalpp 535d261d364f5925dec1ae3966a067883e53281e
```
Comments:
- Henceforth, please update the `debian/changelog` while making a new release. If you are not in a Debian system, you can simply edit the version number in [this line](https://github.com/xournalpp/xournalpp/blob/master/debian/changelog#L1). There's no need to edit the other fields, Launchpad can pick up the correct version and ignore other things. Then, one would not have to manually change version numbers in Launchpad.
- When a new version is released, one only needs to change the git commit address in the Launchpad recipe (and update the version number, if `debian/changelog` is not updated).
- I have enabled builds for `armhf` and `arm64` in the PPA. Might come handy for a Raspberry Pi touchscreen or an ARM tablet.
- If the developers want to maintain their own official stable PPA instead of the PPA I made, I am perfectly okay with that (that's why I wrote how to do it in details). Otherwise, I would be happy to maintain the PPA, and update it when a new stable version is released (I am watching releases).
- I have tested the PPA works in Ubuntu 18.04 64 bit. Please test it further, and consider adding it to the Readme.

Thanks to all the developers for making this beautiful software.

**Comment by apandada1** [comment]
Shall I send a pull request with updated Readme, mentioning this PPA?

**Comment by Technius** [comment]
@apandada1 Thanks for the help, we would greatly appreciate a PR!

**Comment by apandada1** [comment]
Done. By the way, the nightly builds in the PPA are failing to build in Ubuntu 18.04 since August (they build fine in 20.04). See https://github.com/xournalpp/xournalpp/pull/506#issuecomment-695328275 for details.

This may create issues in Ubuntu 18.04 when the next version is released (although one can manually copy packages from 20.04). I could not determine why the build failed, while it builds for 20.04

**Comment by Technius** [comment]
It's probably failing because we're using the C++17 filesystem library in 1.1.0. Filesystem is not available on 18.04, so we download a shim library during build time--this is not allowed on Debian-based builds, if I recall.

**Comment by PraxTube** [comment]
What is the recommended xournal++ version for ubuntu 16? There seem to be known bugs in some versions, but I don't know which one's the recommended one.

The ones I tested so far seem to crash non stop.
(versions 1.0.20 and 1.1.3)

**Comment by apandada1** [comment]
Did you try snap/flatpak? Do they also crash?

**Comment by PraxTube** [comment]
I just did and it seems just fine. Thanks a lot!

I guess the reason was that a lot of dependencies weren't met (i.e. I was installing it wrong) and with the flatpak install it got all the necessary dependencies.
