### ISSUE TITLE
Text-tool don't work on windows 10 

### ISSUE THREAD

**Issue by Caiuzx** [xournalpp/xournalpp#1052]
Hi , 
i have windows 10 , 1809 . does having visual studio 2017, matter ?
**i select the text tool but only enter and tab works.**
I can't write anything and it's a shame.
what could i do to solve? - What configurations do you have? 
I already have a gtk installed with GIMP, does it need the GTK 3 version to make it work?

**Comment by andreasb242** [comment]
Gimp and Visual Studio does not matter, Xournal++ uses the delivered GTK3 Version.
This is probably the same bug as #800

It's not yet fully clear when the bug happens. Sometimes it's there, sometimes not. When I tested, it was working.

**Comment by Caiuzx** [comment]
> Gimp and Visual Studio does not matter, Xournal++ uses the delivered GTK3 Version.
> This is probably the same bug as #800
> 
> It's not yet fully clear when the bug happens. Sometimes it's there, sometimes not. When I tested, it was working.
I would like to solve the problem. I'm an amateur programmer. I need Xournal ++ to do prototypes of my games. Is there a program to understand where the error is? which analyzes the program flow when I press the keys on my keyboard?
because it is strange that nothing appears.
Xournal 0.48 the keys work! but Xournal 048 is NOT Xournal ++!
How can I help? since my computer is one of those that the keyboard does NOT work?

**Comment by andreasb242** [comment]
Hey @Caiuzx 

Welcome! You are the first Windows developer! :-) (I did the Windows Port, but I'm usually use Linux)
You can contact us on Gitter, there are also private chats possible.
https://gitter.im/xournalpp/xournalpp

I used MSYS2 and therefore gcc for compiling.
It's not that complicated, the manual (hopefully correct) is here:
https://github.com/xournalpp/xournalpp/blob/master/readme/WindowsBuild.md

Theoretical it's possible to compile with Visual Studio, but I never tried, therefore it will be probably much easier to use gcc, and gdb to debug.
There are a lot of frontends for gdb, e.g. Eclipse, Code::Block and multiple else.

The bug is probably somewhere in src/gui/TextEditor.cpp

**Comment by Caiuzx** [comment]
ahah thanks a lot !

**Comment by studleylee** [comment]
I have the same issue on Win10

**Comment by Technius** [comment]
This bug seems to occur in the latest release, but I wasn't able to reproduce the bug after compiling a version from source (following the instructions in `readme/WindowsBuild.md`).

**Comment by Taylancan** [comment]
Guys I prefer VS Code with cmake tools and cmake Intelisense. Its getting powerful and is (I think) the first piece of Code that is crossplatform from MS. 
You Can also bind a MYSYS to VS Code

**Comment by LittleHuba** [comment]
@Caiuzx please recheck if the problem persists

**Comment by Caiuzx** [comment]
> 
> 
> @Caiuzx please recheck if the problem persists

just resolved on 1.0.12

**Comment by LittleHuba** [comment]
Thanks for the feedback. Then I'll close the issue

**Comment by DannyAn** [comment]
1.0.18 doesn't work.

**Comment by mrjihun** [comment]
There is simple workaround here.

Install msys, install gtk, sync pacman database, update gtk.
and copy content of msys's binary.
Copy all of them to 'bin' of xournal++.

Then xournal++ will work again.

In short, just update gtk library.
