### ISSUE TITLE
File open dialogue does not respect current working directory

### ISSUE THREAD

**Issue by sm8ps** [xournalpp/xournalpp#1056]
Calling the file open dialogue while having a file already opened, I would expect the new file to be searched for in the same directory as the current file (which I call current working directory in the title of this report; CWD for short). Instead, the list of recently opened files is selected which is inconvenient. When wanting to edit another file in the CWD, one has to browse through the whole file system hierarchy. On the other hand, the list of recently opened files is always available as a special filter option in the file open dialogue.
This happens on Ubuntu Budgie 18.10 with 1.0.11 (compiled on April 5th 2019, 22:39:29). The desktop environment uses the Nautilus file browser if that should matter. The issue sort of reminds me of the now closed #990 but I do not recognize any obvious connection.
Thanks for your consideration!

**Comment by Technius** [comment]
I'm willing to work on this.

**Comment by Technius** [comment]
Alright, so I have an initial version of this working (i.e if you open a file and then choose "Open File" again, the file chooser dialog will be open to that file's folder). However, the GTK documentation suggests the following:

> Note that old versions of the file chooser’s documentation suggested using gtk_file_chooser_set_current_folder() in various situations, with the intention of letting the application suggest a reasonable default folder. This is no longer considered to be a good policy, as now the file chooser is able to make good suggestions on its own. In general, you should only cause the file chooser to show a specific folder when it is appropriate to use gtk_file_chooser_set_filename(), i.e. when you are doing a Save As command and you already have a file saved somewhere.

On one hand, I agree that I've personally found those file chooser suggestions to be helpful. On the other hand, there have been times when I wanted to save a series of files in the same folder. So I've thought of a compromise: we could add the CWD to the sidebar displayed on the left so that we still 1) have access to the suggestions by default, and 2) can access the CWD one click away.

Thoughts?

**Comment by LittleHuba** [comment]
Your solution looks nice to me. As nobody else has any comments on this, it is good the way you did it. See the PR for further comments.

**Comment by sm8ps** [comment]
Original poster here, though not experienced in the programming of GTK or similar. Your suggestion makes sense to me and seems to solve the issue while at the same time avoiding problems in the future. So from my point of view it looks all good.
Thank you for your efforts!
