### ISSUE TITLE
General discussion about xournalpp developement

### ISSUE THREAD

**Issue by MarPiRK** [xournalpp/xournalpp#111]
Hi, I'm planning to work more on Xournal++. Now I'm improving new string handling, but I have few questions for current developers:
1. While rewriting string I read huge amount of code and I'm wondering, why in Xournal**++** is so much C-like code, for example glibc (with awful string handling and need to convert things back and forth), zlib.h and some other C specific libraries/headers. Why don't we use glibmm/gtkmm and some C++ libraries like boost (which I'm basically using in string_new)?
2. What is poppler source code included for? Can't we just use system preinstalled **C++** binding (btw currently I have installed in system poppler-0.32 in comparison with about 1,5 year old 0.24.1)?
3. Anyone there is using some kind of IDE to edit code? I'm using NetBeans and those Tab indents are terribly inconvenient for me and I'm sorry if in my commits are spaces instead of tabs, but I can't find a way to change it.
4. I have some ideas, but it will be extremely difficult to implement them while we have such mess in branches. Can't we just merge everything up to glib_new (which I personally consider stable) and then center our attention on gtk3 and other new (hopefully more C++'ish) stuff?

**Comment by Corna** [comment]
I agree

**Comment by wbrenna** [comment]
I can hopefully clarify some of this.

1. I can't say much here since I came along far after the original development. Speculating, Xournal is written in C and so the port probably contained some indication of its heritage. Removing dependencies on glibc's string handling is much appreciated and I don't see any reason why it should not be changed.

2. I included the poppler source hack - this was due to the fact that Xournal++ didn't/doesn't have frequent enough development to cover the changes in poppler. Basically the poppler headers were changing at a pace too fast for Xournal++ to keep up with, and I didn't see a better option. Historically Xournal++ was neglected for a number of years, and this was likely due in part to the fact that it wouldn't compile on modern systems because of the poppler calls. Potentially this could be changed back to use the system bindings, but personally I think if you want to focus on PDF there are bigger issues at the moment, namely the inability to properly load/save certain PDF types like forms (bug #60, for example).

3. I don't use an IDE and I'm not too familiar with NetBeans. That said, have you tried this: http://stackoverflow.com/questions/1949014/how-can-i-configure-netbeans-to-insert-tabs-instead-of-a-bunch-of-spaces?

4. I think there is a potential for improvement here. Firstly, I believe all features are merged up to glib_new with the exception of anything to do with gtk3 adjustments. The addpoppler branch was created when the full poppler source was included; you can see if you try to compile master that it won't compile on poppler greater than some version (0.16+ or so). I think we can probably remove addpoppler. However, if we are in agreement to make glib_new the new master, I suggest that we put current master into a legacy branch, since the heightened dependencies on glib_new mean it won't compile on many older systems (I regularly use two machines that won't compile glib_new!).

**Comment by Corna** [comment]
I agree with number 4; we should move
master -> legacy
glib_new -> master
and delete addpoppler

**Comment by MarPiRK** [comment]
Thanks for comprehensive response.
1. I think that after deep testing of my string_new branch I can gradually move from glibc including standardized logging (using very convenient boost::log).
2. Maybe this issue exists because of super old poppler?
3. Thanks for advise. It's working as it should. In next commits I'll use this formatting.
4. I think that's good idea. Why can't you update glib on your machines?

**Comment by MarPiRK** [comment]
So when will point 4 happen?

**Comment by wbrenna** [comment]
I think this weekend I can get the time to fix up the branching and test/apply all the patches that have been waiting.

Regarding poppler, presumably the most recent version of poppler was used when the library was written. When I patched in 0.24 it was also a fairly recent version (as you can see, 0.24 is only about 1.5 years old). Poppler development just seems to move quickly, and since it's not at 1.0 they don't mind breaking compatibility. Compiling against a fixed version that works seemed simpler when there isn't anyone dedicated to ensuring that xournalpp will compile against a set of incompatible poppler versions.

**Comment by x2b** [comment]
Just a note regarding 2: Xournal++ developers chose to use the C++ bindings of poppler in an attempt to make everything more C++ish (At least that is my guess :) ). Unfortunately these bindings were never properly documented and as far as I know the code has been abandoned since, I don't even know whether it still ships with poppler. To port this to a later version I guess that we would have to write our own C++ wrappers around the C part of poppler.

**Comment by MarPiRK** [comment]
Hmmm... [There](http://en.wikipedia.org/wiki/Poppler_%28software%29) I can see that Poppler is written in C++, so I guess that there should be no problem with documentation whatsoever?

**Comment by x2b** [comment]
Well, take a look at the project wiki: https://wiki.freedesktop.org/www/Software/poppler/ Even the link to the C++ part is not working...

**Comment by MarPiRK** [comment]
Huh, this entire wiki is little outdated... It states wishes for 0.28, but current version is 0.32. Unbelivable... Last edit: almost exactly a year ago.

**Comment by MarPiRK** [comment]
I've told with tsdgeos on poppler IRC and it seems that indeed "poppler has poor outdated documentation", but in fact it's not as bad as wiki says :)
Freedesktop's wikis are pretty hard to edit – in the name of "preventing from spam" their preventing from any edits, but eventually he managed to update wiki.
Back to poppler doc. There is some available, but not in header files, but in cpp files. To generate it you need to download poppler package cd to cpp directory and run doxygen.

**Comment by x2b** [comment]
Well, I am starting to recall the problem: There is one file, called `CairoOutputDev.h` which is included in poppler. At versions <= 0.24 it was shipped (=installed), so it could be `#include`ed from the Xournal++ code. As the name suggests this file is required to render PDF output to a cairo context (a `cairo_t*`). However, the file is no longer shipped with versions > 0.24 although it is still in the source code.

Hence there are two ways to resolve the situation:

- We could either report the problem upstream and hope that the poppler devs start to include the file again in future releases. However, this would mean that the local poppler build scripts would still be needed for quite a while
- We could try to implement the PDF rendering in a different way so we are no longer dependent on the functionality. I had the plan to do this once, but I was dissuaded by the poor documentation. However, if the poppler devs are available we might be able to pick their brains.

I just threw out all of the internal poppler stuff from my fork, see https://github.com/x2b/xournalpp/tree/wip/poppler . I would be only too pleased if you could get this to compile

**Comment by MarPiRK** [comment]
I'll try it out next week.
I've got in touch with previous poppler online cpp reference maintainer (Thomas Allen <thomas@oinksoft.com>) and he told me, that he won't maintain this anymore, because he doesn't feel like installing some dependencies on his server. I've done this on my own: http://marpirk.github.io/poppler-cpp-doc. It's published also in official poppler wiki.

**Comment by andreasb242** [comment]
I'm may a little bit late, to give the answer.
I'm the original author of Xournal++, first I simply tried to rewrite Xournal, but it was based on deprecated GTKCanvas.

it was simple not possible, to get the result I would have. So I decided to start rewriting in in C++.

1. I never did a GTK Project before, and get a fast start I wrapped a lot of the old Code in C++, because of this you have a lot of C Code in the Project.
(I had about one year in my free time, until it was more or less usable)

2. First I used the poppler GLIB API, but some features were not possible, Xournal++ needs to merge PDFs, I woulden't lost the Index etc. so the only realistic thing was to use the internal Poppler API, which is not stable.
I know this is not a good solution, but it was the only one, which makes it possible for me to get it working in the time I had, because I was student and would like to use Xournal++.

3. I used always Eclipse to write Xournal++, it should be no problem to use NetBeans

4. I like if there is somebody developing for Xournal++, it was a lot of work, and without maintenance it will die sometimes :-)

Improvements and code cleanup is always good, because of this I like open source projects.

The "XOJ_TYPE_ATTRIB;" were used for debugging, at the start. This was working with Classes and Structs, and is a relict which can now be removed, because Xournal++ should be more or less stable.
The stacktrace logg etc. was added later I think, and I hat at the beginning a lot crashes...

I hope it's now clear why Xournal++ is written like this.

Feel free to contact me if you need help for improvements, even if I'm not active developing at Xournal++ at the moment, I may can help you at some points.

Andreas

**Comment by andreasb242** [comment]
The "XOJ_TYPE_ATTRIB;" was also used to detect Memory Leaks. it is always running, and at the end it logs out the objects and the count, if there are leaks.

It was not possible to use Walgrind, because I had a Tablet with 1.4Ghz Single Core and 1GB Ram, running Xournal++ with Wallgrind makes it complete unusable...

**Comment by MarPiRK** [comment]
If I remember correctly PoDoFo handles PDF merging/splitting pretty good.
I think, that XOJ_TYPE_ATTRIB feature should be possible to disable in configure script.

**Comment by andreasb242** [comment]
We can have a look at PoDoFo, if it matches the requirements, why not?

**Comment by MarPiRK** [comment]
I have a question about XournalTypeList: what should I do, if I removed some class? Do I have to enumerate it from beginning?

**Comment by andreasb242** [comment]
No, the exact value don't matter, each type should be unique, because this is used as "Type ID", for runtime checks.

**Comment by MarPiRK** [comment]
What do you think about creating Trello board with our ideas, todo lists, roadmap? This way we'd be able to discuss specific problems in cleaner way. I think, that making issue for each idea is pretty messy and we don't see bugs, we have to resolve in flood of brilliant ideas list.

**Comment by MarPiRK** [comment]
Anyone there? I can make it and populate with current informations.

**Comment by andreasb242** [comment]
I don't know Trello, but I have still some Ideas for Xournal++ ;-)

**Comment by MarPiRK** [comment]
Could you send me your email, so I can invite you to organization?

**Comment by wbrenna** [comment]
I would prefer we keep roadmaps publicly accessible! Is there an option to open it to anyone with a link?

**Comment by MarPiRK** [comment]
Yes, it's open to anyone using link

**Comment by MarPiRK** [comment]
What about changes in branches, which we had discussed a moth ago?

**Comment by x2b** [comment]
Another thought, maybe use [Travis CI](https://travis-ci.org/)?

**Comment by MarPiRK** [comment]
Yeah, I think it's interesting proposal.

**Comment by MarPiRK** [comment]
I was thinking about Windows support. If I remember correctly autotools aren't considered as best choice for such scenario. What do you think about moving to something like CMake? I think it's much simpler and it doesn't take that much time to configure (especially boost).

**Comment by Corna** [comment]
Building software under Windows is often very easy thanks to [MSYS2](http://sourceforge.net/projects/msys2/)
I have a working build environment for both Win32 and Win64, and I can successfully build my project ([pcb2gcode](https://github.com/pcb2gcode/pcb2gcode)) with a simple

```
autoreconf
./configure --prefix=/mingw32
make
```

If you want I can try to build xournalpp

**Comment by MarPiRK** [comment]
Oh, I haven't known that. What about library dependencies?

**Comment by Corna** [comment]
With MSYS(1) you had to download and build them by yourself, with MSYS2 and pacman you can just download them from the repo. For example, if you want to download boost you can just run

    pacman -S mingw-w64-boost-i686

for the 32-bit version and

    pacman -S mingw-w64-boost-x86_64

for the 64-bit version

**Comment by wbrenna** [comment]
I hadn't heard of MSYS before - that would be great if it works. Let me know what you find!

**Comment by andreasb242** [comment]
I know MSYS(1), but had it only used as MINGW replacement. I'm using windows only in VMs, but if there would be an easy way to build Xournal++ on windows we should think about building it for windows and creating a setup.

**Comment by wbrenna** [comment]
For me it was
```
pacman -S mingw-w64-x86_64-boost
```
but I'm stuck with pkg_config - it doesn't seem to recognize packages that were installed under the ```mingw-w64-``` prefix. Does this mean it needs PKGBUILD, or perhaps I'm missing a dev package? gtk/gdk 3, fontconfig, lcms are not being identified.

**Comment by Corna** [comment]
Make sure you're running MSYS2 from the W64 shortcut. You also need to specify --prefix=/mingw64 during the configure

**Comment by wbrenna** [comment]
Hm, I had tried the second prefix and it didn't help. I was certainly running from the shortcut it created as well.

**Comment by andreasb242** [comment]
Close this discussion, 3 years old and the ticket for mm is still open
