### ISSUE TITLE
Too much precision in xopp files.

### ISSUE THREAD

**Issue by JJones780** [xournalpp/xournalpp#1277]
Low priority.. but do we really need 14 digits of precision in the xopp file?

example page coordinates:
168.71782794981516 503.4808047927973

cutting down to 4 would reduce file size substantially before and after compression.
168.7178 503.4808

Should be a setting ... and it might be good to have it keep accuracy for files loaded with more accuracy.

**Comment by siliconninja** [comment]
Hi JJones (and whoever else reads this issue 😉),
I think this is a great issue. I tried writing some code to fix it, but I didn't succeed.
I looked up the setprecision function in C++, but I wasn't sure if we should use it because it would require capturing stdout and converting it to a double, which might look ugly. It would also force numbers outputted to have whatever precision we specified in setprecision.
So, I wrote my own helper method instead, but it didn't end up working, and it kept the same 15 digits in the file, but the number was rounded up (because of the floor function).
According to this: https://stackoverflow.com/questions/12349323/setting-the-precision-of-a-double-without-using-stream-ios-baseprecision, it looks like we'd need to use a different datatype other than a double, or use third-party libraries, if we don't want to use setprecision.

What do you think the best solution is in this case?

**Comment by Febbe** [comment]
> it would require capturing stdout and converting it to a double, which might look ugly. 

I really don't know what you want to say with that. How and why do you want to convert a stream to an primitive type?

Whats the Problem with `std::ofstream << std::setprecision(4) << std::fixed << float;`
or 
```
std::stringstream ss;
ss << std::setprecision(4) << std::fixed << float;
return ss.str();
``` 
?

**Comment by siliconninja** [comment]
> I really don't know what you want to say with that. How and why do you want to convert a stream to an primitive type?

I was thinking about setting the precision right when we create the coordinates, so if we are making points, we won't be storing 15 bits of information in memory for each point we create. To do this inside of the constructor of Point.cpp (please see my commits for what I was trying to do), if we use `setprecision` which returns an output stream, setting `this->x` or `this->y` would require converting it to a double.

> Whats the Problem with `std::ofstream << std::setprecision(4) << std::fixed << float;`

> or

> `std::stringstream ss;
ss << std::setprecision(4) << std::fixed << float;
return ss.str();`

> ?

We could do this if we are only setting the precision when we write to a file, and not when we create each Point. I know that worrying about doing this with each Point instance is making the issue a little more complicated, but I wanted to make the code related to this issue as efficient as possible. We could also use strings to store Points' coordinates, but that would require rewriting a lot of the existing codebase.

Now that I realize it, I think the code snippets you posted are okay. I just wanted to make sure my code wasn't too confusing if it was read by someone else.

**Comment by siliconninja** [comment]
Just saw your edits. Sorry.

>> According to this: https://stackoverflow.com/questions/12349323/setting-the-precision-of-a-double-without-using-stream-ios-baseprecision , it looks like we'd need to use a different datatype other than a double, or use third-party libraries, if we don't want to use setprecision.

> The first answer told the reader, not to cut the precision or whatever he wants to do. Leave the double or float as it is.
For example try to imagine, how 0.4 is represented in doubles or floats?
 00111110110011001100110011001101 
It must be like an infinite amount of 1001 but for that the size of floats or doubles is to small. You don't want to cut more. 

Okay, I see your point.

Another thought I had: Doubles are useful for detailed drawings. We can keep them in the code.

> float tmp;
std::ifstream ifs{"filename"};
ifs >> tmp;

> This will still read those ugly long numbers.

I understand. You need to use an instance of an ifstream or stringstream to make the changes not permanent.

This is very helpful to know. I think streams are

**Comment by Febbe** [comment]
> I was thinking about setting the precision right when we create the coordinates, so if we are making points, we won't be storing 15 bits of information in memory for each point we create. 

I've edited my post and provided a example, why you don't want to do this. Therefore your code would not cut the precision in memory.  `std::round(0,4 * 100)`/100 will still be `00111110110011001100110011001101` and all of them are necessary to represent 0.4. 
Another thing space efficiency is not efficient in matters of prozes time. Currently the most efficient primitive types on modern amd64 mashines are 4bytes each. And we don't need to be that space efficient so we can even use doubles everywhere. And the compiler will only use SSE if we compile with -O3, so it does not matter anyway. 

> I understand. You need to use an instance of an ifstream or stringstream to make the changes not permanent. That is very helpful to know.

Someone want to use streams in combination with iomanipulators only for displaying and serialization in non binary formats.

**Comment by Febbe** [comment]
Another thing, if you don't want to cast something, but you function can be generilized for other types, you can just use templates:

```
template <typename Number>
Number Util::setPrecision(Number number, Number decimalPlaces)
{
	auto factor = 10 * decimalPlaces;
	return std::round(number * factor) / factor;
} 
```

**Comment by JJones780** [comment]
Hi SiliconNinja,

 Thanks for your interest in Xournal++!
I see you agree it's best not to change the internal precision.

That leaves the file save precision.  It would be interesting to discover what precision could be lost and how much that would affect the file sizes ( after compression ).
It may or may not be something we want to do.

If you were interested in producing those numbers and letting us know that would be appreciated. At that point a decision could be made whether to mess with the save precision.

**Comment by siliconninja** [comment]
Hi JJones780,
Yes, I would like to participate in getting these numbers.
I will let you know if I have further questions or when I have results.

**Comment by JJones780** [comment]
That sounds great... I'm looking forward to seeing the numbers.

**Comment by siliconninja** [comment]
I'm very close to being able to test it out - I'll keep working on it later tomorrow. I think I know how to continue.

**Comment by siliconninja** [comment]
Well, I thought I had it... now files don't open correctly and strokes appear as a weird line. So I can't make an accurate filesize comparison at this point because the strokes are near the same spot, making the file smaller, even though it has the incorrect contents.
I'll keep investigating this tomorrow, since I don't have much free time left today.

**Comment by Febbe** [comment]
No Problem I can look into your code after the 17th and can help or lead you if you haven't fixed it already😀. Thank you for your interest till now.

**Comment by siliconninja** [comment]
Thank you for your help! I appreciate it. Feel free to look into my code and give help at any time -- I wanted to say that earlier. This didn't end up solving my problem, even though we have less undefined behavior, which is good!

**Comment by siliconninja** [comment]
I haven't completely fixed it yet, so if you can offer any more help, I will have more time to try things out.
I saw that the numbers of the coordinates were shifted over to the left, they weren't the same. So they are still being read properly, but not written properly. I've attached some example files you can look at.

Remove the .zip in the file name, this is a restriction of GitHub not letting me upload .xopp files.

[2019-07-14-Note-22-52-with-4-digit-precision.xopp.zip](https://github.com/xournalpp/xournalpp/files/3394795/2019-07-14-Note-22-52-with-4-digit-precision.xopp.zip)
[2019-07-14-Note-22-52.xopp.zip](https://github.com/xournalpp/xournalpp/files/3394796/2019-07-14-Note-22-52.xopp.zip)

**Comment by Febbe** [comment]
Mmh I have a deadline on Wednesday and here we have 4 o clock, I will look into that on Wednesday or Thursday. This looks like a bigger issue with old plain c IO. But you can try to experiment with << std::right or << std::left. U can also use << std::setw(size) to set the minimum size of the next stream operation.

**Comment by JJones780** [comment]
Oops.. sorry I didn't look at the code earlier.
There's a gotcha to be aware of.

Since we are saving xopp files we want to force using a single locale.. so that decimal separators are the same no matter where the file is written ( comma or dot depending on which locale / country ).
This CAN be done using C++ streams but there are potential issues with changing locales within the same program. You can research this on the web if you want more information.
To make a long story short.. the glib library has g_ascii_____ functions that are made specifically for this purpose. We use g_ascii_dtostr which always uses the 'C' locale and doesn't interfere with the streams.
There is also a [g_ascii_formatd](https://developer.gnome.org/glib/2.30/glib-String-Utility-Functions.html#g-ascii-formatd) which will allow you to limit the number of decimal places used for floats by including for example a ['%.4f' format string](https://alvinalexander.com/programming/printf-format-cheat-sheet#formatting-floating-point-numbers-with-printf)

I suggest you change a few of the g_ascii_dtostr into g_ascii_formatd and then collect some stats from there.

Do not use c++ streams.
Sorry not to chime in sooner.

**Comment by Febbe** [comment]
Mhh I thought the standard c++ locale is the c locale until it is changed.

**Comment by JJones780** [comment]
siliconNinja,   Also, I'd recommend you become a GitNinja too...  Git is a very powerful tool and imo well worth getting to know.

I'm commenting because I noticed you are working on the master branch in your fork of xournal++.  You should be creating a new branch and making changes there. 

Once you get comfortable with the basics I'd also recommend looking into  git rebase  which will allow you to rewrite history and clean things up for contributing back to the projects or just rebase your branch onto the latest master branch to make it easier to PR and merge.
git cherry-pick can be handy to pull commits over to a new branch one at a time too.
git reset   might've been good to step back instead of git revert.
git stash  will be something you'll need to use occasionally as well.

**Comment by JJones780** [comment]
> Mhh I thought the standard c++ locale is the c locale until it is changed.

You'll figure it out  :p

**Comment by siliconninja** [comment]
So for some reason my commits were duplicated. I was experimenting with `git pull --rebase` to avoid a merge commit, but that made things worse, so I used `git rebase --abort`. Also, I was using a `issue_1277` branch on my fork, but I thought the changes from the "upstream" remote on my local repository (which I've set to github.com/xournalpp/xournalpp) weren't being rebased onto the `issue_1277` repository, so I merged them into my `master` branch to see if that would fix the issue. Turns out that didn't fix the issue, and there were no changes.
Thanks for the tips anyway! When I reset my master branch, I used `git reset`, but that requires a `git push --force`, which isn't very optimal.

Anyway, I was able to get it working, thanks to the tip from JJones780! The file size for 4 decimal place precision is about half compared to 15 decimal place precision (wow!), so I recommend putting this feature into the main repo.
I have attached the two files here for reference (remove the .zip from both file names):

[2019-07-16-Note-22-00-with-4-dec-place-precision.xopp.zip](https://github.com/xournalpp/xournalpp/files/3399564/2019-07-16-Note-22-00-with-4-dec-place-precision.xopp.zip)
[2019-07-16-Note-22-00-with-15-dec-place-precision.xopp.zip](https://github.com/xournalpp/xournalpp/files/3399565/2019-07-16-Note-22-00-with-15-dec-place-precision.xopp.zip)


Next up is to make a setting for it, since that was in the issue description.

I don't actually see any difference between the two in terms of image quality from the strokes, it might not be necessary, although I'm not sure if some users want the original 15 digit precision. Here are some sample images:
With 4-decimal place precision:
![Screenshot_20190716_201437](https://user-images.githubusercontent.com/29907828/61338617-f2ac1480-a829-11e9-8e1b-5834e4e92e29.png)

With 15-decimal place precision (original):
![Screenshot_20190716_201423](https://user-images.githubusercontent.com/29907828/61338593-ddcf8100-a829-11e9-9b23-58ceefb4a86e.png)


I'm also not sure if it should be disabled by default - I think it shouldn't in case people don't want their high resolution work compressed when they use it for the first time.

**Comment by siliconninja** [comment]
I could remove the duplicates using `git reset --hard <commit hash before duplication>` and then `git pull`, which would start the merge commit again, but I would need to push using `git push --force origin issue_1277`, which is not usually a good idea.
In general, the rule is not to use `git push --force` which modifies the history permanently, unless it is absolutely necessary:  https://stackoverflow.com/a/9264653. I'm not sure if PRs will be affected since I am using a separate branch from the xournalpp repo. If not, I can undo the duplicated commits, and undo the reverted commit from earlier using `git reset <commit hash before any changes were made>` then `git cherry-pick` the useful commits, since I don't need the unused commits in my local repo for anything. That way the PR would be cleaner.

**Comment by Febbe** [comment]
Hey thanks for the work this looks very good.
For the git usage I recommend to create a git test repo where you learn to use git rebase git push --force etc.. For the master branch and the original repository it is truly a no go to use the force push, but that's why you fork the original, try things out, fix things, then you clean up your fork and create a pull. If you really want to avoid force pushing, you can just create infinite branches until your cleanup is finished. This has the advantage, that your history isn't lost when you make a mistake. You can also create different remote branches from the same local branch with some git push parameters.

**Comment by Febbe** [comment]
Pro tip Google the usage of git rebase -i, it is awesome.

**Comment by Febbe** [comment]
I think me or another collaborator should write a tips and tricks section for git into the wiki.

**Comment by Rmano** [comment]
> although I'm not sure if some users want the original 15 digit precision

If I am not wrong, the measurement units is a postscript point (at least by default), so (72 points = 1 inch = 25.4 mm) 1 unit is 25.4/72 = 0.35 mm  (more or less). Using 4 digits, you go down to 35 micron of precision... I tonk this should suffice for most uses, *unless* we are trying to directly draw integrated circuits without scaling... ;-)

**Comment by Rmano** [comment]
> I think me or another collaborator should write a tips and tricks section for git into the wiki.

I have a (ultra small) thing on contributing here: https://github.com/circuitikz/circuitikz/blob/master/CONTRIBUTING.md

**Comment by Rmano** [comment]
> In general, the rule is not to use `git push --force` which modifies the history permanently, unless it is absolutely necessary: https://stackoverflow.com/a/9264653. I'm not sure if PRs will be affected since I am using a separate branch from the xournalpp repo.

I am using (for my projects) forced push quite a lot, *if they are restricted to your copy of the repository*. My workflow: I work on a branch in my fork, and when I want a review, I publish a (maybe draft) PR on the main repo. If I `rebase -i` (which is awesome) or `--amend` something, then I force push the changes *on my fork*. GitHub is smart enough and will take care of it; the PR will immediately change, and the CI checks will restart. 

That way you can experiment, and show to the main project a clean history. The forced pushes are not dangerous in this scenario, as long as no one is tracking your branch on your fork.

**Comment by JJones780** [comment]
@siliconninja, 
If you max zoom and then draw what are the differences?
Someone might want to place a micro-note on a page at a very high zoom.

Hmmm... consider:
A dynamic precision might also be worth doing. For each stroke: If the minimum difference between any two successive points is 0.001xxx then only save with %.3f but if .00004xx then save with %.5f. Then if the user draws something at max zoom it saves the necessary detail. 
Note:  check out  std::log10( ) but watch out for special cases... like 0.

re: git - Rmano's comments above are exactly my use case as well. Don't be scared to force push on your own fork.

Note the "width" array is the pen pressure. It would also be good to reduce precision there as well.

**Comment by siliconninja** [comment]
I should've mentioned -- those tests (in the screenshots) were at max zoom (700%).
I made another "micro note" with the very fine pen setting under Tools > Pen Settings, and here is where I finally see a difference in image quality:
The note I created:
![Screenshot_20190717_082931](https://user-images.githubusercontent.com/29907828/61375794-4f8de600-a88f-11e9-81d1-c996aa124d48.png)

The images up close at 566% zoom:
![Screenshot_20190717_083807](https://user-images.githubusercontent.com/29907828/61376021-c75c1080-a88f-11e9-97cd-0aa46fd8412f.png)

The left is the original, the right is the one with 4 decimal place precision.
The red line at the end of the curve is less straight on the right one, and the blue line below the ink is less straight overall.


I agree with reducing the precision of the values in the pen pressure array -- I was just testing out the point/stroke coordinates at first to get a baseline comparison. I also agree with having a dynamic precision.

Thanks for the tips and ideas -- later today I plan to start working on the code for those!

**Comment by Rmano** [comment]
Relevant xkcd:

https://m.xkcd.com/2170/

:-)

**Comment by siliconninja** [comment]
> Hmmm... consider:
A dynamic precision might also be worth doing. For each stroke: If the minimum difference between any two successive points is 0.001xxx then only save with %.3f but if .00004xx then save with %.5f. Then if the user draws something at max zoom it saves the necessary detail.
Note: check out std::log10( ) but watch out for special cases... like 0.

I think this is a good idea, but it might be inefficient.
This algorithm that finds the minimum difference for all strokes is O(n^2 **log n**) worst case, since we have to compare each stroke with every other stroke, which is O(n log n) for each stroke. There is an algorithm that computes minimum difference in O(n log n) time: https://www.geeksforgeeks.org/find-minimum-difference-pair/
This comparison is being done for all of them unless we find a stroke with a minimum difference between 0.000000000000001 and 0.000000000000009 (both numbers have 15-digit precision), meaning we can stop searching through the rest of the strokes since we know the minimum difference between those two strokes is that much, so we save all 15 digits using %15f.
It is important because detailed drawings or long notes might take a much longer time to save.
We could optimize this algorithm a bit using caching (so the current stroke and the one it's being compared to both use the same precision when the smallest minimum difference is found), so it would need to do the O(n log n) comparison over n/2 elements worst-case, which is still O(n^2 log n), dropping the 1/2 constant. We would still need to compare the element we just found with the other elements to get an accurate comparison, so we can't remove any elements from the list of elements we're searching for except for the current one (finding the difference between one stroke and the same stroke is not useful). Maybe there is an algorithm that already does this optimization for all elements in an array or something similar.

The easiest option might just be to make the precision an option in the settings, and here's another idea:
the option could be more granular/fine-grained: instead of saying 4/15 decimal places, it would let you specify how many decimal places you want, from 2 (minimum amount for an average note to look good) to 15 (since a double can only have up to 15 decimal places).

**Comment by Technius** [comment]
Before you do any optimization, make sure you benchmark the saving code to verify that performance is actually a problem. Otherwise you'll spend time solving a problem that nobody has. (If it is a problem, there are _many_ heuristics we can use to speed this up).

Another idea to throw onto the space optimization pile: If we're going to limit the digits of precision, we can also just save all numbers as fixed point numbers, i.e. all numbers are saved as integers and then multiplied by a separate exponent factor. Then we can group points up by e.g. digits of precision (such that we minimize average length of each number encoded as a string) to save even more space.

I would prefer that we add a few optimizations as possible, though: someone's going to have to maintain them in the future, and fewer optimizations means that the code is simpler. If space is actually such a big concern, we should be encoding strokes in a binary format anyways so that we only have to store 4 or 8 bytes per number (with _no_ loss in accuracy) instead of the >=8 bytes we're currently using to encode the numbers as strings.

**Comment by siliconninja** [comment]
Okay, that sounds like a good plan.

**Comment by LittleHuba** [comment]
I would also be happier with a binary format for the stroke data as nobody reads it in a text editor anyway. And it would decrease file size tremendously while speeding up accesses.

**Comment by JJones780** [comment]
@siliconninja   The Dyanimic precision idea was only for hand drawn strokes ( a simple O(n) run through and fudge factor ) and we'd have to use a default precision for squares or other tools-drawn strokes. Maybe best to forget about the dynamic precision as it would become a hassle to tune and maintain.
My goal was to, as in the above mentioned XKCD comic ( thanks @Rmano ! ), avoid precision over-over-overkill ;) A fixed reduction of precision should suffice.

**Comment by JJones780** [comment]
Binary Format.  
I totally agree. I opened a separate feature request issue for it. 
Please continue binary format discussion at https://github.com/xournalpp/xournalpp/issues/1362

Our existing format discussion should remain here.

**Comment by siliconninja** [comment]
Hi everyone,
I'm glad I was able to find time over the weekend to start working on things again. I didn't get to starting dynamic precision anyway, so this was the perfect time to respond. I have fixed the width of each stroke, the width/height of the page, other attributes, etc. having 15-digit precision by default in commit b58f9d6, which has 4-digit precision as the default. Now I am working on implementing a setting for it.
I have a question -- in Util.cpp and Util.h where I implemented the precision string formatting helper methods, I need to be able to access the setting for how many digits of precision we want, which is inside of the `Settings` object that holds the settings filename specifically. I saw some code in `Control.cpp` that does this. I was also thinking about moving the helper method to the `XMLAttribute` class, since that's what all of the attributes (DoubleAttribute, XmlPointNode, XmlStrokeNode, etc.) have in common, but `XMLAttribute` doesn't use a `Settings` object already.
I saw some commits specifically for adding settings that used a `Control` object to access the settings. Even worse, `XMLNode` makes a `DoubleArrayAttribute` (line 93 of `src/control/xml/XmlNode.cpp`), and `XMLNode` doesn't have a `Control` object. This makes it difficult to put a `Control` object in `XMLAttribute`, because any `XMLAttribute` object would need to be able to access that. The reason why I want to put it in `XMLAttribute` instead of individual ones is to avoid code duplication.

Is there a better way to go about accessing a `Control` object to access the settings which contains the number of decimal places of precision we want, which we can then access in `Util` or a similar class?

**Comment by Technius** [comment]
This is actually indicative of a major design flaw with the current serialization code (in fact, I have several things to say about it); it would probably have to be rewritten to be more robust to modifications. For now, I think it would be better to focus on hardcoding the precision and getting the size comparison so that we can see if this precision change is actually worth it.

**Comment by siliconninja** [comment]
I've attached a very detailed report of file sizes and a rough quality guideline (pixel comparison). For micro-notes that I've done earlier, I'd guess that about 6-8 decimal places is about where we don't sacrifice any quality for file size.
Rename the .ods.zip file to .ods. Ironic that GitHub supports .xlsx, but not .ods :smile: 
[Coordinate precision vs file size graph.ods.zip](https://github.com/xournalpp/xournalpp/files/3415115/Coordinate.precision.vs.file.size.graph.ods.zip)

**Comment by siliconninja** [comment]
I've also replaced all of the `g_ascii_dtostr` with `g_ascii_formatd` that replaces the doubles with the right precision specified in `Utils.h`.
