### ISSUE TITLE
"zoom to fit screen" should show both pages if showing "paired pages" in landscape

### ISSUE THREAD

**Issue by huzzam** [xournalpp/xournalpp#1345]
I use Xournal++ on a Surface tablet, in both landscape and portrait modes. When in landscape, I often view two pages side by side. Unfortunately, I have to zoom manually to the correct level, as "zoom to fit screen" actually just does "fit width" of one page, thus seeing only the top half of one of the pages. The current behavior does not fit the description of "fitting the screen" IMO.

If showing paired pages, I think "zoom to fit screen" should "fit width" BOTH the pages (if the monitor is in landscape orientation and the pages are portrait). 

As a bonus refinement, the ideal would be to have a separate zoom preset for landscape vs portrait, thus automatically setting (e.g.) paired pages+fit (double) width in landscape, and single page zoomed to fit in portrait.

**Comment by Febbe** [comment]
I have this on my list, but it could be that I've already implemented this in the branch refactor_layout_resize.

**Comment by armsp** [comment]
I am facing the same issue. It would be wonderful if it is resolved as currently I use Foxit which correctly fits a pair of pages but since its Ubuntu, its version is just 2.xx and so the writing experience is very very bad.
I wanted to stick to Xournal, but manually doing it every time for every book is off-putting.

**Comment by Febbe** [comment]
Currently, zoom to fit is disabled, since this is not fixable without rewriting a lot of the code.
