### ISSUE TITLE
Word Wrap for the Text Tool

### ISSUE THREAD

**Issue by rhnvrm** [xournalpp/xournalpp#139]
There should be an option for Word Wrapping the text in the Text tool as it is often required when pasting from wikipedia etc.

**Comment by wbrenna** [comment]
This should be possible, though I recall looking at it and it required a bit more time with some potential pitfalls. Pango word wrapping can be done with something like [this](https://gist.github.com/bert/262331), though it might be confusing since I suspected the gtk_text_buffer might not wrap text during editing - it would wrap only when text is not selected.

**Comment by andreasb242** [comment]
Xournal did not support Text wrapping, so I didn’t implement it. But It’s a feature which makes really sense.

**Comment by andreasb242** [comment]
We will brake compatibility, and the usage is not that high, I close this ticket (cleanup of old tickets...)

**Comment by goekce** [comment]
https://github.com/xournalpp/xournalpp/issues/1756
