### ISSUE TITLE
Text color darkens if a highlighter and non-white background are used

### ISSUE THREAD

**Issue by fxkrait** [xournalpp/xournalpp#1394]
**Affects versions :**
 - OS: [e.g. Linux (which distro), Mac, Windows]
 -- Arch Linux
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]
 -- xournalpp 1.0.12-1
 -- xournalpp-git

**Describe the bug**
- With a colored (non-white) background and highlighter having been applied, text color appears darker than it should.
-- The true color will appear while editing the text
-- Once done editing, the text suddenly becomes darker in color.

**To Reproduce**
1. Apply any colored (non-white) background  to the page color.
2. make some colored text.
3. Then add a highlight anywhere on the page (any color works)
4. Create some new colored text (of any color)
-- notice that this text becomes darker in color (and any future text added is also affected)
-- Furthermore, if you edit existing unaffected text that has the correct color, it will become darker in color aswell
-- Changing background color back to white does not appear to fix this (the text remains darkened)

**Expected behavior**
The "true" text color (what appears during editing text) should be shown on the page after editing.
**Screenshots of Problem**

Non-White Background: Text color affected
![darkBackground](https://user-images.githubusercontent.com/7407672/62431036-b35e3e80-b6d8-11e9-9a49-f5d7641ca1ea.gif)

White Background: Text color unaffected
![whiteBackground](https://user-images.githubusercontent.com/7407672/62431033-accfc700-b6d8-11e9-8ba2-26f8d0d68f62.gif)

**Comment by Technius** [comment]
I did some additional testing:
* The issue only affects pages with _explicitly set page colors_ that have highlighter strokes on them. It occurs on pages with color explicitly set to `#FFFFFF`; it does not occur on pages for which the color has not been explicitly set.
* White colored text will be completely invisible; black colored text is unaffected
* The issue will persist _after restarting the application and reloading the file_.
* The amount of darkening depends on the color of the highlighter.
* Selecting any affected text (by itself) with Select Object or Select Rectangle will temporarily "fix" the issue. But trying to perform any sort of action may cause the issue to occur again (doesn't happen 100% of the time).
* **If all highlights are deleted from the affected page(s), the issue no longer occurs.**

I suspect the cause of the issue is somewhere in the highlighter rendering code.

**Comment by fxkrait** [comment]
@Technius From what I can see, I do not believe that this occurs on pages with color explicitly set to #FFFFFF. The amount of darkening seems to be directly related to the "darkness" of the background color.

Same color text, but darker background seems to darken text more:
![dark](https://user-images.githubusercontent.com/7407672/62450797-de20b500-b721-11e9-898d-c1afe2487814.png)
![light](https://user-images.githubusercontent.com/7407672/62450802-df51e200-b721-11e9-9746-ef06293d0c52.png)

**Comment by Technius** [comment]
Did some sniffing around today, and I found that when highlighter strokes are present on a page, text objects are rendered after the background is rendered, hence why the background color is tinting the text. It won't take much longer to identify the root cause.

**Comment by Technius** [comment]
The PR should fix the issue, but please note that there's still bugs in highlighter rendering (see #1402 for more details). Let me know if there's any other problems.
