### ISSUE TITLE
Opening broken file can corrupt current document 

### ISSUE THREAD

**Issue by tumb1er** [xournalpp/xournalpp#1397]
By default, xournalpp creates a blank document. If you open corrupted document and it fails, like in #1393 current blank document become corrupted too.

**Affects versions :**
 - OS: Ubuntu 19.04
 - Version of Xournal++ 1.0.6-0~201908020631~ubuntu19.04.1 

**Describe the bug**
Currently opened document is corrupted while opening broken file.

**To Reproduce**
1. Launch xournal++. It creates new blank document.
2. Open corrupted file from archive. XML parser error is shown.
3. Draw a stroke in current blank document.
4. Save it as a new file.
5. Try to reopen this file.
6. New document is opened with hidden background layer and xournal++ crashes while showing background.

**Expected behavior**
After broken file open error, current document is valid and can be saved and loaded correctly.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/1587241/62472718-018e4300-b7a8-11e9-8986-b2ad2b47a044.png)

**Additional context**
initial corrupted file is attached as [2019-08-03-Note-16-17.zip](https://github.com/xournalpp/xournalpp/files/3468056/2019-08-03-Note-16-17.zip)
new corrupted file is attached as 
[new_corrupted.zip](https://github.com/xournalpp/xournalpp/files/3468075/new_corrupted.zip)

**Comment by siliconninja** [comment]
Hi @tumb1er,
I found a potential fix for this problem and I've opened a PR for it.
What the code from the PR does: If the file was not loaded correctly, it will keep the existing document in the window, regardless of whether the document was saved or discarded (which I would expect, since I might want to continue working if the file wasn't loaded correctly). When this happens, you can check/uncheck the background layer and the document works like usual.

**Comment by siliconninja** [comment]
Specifically, my closed PR fixes opening the "2019-08-03-Note-16-17.xopp" file (since that displays a coordinate error in the message box, and if that happens, the current document shown in the window doesn't get "closed" and destroyed, meaning it can still be used), but it does NOT fix opening the "new_corrupted.xopp" file (since the file opens properly, and nothing is shown).

It also fixes if I try to load something from another file type (non-XOPP), such as the ZIP file itself that you posted, if I type to search in the open dialog (i.e. I have document with strokes in it in the current window and I click File > Open, type "new_corrupted", then double-click on "new_corrupted.zip".

I think the "new_corrupted.xopp" error comes from the XML parser ignoring stuff and not returning any errors.
