### ISSUE TITLE
Repeated white background flash on larger colored background documents

### ISSUE THREAD

**Issue by fxkrait** [xournalpp/xournalpp#1405]
**Affects versions :**
 - Arch Linux
 - xournalpp 1.0.12-1

**Describe the bug**
Background repeatedly flashes white on colored background document that contains multiple pages and multiple text items.

**To Reproduce**
1. Make background light gray color for all pages
2. make 13 pages (just to make a lot of pages, it can happen with less)
3. On first page, create a large text block, and copy and paste it multiple times (to create a lot of text in document)
![firstPage](https://user-images.githubusercontent.com/7407672/62771250-a8493c80-ba51-11e9-9d7c-6718a843448b.png)

4. go to second page, and make some new text
5. Notice flashing

**Expected behavior**
Background should not flash white.

**Screenshots of Problem**
gif of flashing:
![flash](https://user-images.githubusercontent.com/7407672/62771301-c151ed80-ba51-11e9-8c39-323ae2916e3d.gif)

**Additional context**
Note: This does go away if the file is re-opened.
However, I do believe it will soon happen again in the same document upon further editing (and additions).
The flash can also occur when scrolling around the document.

**Comment by lehmanju** [comment]
Related to #1107

**Comment by ehremington** [comment]
This very annoying since it means that the projector screen is flashing at my class full of students.

This happens for me when I have zoomed in to a portion of a page and then start writing, although it seems sporadic even in that case.

**Comment by LittleHuba** [comment]
I isolated the problematic section of code:
```
void XojPageView::paintPageSync(cairo_t* cr, GdkRectangle* rect)
{
	XOJ_CHECK_TYPE(XojPageView);

	if (this->crBuffer == nullptr)
	{
		drawLoadingPage(cr);
		return;
	}
```

For performance reasons we have a cleaning job that removes the buffers of pages that were not rendered for a longer time. This will remove the variable crBuffer which triggers a repainting of the Loading-Page (the white flicker...)

I'm still searching for the best way to fix this.

**Comment by LittleHuba** [comment]
If you are not interested in the technicalities you may ignore this post. 

Okay so the problem is as follows:
Xournal++ draws pages in two steps:
1. Render the contents onto a buffer surface to minimize the time consumed by the overall drawing process
2. Draw the actual view
2.1. Draw the background of the view
2.2. Draw the shadows around the visible pages
2.3. Draw the visible pages using the buffers from step 1

Additionally we have the cleaning job that purges the buffers created in step 1 if there are a lot of pages and the page was not visible for a longer time.

Now when we trigger a repaint of a page that had its buffer removed by the cleaning job the following happens:
- We draw the background of the view itself
- We draw the shadow around the page
- We find the buffer missing and draw the loading page
- We trigger a rerender (step 1 above) which recreates the buffer, renders the page to the buffer and triggers another paint of the view

As you can see only removing the drawing of the loadingpage is not enough as then we will get the background of the view drawn and a shadow but the page will just miss. We can also not just do the rendering for that page in the painting phase, since that would block our UI-Thread, making the program unresponsive.

Now to the final solution, which is a bigger effort but currently the only solution I see (correct me if I'm wrong...):
We need to rewrite the painting system to not paint a background for the view underneath the pages, but only for the areas where it is actually visible. The area where the page is drawn shall never be touched, except there is actually a buffer available from which can be drawn.
Finally we have to reevaluate the loading page. It will be only drawn once initially when the page has not yet been rendered (loading of a document or creation of a new page).

**Comment by JJones780** [comment]
Are you sure this requires a design fix...?  I say this because pages that are visible should not be invalidated.

I've only had a quick look:

void Layout::updateVisibility() - determines if page is visible and calls setIsVisible()

void XojPageView::setIsVisible(bool visible)  - sets time when first noticed to be non-visible or 0 if visible.

used by gboolean XournalView::clearMemoryTimer(XournalView* widget)  to clear out old pages ( by sorting based on time first unseen.  **Only pages with non-zero ( i.e. not currently visible ) are considered.**


Another thing to look into would be the process by which the buffers are invalidated when the user zooms in or out. Maybe this is where the buffer is being invalidated accidentally?

**Even if the page is zoomed we shouldn't be showing the loading page**.. it will scale the current pixbuf and rerender later:  see: void XojPageView::paintPageSync(cairo_t* cr, GdkRectangle* rect)

I'm out of time...  will look again another day.
Enjoy the Morocco bakeries @LittleHuba !

**Comment by LittleHuba** [comment]
> Are you sure this requires a design fix...? I say this because pages that are visible should not be invalidated.

We are talking about pages that have been out of view and are scrolled to again. They have an invalidated cache which results in these errors. The invalidation is a valid thing but the painting algorithm is not able to handle this in a good way...
Additionally they are invalidated for zooming sometimes. I think this is done for HighDPI but this part of the code is not really well documented so I could be wrong.

> Enjoy the Morocco bakeries @LittleHuba !

Thanks! Will do!

**Comment by JJones780** [comment]
I'll apply this fix now
... and look into the other potential issues when I get the time.
re: look into into buffer invalidation efficiency, operation during zoom
