### ISSUE TITLE
change standard select tool

### ISSUE THREAD

**Issue by JulianGro** [xournalpp/xournalpp#1563]
**Is your feature request related to a problem? Please describe.**
Trying to find the select tool can be difficult for the first time. I personally didn't recognize the red box as a selection tool.

**Describe the solution you'd like**
I personally think that the "Object select" tool has an icon which would be much more easily identifiable. So that tool could be used by standard, rather than the "rectangle select".

**Describe alternatives you've considered**
I feel like changing the icon from a red rectangle to a cursor with a red rectangle, would make it more clear, what this tool is doing.

**Comment by Technius** [comment]
The dotted rectangle is a common icon for a rectangle select tool. I think it's important to be consistent with common conventions.

[Photoshop](https://helpx.adobe.com/photoshop/using/selecting-marquee-tools.html):
![image](https://user-images.githubusercontent.com/1066652/69490399-13215680-0e3c-11ea-9e7d-ca8eec0e3578.png)

GIMP:
![image](https://user-images.githubusercontent.com/1066652/69490370-bc1b8180-0e3b-11ea-82a4-0d8179ca2e63.png)

Krita:
![image](https://user-images.githubusercontent.com/1066652/69490375-c5a4e980-0e3b-11ea-9290-c0102b29b569.png)

However, we _could_ try combining the select rectangle and select object tool, since that could feel more intuitive.
