### ISSUE TITLE
Program neither Saves nor Loads

### ISSUE THREAD

**Issue by Crazycolbster** [xournalpp/xournalpp#1572]
**Affects versions :**
 - OS: Linux Mint 19.1
 - Cinnamon
 - libgtk 3? I'm not entirely sure.
 - Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]
1.0.15

**Describe the bug**
When Saving and Loading, the dialoug box won't change directories. When saving to /home,
the file doesn't actually save. Loading finds no files and doesn't detect several subdirectories.

**To Reproduce**
1. Create any file, a single stroke works
2. Attempt to save, you'll notice the directory won't change
3. Attempt to load, no files will be found.
4. Cry at the 2 hours of homework you lost.

**Expected behavior**
The program saves the file and opens it at a later time.

**Screenshots of Problem**
![image](https://user-images.githubusercontent.com/43626579/67611615-3337fa00-f758-11e9-9eb8-07f926a103d5.png)
Saving really doesn't work.

![image](https://user-images.githubusercontent.com/43626579/67611641-624e6b80-f758-11e9-9aaa-8e0eec6f110f.png)
Neither does loading...

**Additional context**
I'm not that proficient in Linux, and this is the first time I've submitted a bug in Github, so sorry if there's something off.

**Comment by Crazycolbster** [comment]
If anybody reads this within the next 3 hours, my assignment is due at 12 tonight MST. Is there any way whatsoever I can at least open the old autosave file?

**Comment by LittleHuba** [comment]
Do you have installed a GTK Icon Pack?

**Comment by Crazycolbster** [comment]
I think I do, but I'm not sure. I'm using Linux Mint 19.1, which has flatpak support, but I'm not sure if it has an Icon Pack installed by default. How would I check?

**Comment by Technius** [comment]
I assume your desktop manager is Cinnamon if you're on Linux Mint? Then you should already have appropriate themes installed. If so, the problem is something else.

Are you using Xournal++ through Flatpak? AFAIK for Flatpak, there's some permissions that you'll need to set in order to save/load files in arbitrary folders. By default, the Flatpak manifest (on FlatHub) only [allows access to the `~/Documents` folder](https://github.com/flathub/com.github.xournalpp.xournalpp/blob/8d2af0aef66de1a7fce51931700171dd7875a246/com.github.xournalpp.xournalpp.yaml#L14).

**Comment by Crazycolbster** [comment]
I am using Flatpak, yes. I couldn't install it through the apt. How would I set these permissions?

**Comment by Technius** [comment]
A quick workaround is to apply an override that allows access to any file:
```bash
flatpak override --filesystem=host com.github.xournalpp.xournalpp
```
Note that this defeats the purpose of Flatpak sandboxing, though.

**Comment by Crazycolbster** [comment]
Well, that did the trick. Would there be a way to install the flatpak and still give it permission? This is my first time using Flatpak and I live in fear that other programs will give me similar issues now.

**Comment by Technius** [comment]
I did some more investigating, and you can try the following line to make saving/loading through the file chooser work if you do not want to use the catch-all filesystem permission:
```bash
flatpak override --system-talk-name=org.freedesktop.portal.FileChooser com.github.xournalpp.xournalpp
```
Unfortunately, this is not perfect because it may make autosaving work incorrectly: you will only be able to retrieve the 2nd oldest autosave, and only from `~/.xournalpp/autosave`.

We will need to update the README with this information in the near future.

**Comment by muelli** [comment]
Interesting indeed.
Is xournalpp not using a native file chooser from GTK?
That should work out of the box.

**Comment by Febbe** [comment]
@LittleHuba this could be a serious reason to use std::filesystem and std::ofstream. With that exceptions were thrown which signal the user to choose a folder with write access.

**Comment by LittleHuba** [comment]
Yes that is true. I think it is a good idea to incorporate std::filesystem even if it is some pain to do so.

**Comment by Technius** [comment]
The `host` permission has been enabled on the Flatpak by default (flathub/com.github.xournalpp.xournalpp#13). Unfortunately, we couldn't think of a good solution and this was the best compromise we could come up with before we can get a new file format out.
