### ISSUE TITLE
Centred zooming

### ISSUE THREAD

**Issue by cass00** [xournalpp/xournalpp#161]
As a follow-up to the the pinch-to-zoom feature (#160) , I tried to make the zoom pointer centred following commit gnome/evince@9d9e14dfa. Please see commit cass00/xournalpp@fcf3ba9f01 ( and previous commit cass00/xournalpp@fd5beb6224b) for a prelimanry version. It works quite well for ctrl+mousewheel (despite small offset), however it is very buggy for the pinch-to-zoom action.

Short explanation how it works: A pivot point is defined by either the position of the mouse pointer or the centre for the pinch-to-zoom action, which is kept static in the current view by using the ```scrollRelativ``` function with calculated shift values. This pivot point could for example be the centre of an image one might want to zoom in. Please be aware that the internal coordinates for the pivot point (with respect to the document) change after each zoom action, as the total size of the Xournal widget changes. 

Somehow, this concept gets messed up for the pinch-to-zoom case, as I usually end up in the bottom right cornor after a few zoom attempts. Is there a strict temporal order for zooming actions in xournalpp? This issue might be related to the hand tool problem #162 .

**Comment by wbrenna** [comment]
Hm, I'm not sure exactly how to fix this at the moment but I can definitely acknowledge that it's not unexpected - the hand tool jitter is also something that I noticed on an install a while ago, but it appears to happen only in certain environments and right now none of the systems I use exhibit bug #162. 

I haven't had much time lately to be working on these issues but one thing that you may first look at is the behaviour in different modes of operation. In particular, ```Presentation Mode``` in the View menu will keep pages centred, and so maybe the hand tool behaviour is particularly affected by that? On my systems it works normally in either mode.

**Comment by cass00** [comment]
I've done some testing and it seems that the scrolling (i.e. change in the adjustments) is interfering with the pinch-to-zoom gesture. In particular, a scrolling action can lead to an abrupt change in the size of the bounding box of the gesture, as event coordinates are not updated properly (become a mix of pre-scroll and after-scroll positions). This leads to an erroneous zoom behavior. In contrast to the handtool issue #162, there is no option to use root coordinates (which would not be changed by a scroll action) for the gesture. I can post a more detailed explanation if wanted. 

However, this is a gtk problem and should be addressed somewhere else. Possibly there is some workaround, as centered zooming works well in evince, even though I can't see much difference between the different implementations.

**Comment by wbrenna** [comment]
There should be some workaround. We have raised some questions with the gtk3 team about canvas drawing in the past and the response hasn't led us to solve the problem, but if you'd like to ask them how they would fix this, they do have a mailing list for that!

**Comment by cass00** [comment]
Went to the irc channel yesterday and asked. Even got a reply, but couldn't directly answer the questions I got in return ("what's the gesture's widget? the scrolledwindow or its child? is the child a GtkScrollable?"). Will try again some time later.

I'm wondering if there's any document describing the program structure in more general terms. The code is quite convoluted and hard to browse, if one doesn't know where to look directly.

Furthermore, is there any priority list with things to fix in regards to a (fully) working gtk3 version?

**Comment by wbrenna** [comment]
Unfortunately I don't think anyone has had the time or initiative to describe the entire program structure. You're right that there is a bit of a learning curve; I can do my best to answer questions and there are a few others here who also know quite a bit about it. At one time trello was suggested for a roadmap and info about the program but that didn't seem to take off. 

I think for things to fix for gtk3, the highest priority items are the sluggishness of drawing (which is described a bit in issue #109, and seems to be due to the way we place strokes onto the canvas though it's unclear exactly how this needs to be done to work with gtk3 properly - according to the gtk3 people it was done 'wrong' from the start but gtk2 had good performance anyways), and also the entire threading needs to be redone for gtk3. I understand that gtk3 deprecates gdk_threads_enter so all those calls need to be removed, and there was some deadlock that I noticed when going to gtk3 so currently I run it single-threaded only until this is fixed. Other than those two things, filtering Issues with "High Priority" - all of those issues will be the highest priority items that will also apply to gtk3.

Hope that helps! And thanks for your work so far!

**Comment by andreasb242** [comment]
@cass00 
>I'm wondering if there's any document describing the program structure in more general terms. The
>code is quite convoluted and hard to browse, if one doesn't know where to look directly.
Sorry for that ;-)
I first only would improve Xournal a little bit, but It's fully written in C, with struct, and GTK canvas etc.
So the way was to port Xournal structs to C++ classes, e.g. Stroke Recognize is a 1:1 copy of the original Xournal code, only put into a class...
(Written by Denis Auroux, he helped me to understand the code: In short, it's only physics ;-))

The logic is mostly splitted up into model / view / control, as you may learned it in a school, the Model contains the Data, the View display it, and the controller handle input and contains the business logic.

This code structure is based on the XML file format (you may have a look at .xoj files), but completely new written for Xournal++.

The GUI is bases on GTK (C API) not GTK+ (C++) API because I started with Xournal Code, and there is a much better Documentation for GTK than GTK+.

I used always Eclipse CDT for development, with this you can simple brows through the code, show references etc. I know, a lot of people don't like Eclipse, but it's may a try worth for you ;-)

I did this project at study, now I'm not active working on it any more, but I'm mostly reading the notifications from GitHub.

**Comment by MarPiRK** [comment]
I've been using Netbeans to develop Xournal++. It may not have the greatest support for C++, but if you really don't like Eclipse, it's worth trying ;)

**Comment by cass00** [comment]
Found a solution to the problem. Following up on the question I got in the #gtk IRC channel ("what's the gesture's widget? the scrolledwindow or its child? is the child a GtkScrollable?"), I changed the gestures widget from the XournalView widget to its parent and it works fine.

Also, thanks for your input.
