### ISSUE TITLE
Scrolling by touchscreen doesn't update page number

### ISSUE THREAD

**Issue by wullli** [xournalpp/xournalpp#1621]
First of all thanks for the great work. I am finally able to take my lecture notes on Linux and don't have to run windows just for this purpose. Now also works fine with wayland.

**Affects versions :**
 - OS: Arch Linux 5.3.11
 - Version of Xournal++: 1.0.16-1

**Describe the bug**
Scrolling by touchscreen doesn't update page numbers. So when a new page is inserted, it will be inserted at a different position than expected

**To Reproduce**
1. Open PDF to annotate
2. Select Page n
3. Scroll 2 pages down
4. Insert new page
5. Page will be inserted at position n+1 instead of n+3

**Expected behavior**
Page should be inserted at position n+3

**Comment by redweasel** [comment]
This is expected behaviour. Scrolling does not change the active page, drawing does change it.
The new page is always inserted after the active page. This is no bug. Maybe this can be rephrased as a feature enhancement, but I think it is good as is. Also with the new infinite page system coming up it will change a lot.

I think this bug can be closed

**Comment by LittleHuba** [comment]
That is actually a bug that was recently fixed by me.
The nightlies have the new behaviour.
