### ISSUE TITLE
[Mathtex] Change LaTeX formula size

### ISSUE THREAD

**Issue by light2yellow** [xournalpp/xournalpp#163]
Is it possible to change it's size? It just looks too big. Also, is it possible to drag-and-drop it on some another part of the document?

**Comment by wbrenna** [comment]
Do you mean by default? Because after creating the TeX, you can select the object and resize it using the boxes at the corners. If the resolution looks bad, you can then rerun the TeX command on the object by using ```CTRL-SHIFT-X``` or the ```Add/Edit TeX``` menu option - it will know the stored TeX and upon rerun it should preserve the size of the object but correctly determine the resolution.

It also should be simple to select the TeX object and drag it to another page or another part of the same page. Copy and paste should work fine as well. Are there any bugs you've noticed?

**Comment by light2yellow** [comment]
~~Well... this sounds a bit foolish, but with what tool could I select TeX as an image?~~
Finally found "Select object" tool. Sorry for inconvenience.
About preserving size while detecting resolution and better rendering next time: I've spotted that this only works if you resize the object, than press somewhere else, than choose an object again and press `ctrl-shift-x`.

**Comment by wbrenna** [comment]
That's right - when you press somewhere else it commits the resize into the undo stack and puts the modified object onto the canvas. Ideally this will eventually happen when you let go of the mouse button during a resize but currently it requires this slightly clunky mode of operation.

**Comment by light2yellow** [comment]
Thanks for the information. If you have nothing to add, I'm closing this issue.
