### ISSUE TITLE
diff compatible file format for managing note with VCS

### ISSUE THREAD

**Issue by dadosch** [xournalpp/xournalpp#1649]
**Is your feature request related to a problem? Please describe.**
often pdf are updated and you want to keep your notes compatible to the pdf background or there are multiple version of a anotation.

**Describe the solution you'd like**
One way would be to a file format which shows the changes (is not zipped, like currently). This would allow users to manage their notes using a VCS and thus make it possible to merge different note versions into each other etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by LittleHuba** [comment]
This is unfortunately not compatible with the list of requirements we have for our new file format. Especially the internal attachments are a problem here as even VCSs do not like to version binary files for obvious reasons.

Also merging different notebook versions into each other is fairly complex, as the format is quite complex if you can not visually merge things. While visual merging would be possible, it is in essence opening both document and copy&pasting from one document to the other.

Sorry to turn your request down.

**Comment by LittleHuba** [comment]
I have good news!
I just had a talk with @andreasb242 about another problem and he came up with a solution for that problem which might influence your problem as well.
Since the new fileformat will include the feature of only loading the parts of the document that are actually needed into RAM, the undo/redo system is quite complex. Except that it is not. We will actually use Git internally to version the file between specific actions.

Now here is the thing. If we use Git internally we could provide a feature to not remove the additional files of git when saving, which would increase the filesize but allow people to actually tamper with the history of the file as if it was a normal git repository. This would also mean that merging two files is in essence merging two git repositories. While this does not really improve merge-conflict handling it does tremendously simplify merging of files which do not donflict (people working on different pages,...)

So managing notes within a VCS is still hard as we rely on the ZIP compression to get one single file but we can allow you to make each individual note file a VCS itself. And you can jump to prior versions of the file quite easily. But no promises on the filesize. VCSs do have quite an overhead.
