### ISSUE TITLE
Palm rejection not consistent

### ISSUE THREAD

**Issue by ziekke** [xournalpp/xournalpp#170]
I am using Surface Pro 3. I have Touch Screen set to my NTRG... device, disable drawing and tool: hand.

Problem is that way too often the palm rejection isn't kicking in properly (or at all?) causing the page to jump around everytime I shift my hand to continue writing. Makes precise writing difficult. Wasn't as bad of an issue on Xournal - I experience the issue once every 10-15 minutes - whereas Xournalpp has the issue at least every minute.

**Comment by wbrenna** [comment]
This is an interesting problem - from my limited understanding (I use graphics tablets rather than screen digitizers) it can be solved from either the driver level or the application level. On my one device with an active digitizer I have a shortcut to enable/disable the touchscreen which could be a workaround, at least until this gets properly implemented in Xournalpp.

**Comment by cass00** [comment]
I'm on the same device as ziekke and I can confirm that there is a problem with the touchscreen while writing with the pen (on the gtk3 branch). In xournal (not pp) pen proximity disables the touchscreen, however it seems that xournalpp does not have this option.

**Comment by andreasb242** [comment]
I've bought a Lenovo Helix (used) and found exactly the same Issue, i found already a workaround.
I try to fix this.

**Comment by andreasb242** [comment]
Not perfect (GTK issues, and still room for improvements) but mostly fixed with https://github.com/xournalpp/xournalpp/pull/438/files
