### ISSUE TITLE
How to insert text？

### ISSUE THREAD

**Issue by morkong** [xournalpp/xournalpp#1715]
I select "text" in the [tools] menu, and when I click PDF, I cannot input text through the keyboard

**Comment by Technius** [comment]
What OS are you using?

What version of Xournal++ are you using?

Do you have the new input system enabled?

**Comment by Febbe** [comment]
I can reproduce this on my Desktop: 
- Linux Mint 19.3 Cinnamon (Ubuntu 18.04)
- libgtk-3.0v3.22.30-1ubuntu4
- X11
but i cant on my Yoga with Linux Mint 18.x Cinnamon (Ubuntu 16.04).

**Comment by Febbe** [comment]
changing the input system: works
After checking my devices: Somehow my Razor keyboard shows up.
I don't know why it appears there but this was the cause. It fetched all input events.
Changing it to Disabled helped.
![grafik](https://user-images.githubusercontent.com/2228627/73285544-7c379880-41f6-11ea-8ca0-fc5bb660703c.png)

@LittleHuba can I do something to improve the behaviour here?
Obviously the events from the device aren't handled, so unhandled events should be returned am I right?

**Comment by flo2k** [comment]
I had the same problem here on my Linux Mint 19.3 Tricia with mate desktop and xournalpp version 1.1.0+dev built on 18.04.2020. I have a Logitech MK710 keyboard with a M705 mouse. In the _Input System_ settings on Logitech MK700 there was _Mouse_ chosen (I assume automatically). After changing this to _Mouse+Keybaord Combo_, the input of the keyboard is recognised and I can enter text into the text entries within a page.

A possible improvement could be the automatic recognition of mouse vs. keyboard and setting  _Mouse+Keybaord Combo_ instead of _Mouse_. But I don't know if this is possible. Right now, I'm not into the xournalpp source code.

**Comment by Febbe** [comment]
Yes flo2k, we added this device for exact that reason. Unfortunately, it is not that easy to detect devices automatically.
