### ISSUE TITLE
Can't type Chinese and Japanese

### ISSUE THREAD

**Issue by ghost** [xournalpp/xournalpp#1780]
- OS: Windows 10
 - Version of Xournal++: 1.0.17
 - Installation method: official release(from this site)

bug:
I can't type Chinese and Japanese in the software.

1. choosing the tool "text"
2. typing Chinese or Japanese.
3. there was nothing happen!!

Expected behavior:
the word I typed should appear on the page.

**Additional context**
The IME I used is built-in by Microsoft, Chinese (Traditional, Taiwan)(微軟注音) and Japanese(日文).

**Comment by andreasb242** [comment]
The issue is probably, that the whole input handling is done manually.

https://github.com/xournalpp/xournalpp/blob/master/src/gui/inputdevices/KeyboardInputHandler.cpp

The whole handling is then in:
https://github.com/xournalpp/xournalpp/blob/8052bee481f202f3d148ec8337f560e3719dce2f/src/gui/TextEditor.cpp
Method: onKeyReleaseEvent

@Tamaya1998 are you a developer?
Or at least an advanced user?

The issue: I do not speak / write any language of this kind, and probably nobody of the current developer does. But I think I know where the issue is.

Is it right, that you have to press multiple keys to get one Letter?
You get some kind of Popup or so, right?
I'd expect that not even this happens, right?

If you are a developer, provider more information about such input system, if you can.

Or if here is any developer which knowledge of this input methods, please explain / help, how we can solve such an issue. Thanks!

**Comment by Technius** [comment]
This might be Windows specific, since it works for me on Linux:

![xpp_textinput](https://user-images.githubusercontent.com/1066652/77257305-a757ca80-6c30-11ea-81a1-c0c0901e056d.gif)

**Comment by Voladorwoo** [comment]
typing Chinese  is not working well on my mac...

**Comment by Technius** [comment]
Superseded by #1997.
