### ISSUE TITLE
Cannot use mouse after switching windows when pointer moves into Xournal++ window with tablet

### ISSUE THREAD

**Issue by ReekyStive** [xournalpp/xournalpp#1789]
**Affects versions**
- OS: Windows 20
- Version of Xournal++: 1.0.17
- Installation method: Official Release

**Describe the bug**
Cannot use mouse in Xournal++ after using pen to switch to other windows. This problem does not occur when Xournal++ is always the active window, or when the window is switched using the mouse.

I also found that if the last time I moved the tablet with the tablet and the pointer was inside the Xournal++ window, I also couldn't use the mouse after switching the window with the keyboard.

**To Reproduce**
1. Open Xournal++
2. Use the tablet to move the pointer into the Xournal++ window (no need to click)
3. Use the tablet to click anywhere outside the Xournal++ window, or use Alt + Tab to switch windows
4. Your mouse should no longer work in Xournal++

**Comment by rainllo** [comment]
I'm getting this problem too on my 2in1. For my setup I assigned the mouse to act as a touchscreen. If I open Xournal++ the touchscreen works normally. I'm able to scroll through the page and click the toolbar buttons. But, the moment I click into another window, such as the file explorer or my browser, and then return to Xournal++, it doesn't react to finger input. I can't scroll through the page or click anything on the toolbar, and I can't even close the app using the touchscreen. 

However, pen input doesn't seem affected and I'm able to click all buttons normally using my stylus. 

It's a bit problematic for me because I like to use Xournal++ in split-screen, with a lecture video on the left half of the screen and notes on the right.

**Comment by LittleHuba** [comment]
Sounds like a GTK problem. Our internal input recognition is only for the drawing area.
Can you check if the problem exists as well with other GTK applications?

**Comment by LittleHuba** [comment]
This seems related to #1519 and extends the case. I'll close this in favour of the older ticket. As mentioned there. It is an upstream issue so please file the bug report with GTK.

**Comment by gerroon** [comment]
Is it possible to compile XournalPP with a previosu version of GTK that does not have this issue? As of now the windows version is useless, nearly almost and prone to loosing work. 

I personally recommend that you remove the Win builds with the current state.
