### ISSUE TITLE
LaTex - in Black Background isn't readable at all. The Font size and color can't be set manually.

### ISSUE THREAD

**Issue by dishantpandya777** [xournalpp/xournalpp#1852]
The issue is quite reproducible. 

When you are using default or white Paper / Background... There's no issue.

But when you change to say Black BackGround, then there is no way to cope up with LaTeX. The writing is not readable at all because of the Black Fonts in LaTex Output and the Black Background.

I tried to give the command to change the LaTex fonts color but they reverted with error. So, it seems there's no other option at present.

Please help as I needed to Create a Video Lecture and unable to handle this situation.

I am using in Linux (for above situation).

Thanks.

**Comment by tattsan** [comment]
The following method is a workaround.

Xournalpp uses standalone.cls for temporary .tex file. And standalone.cls includes standalone.cfg.
So if you write  \Requirepackage{color} or  \Requirepackage{xcolor} in standalone.cfg, you can use color latex commands.

**Comment by eldad-a** [comment]
> The following method is a workaround.
> 
> Xournalpp uses standalone.cls for temporary .tex file. And standalone.cls includes standalone.cfg.
> So if you write \Requirepackage{color} or \Requirepackage{xcolor} in standalone.cfg, you can use color latex commands.

Thanks!

Is there a way to have a specific `standalone.cfg` file  for `xournalpp`? 

Modifying the system-wide `standalone.cfg` file works. However, creating one in the `.xournalpp` folder, where the configuration files are, showed no effect. 
This is on `Ubuntu 18.04.4 LTS bionic`; xournalpp installed from the ppa, following the [instructions](https://github.com/xournalpp/xournalpp).
Had to install the dependencies listed [here](https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md), otherwise xournalpp crashes when opening `preferences` from the `edit` menu; this is reported in issue [#917](https://github.com/xournalpp/xournalpp/issues/917).


BTW, on my system the `p` in `\Requirepackage` needed to be upper-case, that is:
```LATEX
\RequirePackage{xcolor}
```

**Comment by Technius** [comment]
I'm planning on adding configuration options to the latex tool in the upcoming week(s).

**Comment by tattsan** [comment]
@eldad-a I put user's standalone.cfg at `${HOME}/texmf/tex/latex/foo/bar/`. PDFLaTeX engine also reads files on current directory (where the engine invoked), but it is temporary directory at /tmp/ in this case. In this method, I can't pass .xopp files to other persons. So the above @Technius 's plan is the best way.

> BTW, on my system the p in \Requirepackage needed to be upper-case, 

Sorry, I corrected that typo. Thanks.

**Comment by eldad-a** [comment]
Great, thank you!

The Xournal++ adds very useful functionality on top of what Xournal already had.
Much appreciated!
