### ISSUE TITLE
new document filename specified from command line

### ISSUE THREAD

**Issue by petergthatsme** [xournalpp/xournalpp#1872]
It would be great if one could provide a file name for a new document via command line. 
So doing 
```
xournalpp new_file.xopp
```
could start xournalpp and the document would already be named `new_file.xopp`. In this case when the user would do a save, no new file-browsing pop-up would appear requesting for naming the doc. 
This is of course standard behavior for editors, etc. 
thanks

**Comment by Technius** [comment]
Better UX would be `xournalpp --new new_file.xopp` since a typo when trying to opening an existing file could cause a lot of confusion.

**Comment by petergthatsme** [comment]
i don't feel very strongly one way or the other, however I'm not sure what would be confusing... if a file exists, then it is opened.... if not, then a new (empty) document is created that has the default save-file-name set to whatever the user provided... this is what all text editors do. Or am I missing what you're saying?

**Comment by Technius** [comment]
What I mean is that if there's a file called `foo.xopp`, then running `xournalpp foi.xopp` (a typo) will print an error saying that there is no such file called `foi.xopp`. The idea is that this will prevent the user from panicking if the command opens a blank document (e.g. maybe they think that the file has been deleted or corrupted).

Yes, we could set the default save name, but it doesn't avoid panics that are caused by opening blank documents.
