### ISSUE TITLE
Touch as Hand Tool

### ISSUE THREAD

**Issue by mazeprince** [xournalpp/xournalpp#194]
Hello,

i use Xournal mainly for PDF annotation.
Since Xournal still has no Search for the underlying PDF, i just tried xournalpp, and the search is working beautiful. 
But i have a problem with my touchscreen. I have a Lenovo Thinkpad Yoga, which has touchscreen and a digitizer. The Pen is working out of the box. To configure the touchscreen i went in to settings and could select my touchscreen as input and chose handtool. 
It is working, but when i use the pen again, the hand tool is still selected.
Has anybody an idea how to get something like "Use Touch as hand tool" like in Xournal?

It works flawless if i for example use the right click as hand tool.
Should it work? Or is it simply not implemented? Anybody has an idea where to look in the code to implement a toggle?

Have a nice day

**Comment by Erudition** [comment]
I have the same issue. It seems that selecting a device to be used as a hand tool, or any tool for that matter, is indeed switched to the hand tool but is not reverted to the previous tool when released.
So you go to drag the page, and then when you try to write again the pen just drags the page.

**Comment by xiamaz** [comment]
I have just compiled the latest master version and this problem is not present for me. Touchscreen can act as hand tool and stylus as pen in a similar manner as in the original xournal.

**Comment by WPettersson** [comment]
The problem (on my Yoga at least) is that there are 3 ButtonPress events when I touch the screen. The first presumably works fine, but the second button press will call copyCurrentConfig() while the TOOL_HAND is active, so it copies the hand over the pen. The third ButtonPress has event->type != GDK_BUTTON_PRESS, so it doesn't call copyCurrentConfig(). The solution will involve working out why there are 3 button presses, I'm looking into it now.

    INPUT:: ButtonPress (ELAN Touchscreen) (x,y)=(445.91,25.45), button 1, modifier 0, isCore 0 on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:342
    INPUT:: gtk_xournal_button_press_event (h->getToolType() == TOOL_HAND) return true on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:399
    INPUT:: ButtonPress (ELAN Touchscreen) (x,y)=(445.91,25.45), button 1, modifier 0, isCore 0 on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:342
    INPUT:: gtk_xournal_button_press_event (h->getToolType() == TOOL_HAND) return true on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:399
    INPUT:: ButtonPress (ELAN Touchscreen) (x,y)=(445.91,25.45), button 1, modifier 0, isCore 0 on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:342
    INPUT:: gtk_xournal_button_press_event return false (event->type != GDK_BUTTON_PRESS) on /tmp/xournalpp/xournalpp/src/gui/widgets/XournalWidget.cpp:357

**Comment by WPettersson** [comment]
Just checked, xournal (the original) also sees 3 button presses, but doesn't see this issue as it doesn't "copy" the existing tool and then replace it, but rather temporarily uses the hand tool instead of the current tool. My best idea for a "fix" at the moment is to add something like

    if (xournal->view->getCursor()->isMouseDown()) {
        INPUTDBG2("gtk_xournal_button_press_event Received ButtonPress while mouse is down return true")
        return true;
    }

to gtk_xournal_button_press_event, and the appropriate extra function to Cursor. I probably won't go ahead with these changes for a day or so, as I don't have time now, so feel free to add alternate suggestions. I'm also not sure how this will affect other features.


Side note, the 3rd button press is of type GDK_2BUTTON_PRESS i.e. a double-click. No idea how/why, and even if it was, it should still only be preceded by a single GDK_BUTTON_PRESS event, not two. And yes, all 3 events have the exact same event->time.
