### ISSUE TITLE
Hide Toolbar toggle shortcut (like F10 is for Menu), used together with Floating Toolbox

### ISSUE THREAD

**Issue by tjavdar** [xournalpp/xournalpp#2074]
Now that one has floating toolboxes, one should be able to pop/hide the static toolbar with a single shortcut. This allows to use all the screen area while having all the tools in a toolbox at hand. 

The problem at present is that hiding a menu is a long-fetched action:
                         (F10, if menus are hidden)->View->Toolbars->Empty toolbar

Desired solution: Create a shortcut to pop/hide the static toolbar (e.g., Shift-F10, as F10 is for Menu)

Workflow if implemented:
   0. Configure first a  personal floating toolbox by: View->Toolbars->Floating Toolbox->Customize,
       then assign it to a mouse button (File->Preferences->Mouse) or the stylus (File->Prefs->Stylus).
       This is  done once.
   1. At session start: Hide Menu (F10) and Toolbar (Shift-F10).
   2. Start writing/sketching using the whole screen.
   3. Invoke the toolbox to change colors, pens, actions, when needed. Go to 2 -> cycle.

**Comment by duncanawoods** [comment]
I'm interested in this too. I've had a look and created a menu item that toggles the toolbars on f9.

@rolandlo is this desirable?

**Comment by rolandlo** [comment]
@duncanawoods That sounds like a logical choice and desirable to me. There was even a PR for this #461, but somehow was closed without merging. I will take a look at your PRs next week.

**Comment by duncanawoods** [comment]
Oh neat. #461 looks similar but better than mine - it saves the setting and toggles visibility more neatly.

**Comment by rolandlo** [comment]
@duncanawoods If #461 is a better implementation for the toolbar toggle shortcut, then we should ask the author @luco5826 to open his PR again.

**Comment by luco5826** [comment]
Hi @rolandlo , thanks for calling me in! If I recall correctly (jk, I just re-read that PR) the problem was about adding "a lot of code" for a feature that was already there (as OP said, through `View->Toolbars->Empty toolbar`).

It's been a long time since that PR and I did not follow this project consistently enough to be sure that #461 would not break anything. I could reopen that but it was more than one year ago, if @duncanawoods had the time and the patience to recheck it or merge it with its work that would be awesome!

**Comment by duncanawoods** [comment]
Hi @luco5826 ok I will take it on.

**Comment by rolandlo** [comment]
Closed by #2112
