### ISSUE TITLE
Rotation of shapes if not copied

### ISSUE THREAD

**Issue by FinnStutzenstein** [xournalpp/xournalpp#2090]
**Affects versions :**
 - OS: Debian
 - Desktop environment: X11
 - Which version of libgtk do you use: I do not know; It is not given in the about window; `xournalpp --version` errors with
```
** (xournalpp:377189): ERROR **: 09:37:11.507: Unknown option --version
Trace/breakpoint trap
```
 - Version of Xournal++: 1.0.18
 - Installation method: apt repo

**Describe the bug**
Create a rectangle. Select it, e.g. with a lasso selection. Rotate it by 45°. Copy it. paste it -> The copy is not rotated.

**Expected behavior**
The copied rectangle should be rotated.

Thanks!

**Comment by FinnStutzenstein** [comment]
Note: When deselecting the rotated shape, the rotation is "saved" -> when reselecting and copying, it works

**Comment by rolandlo** [comment]
Currently you only see a preview while applying rotation and resizing transformations to selections. That's why copies are not rotated (nor resized). The changes are made permanent after deselecting the selection. I agree that the copy behaviour should be improved in future, but at least you can help yourself by deselecting and reselecting before copying currently.
