### ISSUE TITLE
App Crashes when attempt priting

### ISSUE THREAD

**Issue by IgnatRU** [xournalpp/xournalpp#2158]
**Affects versions :**
Windows Home 10.0.18362 Build 18362
App version 1.0.18, Github commit 535d261d, installed via official release

**Describe the bug**
The App freezes if after opening print dialog you click with mouse of pen on the working area.

**To Reproduce**
1. Start the app
2. press Ctrl-P (or File-> Print)
3. click with pen somewhere on the opened document

**Expected behaviour**
not to freeze =)

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/8153862/89810092-e40a5c80-db12-11ea-8786-bd13d1629675.png)

**Comment by tattsan** [comment]
I run into a similar problem on Linux (xournallpp 1.0.18, built from sources locally). 
After opening the print dialog, resizing the document window causes the app to freeze.
In my case, I am using a tiling WM (xmonad), so when the print dialog is displayed, the document window is automatically resized.  I need to change the WM mode to full screen in order to open the print dialog.

I didn't notice this issue because I usually export documents to PDF before printing.

**Comment by Technius** [comment]
We can prevent the drawing-on-canvas-during-printing issue, PR following soon...

The resize problem is caused by the zoom/scroll infinite loop issue (see #1795).

Both need to be fixed for this issue to be resolved.

**Comment by Technius** [comment]
I can't reproduce this issue with Xournal++ 1.1.2 on Windows 10. Let me know if you're still running into this problem, and I will reopen this issue.
