### ISSUE TITLE
Ubuntu + KDE Hang & System Crash On Large Eraser

### ISSUE THREAD

**Issue by MuTaTeD** [xournalpp/xournalpp#2159]
**Affects versions :**
 - OS: Linux -> Ubuntu + KDE
 - Desktop environment: KDE
 - Version of libgtk: 3.22.30
 - Version of Xournal++: 1.1.0+dev Build: Aug 5 2020 20:48:04
 - Installation method: PPA Official

**Describe the bug**
Switching to Eraser mode with Big Cursor crashes the whole Ubuntu session, forcing to login to the machine again as soon as the cursor enters the document area. All work is lost and no recovery option is given on next restart of the application. 
Does not happen when using Medium or Small size Eraser.
Might be linked to #842 and #1001 which was resolved in #1029

**To Reproduce**
1. Start Xournal++
2. Switch tool to Eraser and make sure Large Eraser is selected 
3. Move Mouse or Stylus to Document Area
4. Whole Linux Crash

**Expected behavior**
Application & Linux desktop does not crash.

**Comment by rolandlo** [comment]
From #1001 I quote @MuTaTeD 
> It seems that KDE/GTK theme has some problem when trying to draw a cursor more than 75 pixels in size. 60 pixels seems to be a better compromise.

If that is true, I can imagine quite well that the large eraser can cause problems, especially if the zoom factor is large (larger than around 208\% for the **very thick** eraser or larger than 312.5\% for the **thick** eraser)

Indeed the pixel size of the eraser cursor is given by the formula.
https://github.com/xournalpp/xournalpp/blob/0313ce563947980598149b33dfbbf3c7acfd4edd/src/gui/XournalppCursor.cpp#L312

and the thickness can be seen from https://github.com/xournalpp/xournalpp/blob/0313ce563947980598149b33dfbbf3c7acfd4edd/src/control/ToolHandler.cpp#L41-L42

@MuTaTeD: Do you remember what zoom factor you used when the crash happened? Do you have a reference for the claim above (with the 75 pixels) or is it just an experimental observation?

I don't quite know how this should be fixed, since having a large eraser is certainly something that can be useful sometimes. It wouldn't be ideal to just reduce the size of the eraser. Maybe it's something that the KDE/GTK team should fix.

**Comment by LittleHuba** [comment]
We would have to limit the cursor size in this case. Best would be to make the limit user configurable so people not using KDE can still have the correctly sized cursor.

**Comment by MuTaTeD** [comment]
The problems seems to have been fixed after KUBUNTU 20.04 LTS fresh install, may be some internal library was causing the problem due to recent update of plasma on KUBUNTU 18.04 LTS

**Comment by bhennion** [comment]
Closing this as the reported said it was fixed.
