### ISSUE TITLE
OneNote .one file format support

### ISSUE THREAD

**Issue by penn5** [xournalpp/xournalpp#2237]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At my school, all work is distributed and takes place via OneNote in Teams. This means using either Windows or the Electron app. I know my way around the MS Graph API, so I can implement syncing of .one files to and from the MS server, but I don't have any experience with xournal++ or the .one format itself, so I have no clue where to even start for that. This may tie into #2045, as I imagine there are many people who would like to use a free alternative to OneNote.

**Describe alternatives you've considered**
I can always just one OneNote on Windows with dual-boot :/

**Additional context**
Not really...

**Comment by rolandlo** [comment]
Supporting the OneNote file format .one (as specified in [these docs](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-one/73d22548-a613-4350-8c23-07d15576be50)) would be a HUGE task. We would have to translate the whole .one format into our model. We would only manage to support a fraction of it without greatly extending our model. I think, getting decent .one file format support is simply out of reach for our team in the near future, as desirable as it may sound.

**Comment by Febbe** [comment]
This is kind of out of scope.
Implementing a support for OneNote Documents is a too large task for us. I suppose one Developer could spend a more than two mounts implementing this. And we are all volunteers spending as much time we can afford beside real life work.
Also, we currently have only two active developers mostly handling the huge amount of bugs and PR's.

But you can feel free to implement that by yourself.
To start you should evaluate, if this is even possible:
1. Check if it is legally possible?
2. Is the file format open documented, or do you have to reassemble it?
3. Search for other implementations optionally open source and list, how they do it.
4. If you found an open source solution which is compatible to GPLv2/v3 go on and use it.
5. Create or copy a OneNoteDocumentLoader, which loads documents (optionally saves)
6. Implement a OneNoteDocumentViewer and InputHandler or just parse the contents into our internal representation. The latter is way easier but ugly and prone to bugs.
7. Fell free to contribute it then to xournal++ :).

I will close this for now, since no one can afford the time to work on this the next time.

**Comment by penn5** [comment]
Sadly I don't know enough C++ to be useful. 

1. IANAL but I'm 99% sure it's legal (they have an open document on [the website](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-one/73d22548-a613-4350-8c23-07d15576be50), and its license says you can do whatever you like unless there is a patent, which I couldn't find on their patent list), so that's not an issue.
2. https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-one/73d22548-a613-4350-8c23-07d15576be50
3. https://github.com/dropbox/onenote-parser, but it's unmaintained and probably broken
4. I'm a noob at C++, I'm better at higher level languages

Could you consider re-opening and adding the `help wanted` tag, so it is visible to would-be contributors?
