### ISSUE TITLE
Stroke smoothing

### ISSUE THREAD

**Issue by TentativeConvert** [xournalpp/xournalpp#2320]
I have a very shaky hand, even more on a tablet than on paper.  Gimp has a nice feature that they call "stroke smoothing", which really helps improve my handwriting on my tablet:

![Gimp-vs-Xournalpp](https://user-images.githubusercontent.com/16051841/96257661-09a45e00-0fbb-11eb-94ca-eb2292121ade.png)

Is there any chance a similar feature could be implemented in Xournal++?

**Comment by rolandlo** [comment]
Generally speaking that's something I consider working on (or at least looking in to) in the future. There are more urgent tasks(like geometry tools and fixing annoying bugs) though, so don't expect anything from my side soon.

**Comment by rolandlo** [comment]
Anyone willing to work on this is advised to take a look [in this opentoonz issue](https://github.com/opentoonz/opentoonz/issues/81), where different implementations are discussed.

**Comment by bhennion** [comment]
I was looking into the existing smoothing algorithms, trying to determine which was more adapted to handwritten words. I applied the various stabilizers Krita has to offer, with various parameters, to a recorded input sequence (using libinput record/replay)
![stabilizers](https://user-images.githubusercontent.com/17818041/101196856-9685a280-3661-11eb-9021-368e6fd3b86c.png)

In the case of my handwritting (and my input hardware), it feels like the first line (without stabilizer) is better. Still, I am sure there are cases, like @TentativeConvert's, where a stabilizer could help.

In order to better document the issue, it would help to have other libinput recordings on which I could test various smoothing techniques. So if other linux users could try and use [libinput record](https://people.freedesktop.org/~whot/libinput-rtd/tools.html#libinput-record), write a line or two and post the resulting yml, it would be great.

**Comment by TentativeConvert** [comment]
Here's my  [libinput record](https://people.freedesktop.org/~whot/libinput-rtd/tools.html#libinput-record)ing of the following two lines:

![This-is-a-test-stroke](https://user-images.githubusercontent.com/16051841/101240210-207b4d00-36ee-11eb-99bc-5cb6df9a7709.png)

(I needed to zip the yml file before uploading it.)

[teststroke.zip](https://github.com/xournalpp/xournalpp/files/5646887/teststroke.zip)

**Comment by bhennion** [comment]
Thanks!

I made some research and experiments about a couple of open source algorithms. This first comment is experimental. There will be a second comment explaining how (I think) those algorithms work.

I tried out various parameters for Gimp and Krita's stabilizers. Here are the results. (Note that some parameters are probably depending on the DPI).
Krita:
![TentativeConvert](https://user-images.githubusercontent.com/17818041/101285018-52baa680-37e3-11eb-81c0-77d70b459555.png)
Gimp:
![TentativeConvertGimp](https://user-images.githubusercontent.com/17818041/101287683-0c207880-37f2-11eb-874c-f172b6d923bb.png)

I would argue that:
- Krita's option called Stabilizer feels better that Krita's option called Weighted. For instance, if you compare "Stabilizer 25/2" with "Weighted 25/0.2", the global feeling is the same but the former seems to preserves the tiny loops (in e's for instance) better.
- Gimp's seems somewhat better in the middle of strokes but the beginning and end of strokes are cut off (see the horizontal bar in T).

All in all, the best smoother might be a mix of Gimp's and Krita's stabilizer.

**Comment by bhennion** [comment]
### How those smoothing algorithms work:
Documentation about those algorithms is sparse. Here is what I could gather:

[1] The opentoonz [issue](https://github.com/opentoonz/opentoonz/issues/81) and [PR](https://github.com/opentoonz/opentoonz/pull/432) mentionned by @rolandlo.
[2] [A post](https://w.atwiki.jp/sigetch_2007/pages/18.html) by the person who implemented Gimp's smoothing algorithm. It's in japanese, I used google translate. I could not find the person's name to give them proper credit here. I apologize for that.
[3] Krita's [documentation](https://docs.krita.org/en/reference_manual/tools/freehand_brush.html), an enlightening [code comment](https://invent.kde.org/graphics/krita/-/blob/master/libs/ui/tool/kis_tool_freehand_helper.cpp#L445) about their Weighted algorithm, and various commit messages about their "Stabilizer" algorithm: [initial commit](https://invent.kde.org/office/calligra/-/commit/58e452c466505aa44c0208bd649d0c8facf0194f), [Delay parameter](https://invent.kde.org/office/calligra/-/commit/98b20b037c237f0bf05685373074e3f211ba8833), [Bug fix](https://invent.kde.org/graphics/krita/-/commit/23cbbf8b73cdd6c24a82ab70c8269df2b69a4ef7).
[4] The sources...

Now, here is how Gimp's and Krita's algorithms work (I'm not sure about OpenToonz').

**Gimp's and Krita's weighed algorithms:** They are variants of the same idea (originally in Gimp): for every stylus event, the position is averaged over a certain amount of previous events, and this averaged position is used to draw the next segment. What varies between the implementations are the meaning of "certain amount", and a weight-function used for averaging. The "certain amount" parameter:
1. Gimp has a user-defined parameter (called Quality) which is exactly the number of events on which we will then average.
2. Krita has a user-defined parameter (called Distance). For each event e, it computes the length l(e) of the path the input device made since that event. It then averages on all events e such that l(e) < Distance.

The second variation is the weight-function used for averaging:
1. Gimp uses a [Gaussian](https://en.wikipedia.org/wiki/Gaussian_function) h whose parameter σ is the user-defined "Force" parameter. When averaging, the weight of a given event e is then h( Σ velicity(f) ) where f runs through all events that occured since e occured. As explained [here](https://w.atwiki.jp/sigetch_2007/pages/18.html), the choice of using velocities is purely empirical.
2. Krita also uses a Gaussian function, whose parameter σ is a third of the user-defined Distance. Each event e is then given the weight h( l(e) ) where l(e) is the length used above.

**Krita's "stabilizer":** This algorithm has two components.
1. The first one has a user-defined parameter called distance (although it is not a distance, [see](https://invent.kde.org/office/calligra/-/commit/58e452c466505aa44c0208bd649d0c8facf0194f#f29b1f1bbfc8aafcff32297f6d73ccf2b6f18ade_488_510)). It queues the last Distance event. Every 15ms (50ms on Windows, see [this](https://invent.kde.org/graphics/krita/-/commit/23cbbf8b73cdd6c24a82ab70c8269df2b69a4ef7)), it computes the average of all the queued events and uses it to paint. Note that most queued events did not occur in the last 15ms (on the various Wacom tablets I have access to, there is an event every 3 to 8 ms, on the touchscreen every 10ms, on my trackpad, that's one every 18ms, on my mouse, one every 9ms).
All in all, this is about the same as the other algorithms (except the weights used for averaging are all the same), with this extra 15/50ms story. I think this timer story is simply a way to limit the refresh rate of the drawing, for performance reasons. I don't think it plays an actual role in stabilizing.
2. The second component is more interesting. It corresponds to the user-defined Delay parameter (which is measured in pixels... so this one is a distance). In the following gif, my brush of 40px wide and the delay is set to 70px (this value of course to big for smoothing handwriting, but it shows how this works):
![delay](https://user-images.githubusercontent.com/17818041/101288431-cade9780-37f6-11eb-9cd8-88f13ff63a1d.gif)
You can see the Delay creates a deadzone (here of radius 70px) around the last painted spot. As long as my cursor does stays in this disk, nothing happens. All I can do is drag the deadzone around by trying to leave it. In effect, this cancels out any oscillation of magnitude smaller than our Delay.

**Comment by rolandlo** [comment]
Here is my libinput recording of these two lines:
![grafik](https://user-images.githubusercontent.com/40485433/101368707-c1613800-38a7-11eb-90f6-11e180047042.png)

[stylus.zip](https://github.com/xournalpp/xournalpp/files/5653495/stylus.zip)

**Comment by bhennion** [comment]
Thanks! Here are some output
Krita: 
![rolandlo-krita](https://user-images.githubusercontent.com/17818041/101388631-87506000-38c0-11eb-8432-dc284c814f5b.gif)
Gimp:
![rolandlo-gimp](https://user-images.githubusercontent.com/17818041/101388653-8cadaa80-38c0-11eb-945e-51a18c2730e6.gif)

There are some tricks to avoid the shrinking at the end of strokes. One big thing I am wondering about is: is there a way to reduce the shrinking of letters where the stylus "turns around" (like the top of a "d" or the bottom of a "p" in @rolandlo' handwriting)? Those points seem to be detected by spline interpolation/approximation algorithms, but I still need to understand how that works.

**Comment by Febbe** [comment]
I also want to throw in my 50ct.
A handwriting software should not shorten strokes, so Kritas 2nd component must be modified in a way, this does not happen. There could be a weight for the second factor which shrinks on lower velocity and high angles. The end of the stroke means 0 velocity and undefined or zero angle.

**Comment by bhennion** [comment]
> A handwriting software should not shorten strokes, so Kritas 2nd component must be modified in a way, this does not happen. 

This is actually also an issue with Gimp's algorithm (try it out with sigma=10 and you'll see it). The simplest solution (implemented for instance in Krita's Weighted algorithm) is to prolong the stroke as a straight line to the ButtonRelease event position. 
For Gimp's algorithm, we could simply pop the oldest event from the queue, average on what's left, draw the point, and keep on until on the queue is empty. This would "average a path" between our last drawn point and the ButtonRelease position.

> There could be a weight for the second factor which shrinks on lower velocity and high angles. The end of the stroke means 0 velocity and undefined or zero angle.

This seems like a great idea! I don't know that it's going to work as I am not sure the velocity measurements are reliable enough for that. Will try it out!

> There may be also a drawing tool helpful in the settings, a user can test the different algorithms.

+1

**Comment by Febbe** [comment]
We could try to use the https://en.wikipedia.org/wiki/Moment_of_inertia to create an algorithm. But this may be slower than others. It definitely has the advantage, that loops and curves aren't collapsed.

**Comment by bhennion** [comment]
> We could try to use the https://en.wikipedia.org/wiki/Moment_of_inertia to create an algorithm. But this may be slower than others. It definitely has the advantage, that loops and curves aren't collapsed.
>
> **Edit:** using a naive impl has the drawback, that the starting point is exact, but not the endpoint. It's like using a explicit [Runge Kutta Method](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods)

What do you mean by "using the moment of inertia"? What I understand is that you want to smoothen not only the position of the point, but also the direction of its velocity vector (so the angular velocity of the tangent or something of the like).

If I understood correctly, then indeed, there would need to be a way of maintaining the curve "close" to the input points. This does not seem so easy.

**Comment by bhennion** [comment]
> > There could be a weight for the second factor which shrinks on lower velocity and high angles. The end of the stroke means 0 velocity and undefined or zero angle.
> 
> This seems like a great idea! I don't know that it's going to work as I am not sure the velocity measurements are reliable enough for that. Will try it out!

@Febbe: After logging all events (see [bufferlogs.log](https://github.com/xournalpp/xournalpp/files/5711543/bufferlogs.log): every array corresponds to one stroke, and the most recent event is always on top), I don't think your idea can work. The velocity is really not a reliable input data.

**Comment by bhennion** [comment]
This should be closed (I tried linking it with the already merged PR, but that trick does not work :-)

**Comment by TentativeConvert** [comment]
Thanks so much for adding this feature!  This is wonderful!

**Comment by bugsbunny88** [comment]
so can someone explain to me in simple terms what setting works for the issue that was described initially (which I have);
in Xournal there are 2 Averaging methods and 2 Preprocessors ; and I have 0 clue what they are doing. Just recommended settings you all use ? what does increasing variance from 0.5 do etc... some documentation on this please

**Comment by bhennion** [comment]
Those parameters are very dependent on your setup (resolution, input device, and so on). Personally, I don't use it.
As a first try, I'd advise you go either just a Gaussian averaging and no preprocessor, or no averaging and a deadzone preprocessor. Play around with the parametersand maybe you'll find your fit.

Also, it seems that in some languages, the popup information bubbles got mistranslated (unsurprisingly, translating those kind of indications is quite a difficult task). Starting the app in english (running `$LANG=C xournalpp`) should give you the original wording, which may help.

**Comment by vladQll** [comment]
> Entonces, ¿alguien puede explicarme en términos simples qué configuración funciona para el problema que se describió inicialmente (que tengo); en Xournal hay 2 métodos de promedio y 2 preprocesadores; y no tengo ni idea de lo que están haciendo. ¿Solo la configuración recomendada que todos usan? ¿Qué hace el radio de inercia de la zona muerta? no aparece ningún menú contextual, etc... alguna documentación sobre esto, por favor

I have also searched for information on what that means, maybe the author of the one that implemented that should explain for newbies like me what it means or what it is for (preprocessor, average method, mediarithmetic, B speed, gaussian weights, dead zone, inertia, etc.), I have suffered a lot trying to find a configuration that gives me the feeling that when I write with the tablet it is as if I were writing with a pen. Gaussian weights, dead zone, inertia etc), I have suffered a lot trying to find a configuration that gives me the feeling that when I write with the tablet is as if I were writing with a pen on paper, and for something this is XOURNAL++ a program to take notes, which makes it difficult because when I write fast (because that's how you take notes with pen and paper), everything is wrong in the aspect of the drawings (shaky lines, sharp endings in letters like R, T, P etc), geometric curves in letters like (P, O, e etc) and why I have not left it yet, because basically it has served me to solve problems at home, calmly writing slowly. by the way to solve problems by writing (not quickly) I have used the following configuration.
![image](https://user-images.githubusercontent.com/28522011/216790805-239ddaf6-3bd0-43a4-8f9a-41680fb6d998.png)
