### ISSUE TITLE
Zooming looses the spot in the document

### ISSUE THREAD

**Issue by pindakaas42** [xournalpp/xournalpp#2411]
**Affects versions :**
 - Xubuntu 18.04 
 - Desktop: Xfce
 - version of libgtk 3.22.30
 - Version of Xournal++: 1.0.19 
 - Installation method: PPA

**Describe the bug**
Changing from 100% zoom to fit page zoom, jumps the view around in the document. 

**To Reproduce**
Steps to reproduce the behaviour:
Open a multi page document. 
Do a zoom to 100%, scroll a few pages. 
Do a zoom to fit. 
The view of the document jumps back to where you started scrolling.  

**Expected behavior**
doing the above should show the same bit of document just in different zoom depths.

**Comment by rolandlo** [comment]
I made a quick test with a 100 pages document (all empty, doesn't matter). If I apply "zoom to 100%" and go to the last page (nr 100) and then do "zoom to fit" (which is 375% on my screen) I land on page 27. Now 27*3.75 is roughly 100.

This is probably the same bug that I experience whenever I attach my monitor to a overhead projector (which changes the resolution of my monitor).

**Comment by neldredge** [comment]
I experience similar behavior when switching in and out of presentation mode, which has the effect of changing the zoom.

This is reminiscent of #2289.  With a little debugging, the issue seems to be that `XournalView::scrollTo` is not called again after `Layout::layoutPages` updates the page's y coordinate with `v->setY`.

**Comment by neldredge** [comment]
As a quick hack, imitating #2346, I was able to make it go away with

```
--- a/src/gui/XournalView.cpp
+++ b/src/gui/XournalView.cpp
@@ -498,6 +498,8 @@ void XournalView::zoomChanged() {
 
 
     if (zoom->isZoomPresentationMode() || zoom->isZoomFitMode()) {
+        layout->recalculate();
+        layout->layoutPages(layout->getMinimalWidth(), layout->getMinimalHeight());
         scrollTo(currentPage);
     } else {
         auto pos = zoom->getScrollPositionAfterZoom();

```

**Comment by rolandlo** [comment]
Thanks a lot for debugging and suggesting the fix @neldredge. I will soon make a PR that solves this problem and others (like #1777)

**Comment by rolandlo** [comment]
Ok, PR #2425 is added. It would help, if you could check it out @neldredge.

**Comment by neldredge** [comment]
#2425 fixes my test case, thanks!  I'll keep using it for the next couple days for further testing.

**Comment by rolandlo** [comment]
@neldredge Is it still working fine?

**Comment by neldredge** [comment]
@rolandlo  Yes, I've had no further issues with page positioning.  Thanks!

**Comment by pindakaas42** [comment]
Tested this and it does improve #2411 but it does not fully solve the problem, the zoom to fit still jumps to the top of the page, way better, but it means if I zoom to the bottom of a page in the 100% zoom and then do a zoom to fit, I then have scroll all the way down the page again.

**Comment by rolandlo** [comment]
@pinkdakaas42 That is what I would expect the current code to do (`scrollToPage(size_t page, double top=0)` with omitted second argument always tries to make the whole page visible; if the page is too large it will show the top of it), but I will see if I can improve this.

**Comment by personalizedrefrigerator** [comment]
I think the issue is related to spacing between pages. This spacing is constant regardless of the current zoom. `ZoomControl`, however, does not take this into account.

`getScrollPositionAfterZoom` needs to take into account `XOURNAL_PADDING_BETWEEN` (declared in `Layout.cpp`) because zooming in causes `XOURNAL_PADDING_BETWEEN` to shrink relative to the size of the pages and zooming out causes `XOURNAL_PADDING_BETWEEN` to grow relative to the size of the pages.

A fix might be to change `ZoomControl::getScrollPositionAfterZoom` and `ZoomControl::setScrollPositionAfterZoom` from
```cpp
void ZoomControl::setScrollPositionAfterZoom(utl::Point<double> scrollPos) {
    this->scrollPosition = (scrollPos + this->zoomWidgetPos) / this->zoom;
}

auto ZoomControl::getScrollPositionAfterZoom() const -> utl::Point<double> {
    if (this->zoomSequenceStart == -1) {
        return {-1, -1};
    }

    return (this->scrollPosition * this->zoom) - this->zoomWidgetPos;
}
``` 

to something **along the lines of** 

```cpp
void ZoomControl::setScrollPositionAfterZoom(utl::Point<double> scrollPos) {
    size_t pageIdx = view->getCurrentPage();

    this->sizeOfStuffThatDoesntZoom = Layout::XOURNAL_PADDING_BETWEEN * pageIdx;
    this->scrollPosition = (scrollPos - this->sizeOfStuffThatDoesntZoom + this->zoomWidgetPos) / this->zoom;
}

auto ZoomControl::getScrollPositionAfterZoom() const -> utl::Point<double> {
    if (this->zoomSequenceStart == -1) {
        return {-1, -1};
    }

    return (this->scrollPosition * this->zoom) - this->zoomWidgetPos + this->sizeOfStuffThatDoesntZoom;
}
``` 

and make `ZoomControl::startZoomSequence` use `ZoomControl::setScrollPositionAfterZoom` to set `this->scrollPosition`.

This should help...

I currently have an open PR and don't want to manage two, so if someone else wants to try this, that would be great!
