### ISSUE TITLE
Preemptive load of pages around the current one

### ISSUE THREAD

**Issue by lciti** [xournalpp/xournalpp#2412]
**Is your feature request related to a problem? Please describe.**
(This is taken from #1477, which describes this problem perfectly)
When annotating a PDF and switching between pages, the entire page is momentarily replaced by a big white screen with "Loading...".

I am using xournalpp to record video lectures where I advance through PDF slides and annotate them with the pen tools. This loading screen issue is particularly distracting because my slides have black background and the "Loading" screen is white.

**Describe the solution you'd like**
I wonder if @michaelcadilhac 's code at the bottom of #1477 ([here](https://github.com/xournalpp/xournalpp/issues/1477#issuecomment-663921991)) could be considered for integration. The code basically preloads a given number of pages pages around the current one(s).

**Comment by Technius** [comment]
I was looking into PDF render performance last weekend and one of the biggest sources of jankiness is page loading during scrolling. I will probably implement some sort of prefetching/loading this weekend.

**Comment by lyro** [comment]
I have exactly the same issue. Actually, it's not that loading the next slide is particularly slow. It is loaded quite fast. The problem is only the "loading" screen shown for a very short time. Thus, the easiest "fix" (for me) would be an option to just disable the loading screen (maybe replace it by some busy-icon somewhere outside the main slide or a busy-cursor or so) and to show the previous slide (or even the new slide with the default background, just not the "loading" text) until the new one is ready.
