### ISSUE TITLE
Eraser via stylus button doesn't reflect eraser size setting.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#2521]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11
 - libgtk: 3.24.24
 - Version of Xournal++: 1.1.0+dev ( bd0b5bb717351c9c2a9462ad6c2e4778db99c9ed )
 - Installation method: build from source

**Describe the bug**
If you use the eraser via stylus button, its eraser size is not the same as the eraser setting, but it is the same as the pen setting.

**To Reproduce**
1. Configure stylus button 1 to invoke eraser. Choose size "don't change".
2. Set pen size 'very thick' and eraser size 'very fine'.
3. If you use eraser via menu or Ctrl-Shift-E, the eraser size is 'very fine'.
4. If you use eraser via stylus button 1, the eraser size is 'very thick'.

**Expected behavior**
At the step4 above, the eraser size should be 'very fine'.

**Comment by tattsan** [comment]
This behavior was introduced with the commit 307d4df815c95a5a6e705517a4d020dbbdc192c7 .

**Comment by Fef0** [comment]
I can confirm, same behavior in Ubuntu 20.04 using X11 with latest build from master.

**Comment by rolandlo** [comment]
I agree, that doesn't look right. What's your take on that @idotobi ?

**Comment by idotobi** [comment]
This is actually how I understood `Size: Don't Change`, namely as use the same size as the currently active tool. So this was intended by the implementation I did. Since I rarely use this feature I didn't notice this was different than before :see_no_evil: 

Still, I see your point. The behaviour should be: `Size: Don't Change` uses the size set for the corresponding tool in the toolbar regardless of the size of the currently active tool.

Is that right @tattsan ?
If so I can implement this easily.

**Comment by idotobi** [comment]
@tattsan : You can try out PR #2530 and check if this is the expected behaviour.

**Comment by tattsan** [comment]
Thank you for your quick PR making. It works fine!

**Comment by tattsan** [comment]
I noticed that a similar issue occurs on 'eraser type'.
Suppose eraser is first set to be 'standard', and you want to change it to 'delete stroke'.

1. Successful operations:
- Start from pen drawing mode.
- Change to eraser mode via toolbar menu.
- Change eraser type to 'delete stroke'
- Change to pen drawing mode via toolbar button.
- Change to eraser mode via stylus button1.
- Then you can use 'delete stroke'  eraser.

2. The operations that fail: 
- Start from pen drawing mode.
- Change eraser type via toolbar button.
- Use eraser via stylus button1.
- Then the eraser is 'standard'. (failure)
- Change to eraser mode via toolbar button.
- You'll find the eraser is 'standard'. (failure)

In the past, the latter operations were successful.

**Comment by rolandlo** [comment]
@tattsan I have observed something like that as well, but now I cannot reproduce what you observed right now. What I observe is simpler than that. I am in eraser mode and the eraser is set to `delete stroke` but the eraser acts like `standard`. It's not always like that, but sometimes. If I switch to `standard`and back to `delete stroke` it works normally again.

**Comment by tattsan** [comment]
Should we separate the eraser type issue from #2521 ?

**Comment by idotobi** [comment]
@tattsan :exploding_head: Amazing that you tried that workflow. This is something I missed in my testing and was even and underlying bug. :pray:  Thanks for trying it out so thorowly.

@rolandlo : I can actually reproduce it and I think the problem you're observing might have the same root cause.
Basically the current implementation was not able to change the Erasertype while another tool was active.

**Comment by idotobi** [comment]
@tattsan : I think it should be part of this. I can still fix it today. I already know where the problem is in the code I just need to find a good way to fix it without changing other behaviour :innocent:

**Comment by idotobi** [comment]
@tattsan : The issue is fixed. If you have time it'd be great if you can check it out in the linked PR :)

**Comment by tattsan** [comment]
I've tried the PR. It works fine! I'll continue testing. Thank you so much.

**Comment by idotobi** [comment]
Thank you :pray:
