### ISSUE TITLE
[Possible regression] Does not show an option to quickly choose a pencil of desired color when using eraser

### ISSUE THREAD

**Issue by apandada1** [xournalpp/xournalpp#2527]
**Affects versions :**
 - OS: Linux Mint 20
 - (Linux only) Desktop environment: X11, Cinnamon Desktop
 - Which version of libgtk do you use: 3.24.20
 - Version of Xournal++: 1.1.0+dev
 - Installation method: [Xournalpp Master PPA](https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master)

**Describe the bug**
Until version 1.0.19, one could click on the color buttons to quickly switch to a pencil of desired color when using the eraser. In version `1.1.0+dev`, these color buttons are greyed out. 

**To Reproduce**
1. Click on the eraser.
2. Color buttons are greyed out.

**Expected behavior**
The color buttons should not be greyed out, and clicking on them should switch to a pencil of that color.

**Screenshots of Problem**
![Screenshot from 2020-12-11 12-58-51](https://user-images.githubusercontent.com/3063132/101876117-ea3c4280-3bb1-11eb-9bdd-1c9cd81feedd.png)

This issue was absent in version 1.0.19 (from the other PPA).
![Screenshot from 2020-12-11 12-55-34](https://user-images.githubusercontent.com/3063132/101876131-ef00f680-3bb1-11eb-97a7-fc4831cc47bf.png)

**Comment by Technius** [comment]
This behavior change is intentional, see #2004. I do see some utility in having a quick switch option, but if you're using a stylus, you probably already have eraser bound to a stylus button. And mouse has keyboard shortcuts.

**Comment by apandada1** [comment]
@Technius I have configured to switch to the eraser when I click the middle mouse button. When I click the middle mouse button, I see these in `1.1.0+dev`, but they are not clickable (because they go away when I release the middle button). 
![Screenshot from 2020-12-12 15-17-12](https://user-images.githubusercontent.com/3063132/101980751-c3ebd500-3c8d-11eb-9b7f-bff551424b31.png)
Is this feature now only available when a stylus is present? (I don't have one, so I cannot check)

**Comment by idotobi** [comment]
@apandada1 : I think I understand the issue now. 

Since you don't have stylus I think the gif in #2004 might be misleading.
How the feature works for the Stylus:
 - user uses eraser button
    - eraser is active
 - user goes to toolbar and clicks on color
    - eraser still active but the pen changed the colour in the background
 - user goes back to erase things
    - eraser still active
 - user releases eraser button
    - pen is active but with new colour

Thus the quick change also doesn't work for the stylus.
I'm afraid that #2004 broke your usecase then :see_no_evil:. Sorry for that!

Still I think it's better to not overload the Colour selection with the functionality to also change the tool. In your case when using the mouse you would just need to release the mouse to select the colour for the "toolbar selected tool". Of course if the toolbar selected tool was not a pen previously this is not exactly the same as you would still need to additionally select the pen first. Maybe putting the Pen next to the colours at least reduces this by some degree.
![image](https://user-images.githubusercontent.com/16611056/101982353-95610080-3c73-11eb-8434-1b29eb9ee92c.png)
