### ISSUE TITLE
Background pdf could not be found: Mention full path

### ISSUE THREAD

**Issue by anishmittal2020** [xournalpp/xournalpp#2646]
**Is your feature request related to a problem? Please describe.**
When the background pdf could not be found, please mention full path of the pdf that was connected with the xopp file.

**Describe the solution you'd like**
Mention full path of the pdf that was connected with the xopp file.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by nekohayo** [comment]
This bites me daily:

![Screenshot from 2021-02-08 09-56-46](https://user-images.githubusercontent.com/479401/107236772-0151b200-69f4-11eb-99a8-a3bd69620324.png)

...that dialog's text is not very helpful.

I have hundreds of PDFs in the folders where I deal with unfillable forms, I can't go guessing which one was used for a particular form. Xournal++'s ui should at _least_ tell me the **file name**; the path is not absolutely necessary to me, but it's nice to have.

So the message could say:

```
The background file, <b>{%human_readable_file_name}</b>, was not found. It might have been moved, renamed, or deleted.\n
It was last seen at {%previous_path}\n
Please provide a replacement for it.
```

And then, be extra-nice to the user in terms of being smart: when clicking "Select another PDF" (which should be labelled "Select **replacement** PDF" in my humble opinion), if the path still exists, tell the GtkFileChooser to view that previous folder instead of whatever folder I'm currently in; otherwise show the folder I'm currently in. It could be that the file was just renamed or moved into a subfolder.

**Comment by legendofa** [comment]
An easy solution would be to just embed all pdfs. This problem is avoidable.

https://github.com/xournalpp/xournalpp/issues/2574
This issue proposes that, have not found the mentioned duplicate.
