### ISSUE TITLE
How to uninstall on windows

### ISSUE THREAD

**Issue by cuppajoeman** [xournalpp/xournalpp#2666]
Hi I downloaded xournalpp on windows a while ago, what is the usual procedure to uninstall the program (and all related files?), I didn't see the program in the "uninstall a program" menu, so how should I uninstall?

**Comment by rolandlo** [comment]
There is an Uninstall.exe in your Xournal++ folder (C:\Windows\Program Files\Xournal++).

**Comment by cuppajoeman** [comment]
Thanks @rolandlo, will there be anything extra I have to delete to get rid of any configuration? And if this isn't documented anywhere I can add this so people will know how to uninstall.

**Comment by Technius** [comment]
I checked the uninstaller code yesterday and found that it leaves behind some "garbage" registry keys.

I'm currently working on updating #2606 so that
* the uninstaller is listed in `Add and Remove Programs`
* the uninstaller will clean up its registry keys (including the old versions)
* Xournal++ will be properly registered in the `Open With` menus

If you're interested in cleaning up the registry keys manually, you'll need to delete the following registry keys after running the uninstaller:
* `HKEY_CLASSES_ROOT\Software\Classes\Xournal++ template file`
* same as above but `Xournal++ file` and `Xournal file`
* `HKEY_CURRENT_USER\Software\Xournalpp`

**Comment by Technius** [comment]
I also noticed that the current uninstaller will leave behind a start menu folder, which you will want to delete to ensure a clean uninstallation!

**Comment by Juglugs** [comment]
Whenever I run `winget upgrade --all` it comes back! I've tried uninstalling it with winget and in the Apps section of settings...

Persistent little bugger...
