### ISSUE TITLE
make returns Error 

### ISSUE THREAD

**Issue by egekorkan** [xournalpp/xournalpp#269]
I am running Archlinux 4.18.6-arch1-1-ARCH and getting the following error when trying to build xournallpp:

```
make[2]: *** [src/CMakeFiles/xournalpp-core.dir/build.make:89: src/CMakeFiles/xournalpp-core.dir/control/Control.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: src/CMakeFiles/xournalpp-core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

These are the last log messages. Above, I can see:

```
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected unqualified-id before ‘const’
     static bool likely(const string_type& str)
                 ^~~~~~
/usr/include/boost/date_time/special_values_parser.hpp:105:17: error: expected ‘)’ before ‘const’
/usr/include/boost/date_time/special_values_parser.hpp:105:17: note: to match this ‘(’
     static bool likely(const string_type& str)
                 ^~~~~~
/usr/include/boost/date_time/time_parsing.hpp: In function ‘time_type boost::date_time::parse_iso_time(const string&, char)’:
/usr/include/boost/date_time/time_parsing.hpp:312:19: error: expected unqualified-id before ‘(’ token
     if (svp_type::likely(s)) {

```
There are also multiple warnings saying that `dynamic exception specifications are deprecated in C++11`.

**Comment by egekorkan** [comment]
First I have tried building through AUR package and then manually. These error messages are from the manual build.

**Comment by andreasb242** [comment]
I hope this is fixed after GTK3 merge and Lib updates, please check, and if not, reopen bug or create a new one.

**Comment by HOYUN-HEO** [comment]
The same compilation error occurred while using boost 1.70 and pf_ring 7.4.

Could you help me if I have a solution?

**Comment by lingfors** [comment]
boost::date_time defines a function "likely". This is prone to colliding with a macro "likely", used for "helping" the compiler with branch prediction.

Some solutions:

1) Remove or rename the macro (and push the change upstream).
2) Remove or rename the boost::date_time function (and push the change upstream).
3) Order your includes so that boost::date_time is always included before whatever defines the macro.

**Comment by Technius** [comment]
We removed boost over a year ago, so this is not an issue.

**Comment by LittleHuba** [comment]
@Febbe we should think about this for the filesystem library...

**Comment by Febbe** [comment]
@LittleHuba if we only use boost::filesystem, it shouldn't collide with the macro/function if the macro still exists in our codebase. I think the above question is independent to xournalpp. And in the future it will collide with c++20, because the boost day time lib will be part of the STL. But I ll test it and if its a problem, I would rather fix it, instead to refrain from using incompatible libs. Macros are evil either way.

**Comment by LittleHuba** [comment]
Yeah fixing it is definitely the best approach. It is just that we shouldn't forget about this incompatibility.

**Comment by sai-kumar-paupe** [comment]
Is the issue still existing? I have been seeing the same issue while upgrading to 1.72.0 boost library version.

/Boost/boost_1_72_0/boost/date_time/special_values_parser.hpp:105:17: error: expected identifier before '(' token
     static bool likely(const string_type& str)
                 ^~~~~~

**Comment by Febbe** [comment]
@sai-kumar-paupe currently we don't use boost, so I don't know how you encountered this. Can you be more specific what you did. 
Also you should open a new bug report instead of using a dead thread.
