### ISSUE TITLE
Enable mirroring by either a button or transformation

### ISSUE THREAD

**Issue by coldspark29** [xournalpp/xournalpp#2718]
There is no possibility of creating a mirror image automatically. Here I am trying to transform the drawing to flip it around to get the mirror image for the discrete convolution, but I have to redraw it. I think there should be a button for this and the transformation should also support this.

![mirror](https://user-images.githubusercontent.com/19779511/106100172-30d30580-613c-11eb-86b6-aa3b59c514bf.gif)

**Comment by redweasel** [comment]
yes please! This is my most missed feature by far! (could potentially be a simple fix and a good first issue to tackle)

**Comment by rolandlo** [comment]
It is not so trivial, since there are a lot of calculations made for snapping and there are rotation, stretching, translation and undo actions involved, and previews are displayed, which all must work. I see an approach to simplify the currently used code, which would make it easier. But it is definitively not on the difficulty level of a good first issue. In Xournal the approach is much simpler. There is no rotation and no previews while transforming the contents are displayed.

**Comment by redweasel** [comment]
Ok I'm already looking into it, and came across some very strange code (gigantic if statements in a place where there really should not be a branch). I am already trying to simplify it down. I have worked on similar code in blender already so I hope to make a good contribution here too.

**Comment by coldspark29** [comment]
Nice work!
