### ISSUE TITLE
Gaomon touchpen makes Xournal++ close

### ISSUE THREAD

**Issue by marinellita64** [xournalpp/xournalpp#3078]
A few weeks ago I was able to write on Xournal++ with my Gaomon touchpen without any problem. But since I updated my OS (Windows10) and now it doen't work. Actually when I try to write on Xournal it waits a few seconds and suddently Xournal is shut down.
With the computer mouse however, I can write without problem on Xournal. It looks like it's especially the pen.
I tried to uninstall Xournal, the Gaomon driver, restart my computer, to change the pen parameters (like use Windows Ink or not), but I can't fix the bug.
With this pen, I can write on Krita, Word, Edge or any whiteboard. It's only Xournal++ which doesn't work. 
Thanks for your help.
Best regards
Marine

**Comment by rolandlo** [comment]
Which version of Xournal++ do you run? Have you tried changing some related settings in the input system panel of menu `Edit > Preferences`?

**Comment by marinellita64** [comment]
I tried both version 20 and 19. Until now, I did'nt try to change settings in the input system, but I will.

**Comment by rolandlo** [comment]
Could you please try [version 1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly)? That's the most recent one and is most likely to succeed.

**Comment by marinellita64** [comment]
![bug_install_xournal](https://user-images.githubusercontent.com/52403217/116261610-1975d980-a778-11eb-9f90-ee5e7539a106.png)
Sorry I have a bug when installing this latest version (with some dll, see attached file)

**Comment by marinellita64** [comment]
I just tried it but unfortunately no real improvment. This time it doesn't close immediatly, I manage do draw two or three dots (no line drawing, even with the mouse)

**Comment by marinellita64** [comment]
![bug_xournal](https://user-images.githubusercontent.com/52403217/116265530-7cb53b00-a77b-11eb-8dae-99acdf49a237.png)
With version 19, I checked in Edit / Input System and th pen seems not to be detected.

**Comment by mgavin** [comment]
It looks like you're using the latest version of the Gaomon tablet software. If you downgrade to the version previous to that, you may have better results. I've had to downgrade because of complications with trying to update to the latest software. For instance, I'm running the Gaomon_Windows_Driver_v14.8.77.1020 because the Gaomon_Windows_Driver_16.0.0.20 that came with the software in the screenshot you provided didn't work... and I'll probably be using the downgraded driver until a magical fix sometime later. (IDK what tablet you're using, but I just used numbers from the one I have (PD2200) and got the driver numbers from the support section on their website)

**Comment by marinellita64** [comment]
Oh yeeeeess !! I did exactly what you advised me to do (downloading  v14.8.77.1020) and now it perfectly WORKS ! Thanks a lot, I feel so relieved and grateful now that my problem is solved !! Thanks to every one who took time to think of my concern.
Regards
Marine
