### ISSUE TITLE
Cursor size doesn't update after using "ACTION_SIZE_..."

### ISSUE THREAD

**Issue by jdujava** [xournalpp/xournalpp#3090]
**Affects versions :**
 - OS: Linux (Arch)
 - Desktop environment: X11
 - Xournal++ 1.1.0+dev
 - libgtk: 3.24.29
 - Installation method: AUR - xournalpp-git

**Describe the bug**
I am using a plugin to change sizes of tools, but the size of cursor indicator
changes only after changing the color or after switching to another tool and
back.

**To Reproduce**
Create a simple plugin, bind following actions to any key:
`
app.uiAction({["action"] = "ACTION_SIZE_THICK"})
`
or
`
app.uiAction({["action"] = "ACTION_TOOL_PEN_SIZE_THICK"})
`
Pen size changes, but the cursor indicator stays the same.

**Expected behavior**
Cursor indicator changes automatically with change of the pen size.

**Additional context**
After quick inspection of `Control.cpp` code, it seems to me that calling
`
getCursor()->updateCursor();
`
or
`
toolSizeChanged();
`
at appropriate places could fix the problem (only a guess).

**Comment by rolandlo** [comment]
This also happens when using the menubar or the toolbar to change the pen size.

**Comment by rolandlo** [comment]
The bug seems to happen here:
https://github.com/xournalpp/xournalpp/blob/2d8201f4cebce3d5cc460185c185b6e5449aeb40/src/gui/XournalppCursor.cpp#L419-L424

Xournal++ thinks it doesn't need to change the cursor, because the `size` variable it uses is not the actual cursor Size (but either 3 or 5 depending on whether the pen or the highlighter is used)

https://github.com/xournalpp/xournalpp/blob/2d8201f4cebce3d5cc460185c185b6e5449aeb40/src/gui/XournalppCursor.cpp#L393-L393

https://github.com/xournalpp/xournalpp/blob/2d8201f4cebce3d5cc460185c185b6e5449aeb40/src/gui/XournalppCursor.cpp#L406-L406

**Comment by VanniPrashar** [comment]
Can I fix this please
