### ISSUE TITLE
Fulll pdf path is saved regardless of mode.

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#3189]
**Affects versions :**
 - OS: Linux (doesn't matter)
 - X11 (doesn't matter)
 - Which version of libgtk do you use: 3.24.25 (doesn't matter)
 - Version of Xournal++: 1.1.0+dev
 -  PPA (doesn't matter)
 
**Describe the bug**
The pdf background filename is saved in absolute mode, regardless of the mode it has been originally saved with previously. So if a document is created in attach mode, saved, reopened and saved again, the path to the pdf will now be in absolute mode.

**To Reproduce**
1. Open a pdf `test.pdf` with "Annotate pdf" and check the "attach to journal" checkbox on the bottom left of the file dialog
2. Edit the pdf and save the xopp-file `test.xopp`. Observe that a `test.xopp.bg.pdf` file is created in the same directory and the (ungzipped) xopp-file contains a tag 
```xml
<background type="pdf" domain="attach" filename="bg.pdf" pageno="1ll"/>
``` 
as expected
3. Open the xopp-file from the file manager or with "Open File"
4. Edit and save again
5. Observe that the (unzipped) xopp-file now contains a tag
```xml
<background type="pdf" domain="absolute" filename="full/path/to/pdf/test.xopp.bg.pdf" pageno="1ll"/>
``` 
instead of the attach mode

**Expected behavior**
A document that has been created in attach mode should remain in attach mode when reopend and saved again

**Additional context**
There is a related issue #2736, that relative pdf background filenames can be opened, but when they are saved, the relative path gets replaced by the full absolute path.

**Comment by ashwincreates** [comment]
Hey, how do i see the unzipped version ?

**Comment by rolandlo** [comment]
Just rename the `.xopp`-filename ending to `.gz`, then `gunzip` it, then open it up in a text editor. After making your changes, `gzip` it again and rename the filename ending again from `.gz`to `.xopp`. Make sure you make a backup copy of the `xopp`-file if experimenting with it the first time.
By the way, I have a little python script which gives me a dropdown menu entry in the file manager (nautilus) with with I can open and edit a `.xopp`-file in `gedit` in human-readable format. It does all of the above automatically. If anyone likes, I can share it (without any warranty).

**Comment by Rmano** [comment]
If you use `vim`, adding this to your `.vimrc`:

```vim
" edit xournal files (see https://vi.stackexchange.com/a/10390/854)
augroup gzip_local2
    autocmd!
    autocmd BufReadPre,FileReadPre     *.xopp setlocal bin
    autocmd BufReadPost,FileReadPost   *.xopp call gzip#read("gzip -dn -S .xopp")
    autocmd BufWritePost,FileWritePost *.xopp call gzip#write("gzip -S .xopp")
    autocmd FileAppendPre              *.xopp call gzip#appre("gzip -dn -S .xopp")
    autocmd FileAppendPost             *.xopp call gzip#write("gzip -S .xopp")
augroup END
```
...will let you directly edit `.xopp` files

**Comment by ashwincreates** [comment]
Thanks, i duplicated the bug, So like which part of the codebase should i start exploring to find more abt the bug, will i get it in src/pdf?

**Comment by rolandlo** [comment]
@ashwincreates You will have to look at the `LoadHandler.cpp` and the `SaveHandler.cpp` code files and possibly at the `Control.cpp` and `Document.cpp` code files. Search for the string "attach" and the boolean variable `attachToDocument` to get started.

**Comment by Vonpiper** [comment]
Thank you @gurrgur your code worked great for me!

It was not obvious at first, but I also had to rename the *.pdf files to *.xopp.bg.pdf.

**Comment by Zocker1999NET** [comment]
I modified the script of @gurrgur to use the [pathlib](https://docs.python.org/3/library/pathlib.html) instead of [os](https://docs.python.org/3/library/os.html) package and let it change the PDF path to `myfile.pdf` if the xopp file was called `myfile.xopp`, maybe this version is more useful to others:
```python
#!/usr/bin/env python3

import gzip
from pathlib import Path
import xml.etree.ElementTree as ET


xopp_files = [fname for fname in Path().iterdir() if fname.is_file() and fname.suffix == ".xopp"]

print(f"Attaching the pdf background for {len(xopp_files)} .xopp file{'' if len(xopp_files) == 1 else 's'}.")
for fname in xopp_files:
    fbackup = Path(f"{fname}.bak")
    fname.rename(fbackup)
    with gzip.open(fbackup, "r") as f:
        root = ET.fromstringlist([l.decode("utf-8") for l in f.readlines()])

    for bg in root.iter("background"):
        if "domain" in bg.attrib.keys() and "filename" in bg.attrib.keys():
            bg.attrib["domain"] = "absolute"
            # configure path where pdf can be found <-- HERE
            bg.attrib["filename"] = fname.with_suffix(".pdf").name
            bg.set('updated', 'yes')

    with gzip.open(fname, "w") as f:
        f.writelines(ET.tostringlist(root))
    fbackup.unlink()
print("Done.")
```

**Comment by Joheyy** [comment]
**Where is the issue at:**
I don't know if it's the only thing at fault but I'm pretty sure [this line](https://github.com/xournalpp/xournalpp/blob/3a83def61a8971f66cdcda973af372410f975c03/src/core/control/xojfile/LoadHandler.cpp#L477) is at least partly at fault. 

**What's wrong:**
The value of `attachToDocument`, which is always `false` at this point, is passed to `readPdf`. This is exactly the opposite of what we want because the value should always be `true` since we are reading a file which has the mode "attached" here.

**Why is this causing the error:**
When saving, the value that is passed to `readPdf` is used to determine the mode in which the path is saved.

**How to fix it:**
Replace `attachToDocument` with `true`.

I might do a PR myself some time but I need to set everything up and familiarize myself with this project so it might take some time. I'd be glad if someone who has already worked with this project could test it.

**Comment by Technius** [comment]
Just to clarify, does this bug affect version 1.1.1?

**Comment by rolandlo** [comment]
> Just to clarify, does this bug affect version 1.1.1?

Yes, it does.
