### ISSUE TITLE
1.1.0 Release: Update Snap and Flathub packages

### ISSUE THREAD

**Issue by personalizedrefrigerator** [xournalpp/xournalpp#3245]
## Summary
 * The Snap and Flathub repos for `xournal++` need to be updated to `v1.1.0`.

## Snap
@kenvandine Can you handle updating the `snap` repository? I'm opening this issue here because issues are disabled for https://github.com/kenvandine/xournalpp.

## Flathub
https://github.com/flathub/com.github.xournalpp.xournalpp/blob/8ed3d247e2d2556ec020dfe4f3b74fae13dd47c0/com.github.xournalpp.xournalpp.yaml#L112-L113 probably need to be updated.

Thank you to everyone for your work on this version of `Xournal++`!

**Comment by rolandlo** [comment]
@personalizedrefrigerator I'm working on the flathub repo.

**Comment by rolandlo** [comment]
Test builds for the flatpak are available, see https://flathub.org/builds/#/builders/32/builds/53769
They can be installed via 
```
flatpak install https://dl.flathub.org/build-repo/51715/com.github.xournalpp.xournalpp.flatpakref
```

**Comment by rolandlo** [comment]
@apandada1 Can you please update the stable PPA as well?

**Comment by kenvandine** [comment]
I'll update the snap

**Comment by apandada1** [comment]
@rolandlo  I updated the stable PPA for Ubuntu 20.04 and above. It [does not build](https://github.com/xournalpp/xournalpp/issues/1013#issuecomment-695823720) in 18.04, where users need to manually download the .deb file, or use flatpak/snap.

**Comment by rolandlo** [comment]
@kenvandine As I can see there is already Xournal++ 1.1.0 in the `candidate` and `edge` channels. Thanks a lot! 
Testing the snap I noticed that localizations are not working out of the box. Xournal++ assumes a wrong `locale` directory (namely `usr/share/locale`, which cannot be accessed by the snap package. However we have the `TEXTDOMAINDIR` environment variable to solve the problem:

``
`export TEXTDOMAINDIR=/snap/xournalpp/current/usr/share/locale
``` 
This makes Xournal++ find the right `locale` directory, after which the language can be set in the `Edit > Preferences` menu (Language panel) as usual. I have noticed, however, that Gtk stock menu entries (like `gtk_help` or `gtk_about` that are used in the Help menu) are not translated. I'm not sure why that is happening. Those strings are correctly localized in the AppImage, which uses the `TEXTDOMAINDIR` environment variable at startup as well and doesn't have more/other localization files packed.

**Comment by kenvandine** [comment]
> @kenvandine As I can see there is already Xournal++ 1.1.0 in the `candidate` and `edge` channels. Thanks a lot!
> Testing the snap I noticed that localizations are not working out of the box. Xournal++ assumes a wrong `locale` directory (namely `usr/share/locale`, which cannot be accessed by the snap package. However we have the `TEXTDOMAINDIR` environment variable to solve the problem:
> 
> ```
> export TEXTDOMAINDIR=/snap/xournalpp/current/usr/share/locale
> ```
> 
> This makes Xournal++ find the right `locale` directory, after which the language can be set in the `Edit > Preferences` menu (Language panel) as usual. I have noticed, however, that Gtk stock menu entries (like `gtk_help` or `gtk_about` that are used in the Help menu) are not translated. I'm not sure why that is happening. Those strings are correctly localized in the AppImage, which uses the `TEXTDOMAINDIR` environment variable at startup as well and doesn't have more/other localization files packed.

Thanks, I just pushed fixes for localization which are building now and will be in the snap store soon. It still needs some more thorough testing before promoting, but we're getting closer.

**Comment by rolandlo** [comment]
> Thanks, I just pushed fixes for localization which are building now and will be in the snap store soon. It still needs some more thorough testing before promoting, but we're getting closer.

1. As I can see, the `TEXTDOMAINDIR` variable is now correctly set and the snap package uses the System Default language, or, if the user chooses in `Edit > Preferences`, one of the other languages. The strings coming from gtk are not localized yet. Did you try to fix that? For MS Windows and MacOS we copied the `gtk30.mo` (and `gdk-pixbuf.mo`, `glib20.mo`, `gtk30-properties.mo` in case of MS Windows) to the same `locale` directory where the `xournalpp.mo` files are. In the AppImage we didn't do that, but apparently they are read from the user system (I don't understand how), see

https://github.com/rolandlo/xournalpp/blob/9d1277dee22bb095c2db047bb04f89cc837aee3c/windows-setup/package.sh#L38-L43


2. The LaTeX tool doesn't work yet, although texlive seems to be bundled correctly. When I press the "Test the configuration" button in the Xournal++ preferences, I get the following error message:
![grafik](https://user-images.githubusercontent.com/40485433/126488428-4a2d68cc-3231-461d-856c-dddbeffad17d.png)

I looked for the `tex` folder and found it in `/tmp/snap.xournalpp/tmp/xournalpp-80415/`. It only contained the `tex.tex` file that should be processed by `pdflatex`. There was no `tex.log` or other files generated. The `tex.tex` files compiled correctly in my usual LaTeX editor (with TeXLive 2020/Debian). When trying to compile with the bundled `pdflatex` (TeX Live 2019/Debian), after entering the `tex` folder as `root`, I first got the message

```
(Fatal format file error; I'm stymied)
```

After running `/snap/xournalpp/current/usr/bin/fmtutil-sys --all` it compiled as well with the bundled TeX Live. However from the Xournal++ snap package I still got the same error afterwards.


3. Another question: `Lua plugins` work fine in the Xournal++ snap package. It would be nice to have `lua-lgi` bundled, so that plugins with GUI can run as well. I don't see how a user can do that when the snap package has already been installed. So would it be possible to bundle `lua-lgi`?

Other than the problems above I didn't find any issues when testing the snap package. Audio recording worked fine, loading/saving/exporting to PDF worked fine as well and so did drawing with a stylus.

4. A last question: When promoting the 1.1.0 version to the stable channel, would it be possible to update the icon, description and the screenshots? We have a [appstream metainfo file](https://github.com/xournalpp/xournalpp/blob/master/desktop/com.github.xournalpp.xournalpp.appdata.xml) that contains all those infos. It is also used [on Flathub](https://flathub.org/apps/details/com.github.xournalpp.xournalpp). Of course it can be different, but an update would be appreciated.

**Comment by rolandlo** [comment]
It looks like the bundled LaTeX installation tries to access the file `/etc/texmf/web2c/texmf.cnf` which it is denied. Here is the output of  `sudo journalctl --since=18:23 | grep audit`

```
Jul 21 18:23:50 roland-ThinkPad-X1-Yoga-3rd audit[124343]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj==snap.xournalpp.xournalpp (enforce) pid=124343 comm="xournalpp" exe="/snap/xournalpp/52/usr/bin/xournalpp" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fb75d4d889d code=0x50000
Jul 21 18:23:50 roland-ThinkPad-X1-Yoga-3rd kernel: audit: type=1326 audit(1626884630.796:633): auid=1000 uid=1000 gid=1000 ses=3 subj==snap.xournalpp.xournalpp (enforce) pid=124343 comm="xournalpp" exe="/snap/xournalpp/52/usr/bin/xournalpp" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fb75d4d889d code=0x50000
Jul 21 18:23:50 roland-ThinkPad-X1-Yoga-3rd audit[124343]: AVC apparmor="DENIED" operation="open" profile="snap.xournalpp.xournalpp" name="/etc/alsa/conf.d/" pid=124343 comm="xournalpp" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jul 21 18:23:50 roland-ThinkPad-X1-Yoga-3rd kernel: audit: type=1400 audit(1626884630.936:634): apparmor="DENIED" operation="open" profile="snap.xournalpp.xournalpp" name="/etc/alsa/conf.d/" pid=124343 comm="xournalpp" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jul 21 18:23:53 roland-ThinkPad-X1-Yoga-3rd audit[124426]: AVC apparmor="DENIED" operation="open" profile="snap.xournalpp.xournalpp" name="/etc/texmf/web2c/texmf.cnf" pid=124426 comm="pdflatex" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Jul 21 18:23:53 roland-ThinkPad-X1-Yoga-3rd kernel: audit: type=1400 audit(1626884633.924:635): apparmor="DENIED" operation="open" profile="snap.xournalpp.xournalpp" name="/etc/texmf/web2c/texmf.cnf" pid=124426 comm="pdflatex" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

```

**Comment by rolandlo** [comment]
>     1. Another question: `Lua plugins` work fine in the Xournal++ snap package. It would be nice to have `lua-lgi` bundled, so that plugins with GUI can run as well. I don't see how a user can do that when the snap package has already been installed. So would it be possible to bundle `lua-lgi`?

Thank for bundling `lua-lgi`. Looking at the `package.path` and `package.cpath` variables (via a plugin that outputs these variables) it appears that some version of `Lua 5.3`  with default paths 
```
package.path = /usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;./?.lua;./?/init.lua`
package.cpath = /usr/local/lib/lua/5.3/?.so;/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so
```
is running, which do not help when requiring `lua-lgi` in the snap package.

I made the MigrateFontSizes plugin work in the snap package by patching the `package.path` and `package.cpath` in `MigrateFontSizes/main.lua` like this:

```
  package.path = "/snap/xournalpp/current/usr/share/lua/5.3/?.lua;" .. package.path
  print("package.path is: ", package.path)
  package.cpath = "/snap/xournalpp/current/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;" .. package.cpath 
  print("package.cpath is ", package.cpath)
```
To patch the file I had to store it somewhere else and mount it
```
sudo mount -o ro,bind /tmp/main.lua /snap/xournalpp/current/usr/share/xournalpp/plugins/MigrateFontSizes/main.lua
```

Then at startup of the Xournal++ snap, I get the following output
```
** Message: 08:34:32.071: Plugin "LayerActions" UI initialized
package.path is: 	/snap/xournalpp/current/usr/share/lua/5.3/?.lua;/snap/xournalpp/53/usr/share/xournalpp/plugins/MigrateFontSizes/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;./?.lua;./?/init.lua
package.cpath is 	/snap/xournalpp/current/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/local/lib/lua/5.3/?.so;/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so
```

and the plugin with its GUI runs just fine.

So is there a way to make the running Lua version have the proper `package.path` and `package.cpath` without patching the plugins?

**Comment by rolandlo** [comment]
The snap package and flatpak have been updated a while ago, so I am closing the issue.
