### ISSUE TITLE
Request save as: Exercise.5.12  --saves--> Exercise.xopp (silently ignoring all after the first dot)

### ISSUE THREAD

**Issue by tjavdar** [xournalpp/xournalpp#3330]
**Affects versions :**
 - OS: Archlinux
 - (Linux only) Desktop environment: X11 under i3
 - Which version of libgtk: 3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official Arch repo

**Describe the bug**
Request for saving from File->Save[ as] (or Ctrl-S/Ctrl-U) under a

filename.with.dots

silently ignores everything after the first dot and saves under

filename.xopp.

**To Reproduce**
1. Start xournalpp with an empty canvas and scribble something
2. Choose menu File->Save and write in the filename field:  Exercise.5.12
3. Click save and exit xournalpp
4. Check what actually have been saved (e.g., ls) gives: Exercise.xopp

**Expected behavior**
Filenames with dots should be saved w/o truncation at the first dot.

**Comment by suisseWalter** [comment]
I tried to reproduce this on my system. (ubuntu20.04-i3)
and I can only get it to strip the last set of characters after a . so abcd.a.b.c.d is saved as abcd.a.b.c
I think it tries to strip away any old file endings(.pdf) but is a bit aggressive with it. 
also looking at old files (1.5years old) they all end in .pdf.xopp so I think back then it didn't even strip the .pdf. 
is there a limit of how many it strips away for you? (will the file a.b.c.d.e.f.g be saved as a)?

**Comment by tjavdar** [comment]
@suisseWalter: You are right, it strips only after the last dot, for me a request to save

foo.1.2.3.4 --is saved as--> foo.1.2.3.xopp

omitting the "4". And you are probably right that's done because of annotations, so that annotation of

foo.pdf  --is saved under--> foo.xopp

Still, I don't think this should be done silently. Moreover it is easy to check and skip only if the extension matches '.pdf'.

Anyway, your post suggests for a workaround.  You request

save as: Example.5.12.garbage

in order to get it saved under

 Example.5.12.xopp.

**Comment by suisseWalter** [comment]
I agree.
also note that if foo.pdf is a pdf you want to annotate then foo.xopp and foo.pdf.xopp will both be annotations of the foo.pdf file.
this also works for foo.1 (yes you can annotate pdfs that don't end in .pdf, as long as you open them from the "annotate pdf dialog) annotations can be called foo.xopp or foo.1.xopp. 

I think the proper fix would be to only strip .pdf (and maybe .xopp). I do think stripping .pdf silently is fine. as it would be quite annoying otherwise and leads to cleaner filenames. 

 but I don't (yet) have the skills to write a PR for this.(maybe I will have time to read into the code base in the autumn and then try to fix this). so it might need a actual dev to fix this one.

**Comment by Aniruddha-Deb** [comment]
@suisseWalter I've worked on a PR implementing this. It removes .pdf, .xopp and .xoj extensions (if any) and then appends xopp to the filename, rather than the simple `replace_extension` that was happening previously

Old code (in `SaveJob::save`)
```
fs::path const filepath = doc->getFilepath();
auto const target = fs::path{filepath}.replace_extension(".xopp");
```

New code:
```
fs::path filepath = doc->getFilepath();
Util::clearExtensions(filepath, ".pdf");
auto const target = fs::path{filepath}.concat(".xopp");
```

Let me know if any further changes are required, or I can go ahead with this PR
