### ISSUE TITLE
Copy Image from Clipboard not working on MacOS

### ISSUE THREAD

**Issue by saif-ellafi** [xournalpp/xournalpp#3455]
**Affects versions :**
 - OS: Mac
 - Which version of libgtk do you use: No idea
 - Version of Xournal++: 1.1.0
 - Installation method: MacOS Executable

**Describe the bug**
I would like to paste images on my notes. It seems not to be working when trying to copy paste them.

**To Reproduce**
1. Copy any image from a browser or take a screenshot
2. Command + V (or click on the Edit menu and click Paste)
3. Nothing happens

**Expected behavior**
Expected an Image on my board

**Notes**
Works well on Linux as a Flatpak and as well on Windows.

**Comment by SteveHaker** [comment]
This bug is back in 1.1.2.  I think it was fixed, but has now returned. I am not sure if I should open a new issue.

Affects versions :  
 - OS: Mac O/S, Monterey 12.5
 - Version of Xournal++:  1.1.2 Built on Oct 16, 2022 with libgtk 3.24.33
 - Installation method: Official release

It works as expected in: 1.1.1+dev Built on Feb 15 2022 with libgtk 3.24.30.

Thank you!

**Comment by rolandlo** [comment]
Could you please try out 1.1.2+dev from the [nightly releases](https://github.com/xournalpp/xournalpp/releases/tag/nightly) as well?

**Comment by SteveHaker** [comment]
I tried it on 1.1.2+dev, Built on Nov 23 2022, 00:06:43 with libgtk 3.24.33.
The problem is still there.
Please let me know if there is anything else I can test. 
Thank you very much!

**Comment by rolandlo** [comment]
I'm debugging the problem on MacOS Catalina. Seems copying works fine, but Xournal++ (or Gtk) gets confused by different paste targets. 
@SteveHaker Two questions:
- Does copy and paste work fine for strokes/text in Xournal++? For me it sometimes works and sometimes does not work.
- Do you observe any unusual output in the terminal? Note that you can run `xournalpp` from the Terminal app, by moving into the Xournal++.app folder (`cd Xournal++.app`) and executing `./Contents/MacOS/xournalpp`. Alternatively you can CTRL+click on the Xournal++.app-bundle in the Finder, select `Search package contents`, locate the executable in `Contents/MacOS` and execute it by double-clicking on it.

**Comment by SteveHaker** [comment]
I have had trouble pasting other objects in some versions, but in 1.1.2+dev built on Nov 23, 2022 I can cut and paste text, drawings, and highlighting.

At startup I get this:

(xournalpp:72848): Gtk-WARNING **: 08:24:33.815: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

When trying to paste a screen shot I get this:

** (xournalpp:72848): WARNING **: 08:27:12.429: InputStreamException: End reached, but try to read String, index 0 of 0, ../src/util/serializing/ObjectInputStream.cpp: 154

Whenever I open a menu (File, Edit, View, Navigation…) I get this:

(xournalpp:72848): GLib-GObject-CRITICAL **: 08:28:06.782: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

Using the Image icon, I am able to insert an image that is saved as a file. Once it is inserted I can copy and paste it somewhere else. I can’t paste images that are the result of a screen shot and are held in the clipboard.

Thank you!

**Comment by rolandlo** [comment]
Thanks for your report. 

> ** (xournalpp:72848): WARNING **: 08:27:12.429: InputStreamException: End reached, but try to read String, index 0 of 0, ../src/util/serializing/ObjectInputStream.cpp: 154

I got that message as well. That has to be a bug. I will figure it out. Also I have noticed that Xournal++ prefers to paste text compared to images. When I copy a screenshot from the web browser, the url is sometimes put into the clipboard as text. In that case Xournal++ will paste the url, not the image.

**Comment by rolandlo** [comment]
I think I found the reason why Xournal++ doesn't paste pictures from the Clipboard on MacOS. It's because in 

https://github.com/xournalpp/xournalpp/blob/45a9c7d0f98c6a142f162045a1183afb6ef59e34/src/core/control/ClipboardHandler.cpp#L302-L308

for some reason Gtk says that there is text in the Clipboard via `gtk_selection_data_targets_include_text`, but later in 
https://github.com/xournalpp/xournalpp/blob/45a9c7d0f98c6a142f162045a1183afb6ef59e34/src/core/control/ClipboardHandler.cpp#L51-L53
and
https://github.com/xournalpp/xournalpp/blob/45a9c7d0f98c6a142f162045a1183afb6ef59e34/src/core/control/ClipboardHandler.cpp#L278-L283
it turns out that the text is empty.

If I remove the line 
```c++
handler->containsText = gtk_selection_data_targets_include_text(selectionData);
```
(so that Xournal++ thinks there is no text to paste) then the picture is pasted fine.
Not sure how to fix it. Sometimes copying a picture into the clipboard (e.g. from the web) will also paste text into the clipboard (the url of the picture) and in that case the text is pasted and not the picture.

Maybe we should add a menu option `Paste special` (activated via `CTRL+Shift+v`) like in many other apps (e.g. LibreOffice Writer), where you can choose how you want to paste if there are different options.

**Comment by rolandlo** [comment]
Here is an upstream bug report on the Gtk issue tracker: https://gitlab.gnome.org/GNOME/gtk/-/issues/1757
Sad it hasn't been fixed.

**Comment by rolandlo** [comment]
@saif-ellafi  @SteveHaker I made an attempt for a fix, PR #4489. It works for me on MacOS. Please try the build from https://github.com/xournalpp/xournalpp/pull/4489#issuecomment-1342259577 and let me know if it works for you as well.

**Comment by SteveHaker** [comment]
Thank you. Unfortunately, I get a message that 'macOS cannot verify the developer of “xournalpp”'. I don't have an administrator's name and password to override and execute. I haven't seen this problem with other builds, such as the nightly builds.

**Comment by rolandlo** [comment]
@SteveHaker How did you start Xournal++? Like in [this video](https://github.com/xournalpp/xournalpp.github.io/pull/53#issuecomment-1035994783)?

**Comment by SteveHaker** [comment]
It's working, and it's working very well!!  Clipboard text and images both working.  This is wonderful. Thank you so much!
