### ISSUE TITLE
Code style issue (and possible refactoring): Change "Ruler" to "Draw Line" in code

### ISSUE THREAD

**Issue by siliconninja** [xournalpp/xournalpp#349]
I saw "Ruler" and "Draw Line" in different places when I was looking at the code, which confused me.

Explanation:

The "Ruler" in the GUI refers to the "Draw Line" tool in the GUI (basically, the "Ruler" in most parts of the GUI mean that it draws a line when you click and hold on the note page and drag the mouse cursor to another location and release to draw a line):

Good:

![screenshot_20181121_150311](https://user-images.githubusercontent.com/29907828/48867854-93365b80-eda5-11e8-8bb9-cea9639e2792.png)

Issue:

![screenshot_20181120_230817-xournalppbug](https://user-images.githubusercontent.com/29907828/48867865-9e898700-eda5-11e8-82d5-e542ad6bc0c2.png)

![screenshot_20181121_155733](https://user-images.githubusercontent.com/29907828/48868044-4737e680-eda6-11e8-8bb7-70ac73da1ec6.png)

![screenshot_20181121_160339](https://user-images.githubusercontent.com/29907828/48869138-18237400-edaa-11e8-846a-9ab1d56900be.png)

In the above image, I also noticed that the shortcut is Shift+Ctrl+L. A good way to remember the shortcut for this is that "L" means it draws a line. Shift+Ctrl+R would make more sense for a ruler tool, because it does something different, described in detail in https://github.com/xournalpp/xournalpp/issues/343#issuecomment-440803325 (**Ctrl+F, search for Meanings of the 2 different tool names**).

And there is also a "calibration ruler" in the settings, which is entirely different:
![screenshot_20181121_154855](https://user-images.githubusercontent.com/29907828/48867814-700bac00-eda5-11e8-9e0e-5fcfe0a7c92d.png)

For more detail on why I feel the different names are confusing, please see https://github.com/xournalpp/xournalpp/issues/343#issuecomment-440803325 (**Ctrl+F, search for Why I find this confusing**)

When trying to fix the initial problem I had in issue #343, I tried changing the name of the tool in ui/toolbar.ini to DRAW_LINE to see if that would work. There is DRAW_CIRCLE, DRAW_RECTANGLE, DRAW_ARROW, etc. but why "RULER" for "DRAW_LINE"?
 
My proposal is to replace RULER with DRAW_LINE so contributors can understand the difference.

I feel that these changes to the code would make it much easier to debug specific GUI issues like if a menu is not opening, or a button is not working, or if something is causing a crash by looking at the logs.

Here are some code files that need to be changed. (**I think there are MANY more than that.** I'm just giving off a few examples I know of. Here's the search that I did: https://github.com/xournalpp/xournalpp/search?q=RULER&unscoped_q=RULER)

https://github.com/xournalpp/xournalpp/blob/master/src/control/Tool.cpp#L140-L161

(add DRAW_LINE tool)

https://github.com/xournalpp/xournalpp/blob/master/src/control/Tool.h

(line 94, 108, 121, 151, change Ruler -> drawLine)
anything that refers to isEnableRuler() method (Github search isn't very good)

https://github.com/xournalpp/xournalpp/blob/1d177cfc781965b489aeeb2f090036cbff1b6d1c/src/gui/toolbarMenubar/ToolDrawCombocontrol.cpp#L19

(change ACTION_RULER to ACTION_DRAW_LINE and rename ruler.svg to draw_line.svg)

etc...

Afterwards, update the GUI toolbar constants:

https://github.com/xournalpp/xournalpp/blob/master/ui/toolbar.ini#L52

(RULER -> DRAW_LINE)

etc... (probably more files)

**Comment by andreasb242** [comment]
First: you are generally right.

Pull: https://github.com/xournalpp/xournalpp/pull/351
I simplified and fixed some settings, so all tools should be stored and read correctly from settings.
I fixed some namings in the GUI, all you have mentioned in the Screenshots above (hopefully). Yes, Consistency in UI is really important. I didn't mention that, because I always used the toolbar, not the Menu. Maybe this happend on GTK3 merging, maybe not.

I also changed the name of one enum value, as I merged two enum and I anyway breaked the compatibility in this case, but I had to fix it this way.

For me this is now fixed.
You can edit the Toolbar by drag and drop, so there is no need to change the names there. And I don't think the users do this, as Drag & Drop is much easier. But if you simple change the name, you will break the compatibility! A standard user will recognize that a tool item is missing, but not that the name in the config file is not consistent. If there is a change, it needs to be backward compatible.

If you whish to change names in the code, and fix inconsistency this will also be OK.
In this case create a pull requests, I'll merge them. But the Pull Request needs to be reviewable, so don't change to much per pull, else it's really hard to review.
I won't do this, I'm currently working on bugs and features.

For me this ticket is closed now.
But you can still reply, I'll get a mail and therefore usually also read it.

Pull Request with fixes / improvement are **always welcome**.
So I hope it's OK for you.

**Comment by siliconninja** [comment]
Thank you for the comment. This is OK with me.
If I get to it I might do a pull request. Unfortunately I don't have very much time after this week so I'm contributing what I can to the project just because I like to help out.

**Comment by andreasb242** [comment]
I'm reading all your comments, but I need some time to respond ;-)
I think this Ticket is don, I'll answer to the other tickets.
