### ISSUE TITLE
Replace Windows release 1.1.0 with 1.1.0-hotfix.1 on xournalpp.github.io

### ISSUE THREAD

**Issue by ehamminga** [xournalpp/xournalpp#3713]
**Affects versions :**
 - OS: Windows
 - Which version of libgtk do you use: <3.24.30
 - Version of Xournal++: 1.1.0
 - Installation method: official release

**Describe the bug**
Downloaded and installed the latest version from https://xournalpp.github.io/installation/windows/
Pinch to zoom, one finger scroll, stylus pressure sensitivity not working. Touch input turned into stylus input and could not disable in settings. After installing 1.1.0-hotfix.1, all my issues were resolved.

From the Releases page I can see that the team is already aware of the issues with version 1.1.0 and recommends the hotfix instead. But this is not what you get when users download from xournalpp.github.io. It could leave Windows users with a bad experience which does not do this great program any justice. Will you consider making the 1.1.0-hotfix.1 the default download on xournalpp.github.io? Thanks

**Comment by rolandlo** [comment]
I agree, 1.1.0-hotfix.1 should currently be recommended and made the default download on the website. I have created a [pull request](https://github.com/xournalpp/xournalpp.github.io/pull/63) to change that.
Let me point out that with the hotfix-version Wacom-tablet users may want to set the environment variable `GDK_WIN_32_TABLET_INPUT_API` to `wintab` though, since for them the `wintab` drivers seem to work better than the Windows pointer input stack drivers. See [this post](https://github.com/xournalpp/xournalpp/issues/3218#issuecomment-891173434). When Gtk 3.24.31 make it into the Windows version, that is probably not needed any more.

**Comment by rolandlo** [comment]
The website is updated, so I will close the issue.
