### ISSUE TITLE
Provide a winget package

### ISSUE THREAD

**Issue by derkrasseleo** [xournalpp/xournalpp#3913]
**Is your feature request related to a problem? Please describe.**
The windows builds are currently shipped in a zip folder. The zip only contains the windows executable, which makes no sense to me. (But I'm not a dev, so maybe it makes sense) In order to create a winget package, it is necessary to link to the executable of the program.
**Describe the solution you'd like**
There should be a winget package for xournalpp. Maybe providing only the windows executable is an option.
Maintaining a winget package. Winget is the official package manager for windows.
**Describe alternatives you've considered**
The devs of winget are currently working on supporting zip packages, so this isn't a huge issue. But there is no ETA for this feature,
**Additional context**
I think in the future Winget will be more commonly used and therefore a winget package will be essential for all windows software.

**Comment by Technius** [comment]
I think this would be a good idea. We currently generate our installer using NSIS, but I think that there shouldn't be too much work involved in adapting the current build scripts to winget (hopefully).

> The zip only contains the windows executable, which makes no sense to me.

To clarify, there's two windows builds that we are currently shipping on the nightly version:

1. Installer version, which is an installer `.exe` in a zip file (this should really just be an `.exe` by itself, since the contents of the `exe` are already compressed).
2. A "portable" standalone version, consisting of the binaries & required resources. This can be used by unzipping & directly running the `bin/xournalpp.exe` file.

**Comment by Technius** [comment]
Actually, it seems like we can submit the NSIS installer directly, as long as we follow the expectations outlined in the winget documentation:
* https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#tips-and-best-practices
* https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation#submission-expectations

We will need to fix the following issue:

> The application installs and uninstalls correctly for both administrators and non-administrators.

Only adminstrator install is supported at the moment, so we'll need to adjust the NSIS scripts to support local installs as well.

**Comment by leochras** [comment]
Do you want me to maintain the package, or do you want to do it yourself? Or even auto-update the package somehow? If yes, is there a link to the .exe that's published? I can only find the ZIP. If there's an .exe in the build pipeline, can you just include it in the releases?

**Comment by Technius** [comment]
> Do you want me to maintain the package, or do you want to do it yourself?

We've a bit short-handed at the moment, and I think it would be better for the community to maintain the package since it's going to be submitted to a community repository.

> Or even auto-update the package somehow?

"Auto-updates" should be handled by the community repository update workflows.

> is there a link to the .exe that's published

Not at the moment. However, the exe can be extracted from the setup zip.

**Comment by leochras** [comment]
`Not at the moment. However, the exe can be extracted from the setup zip.`

winget can't work with zip at the moment, but it should be possible in the near future. Without a link to an exe a winget package is not possible right now.
I would maintain the package, but I don't want to just make a repository where I host the most recent exe. I think the installer should still come from this repo.

**Comment by LittleHuba** [comment]
I'll modify the CI to upload the exe directly.
