### ISSUE TITLE
Highlighted text (via other programs) sometimes appears completely yellow covering the text itself, if I export xopp as PDF

### ISSUE THREAD

**Issue by All3xJ** [xournalpp/xournalpp#4015]
**Affects versions :**
 - OS: ArchLinux
 - Which version of libgtk do you use
     - libgtk: 3.24.33
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     - Xournal++ 1.1.1+dev
 - Installation method: aur (git version)

**Describe the bug**
If I highlight the text with external programs such as Okular, and then I export the xopp file as PDF, it appears this way:
![image](https://user-images.githubusercontent.com/20903913/156887325-9cc816cb-b9c3-4d1f-a10c-fc1259ed366e.png)
but not every highlights, only some of them.

**Additional context**
I remember that I have this issue since years.
You can check it with this two files for example: https://mega.nz/folder/2N9nmSBR#Msm2rHkgqkKwjOfeyB-cqg
Export as PDF and you will see the bug. I have this bug since years

I opened this issue: https://github.com/xournalpp/xournalpp/issues/3890 but it's old and I don't think someone will care about it, so I am closing it and opening this.

What can be the bug? Is it fixable? Can I contribute to fix it? If you help me and tell me what could be the issue and the salient code parts that are responsible of it, I can try to fix it.

**Comment by funnym0nk3y** [comment]
Usually it is bad practice to open several tickets for one issue and probably lessens the chance for somebody to care. Additionally the answers of other people are missing now and the issue seems smaller than it is. Most people working on FOSS do that in their free-time so it could take some time for an answer. So I'd reopen the old issue and close this one and just have a little patience.
