### ISSUE TITLE
Can't open dropdown menus via touch/pen input

### ISSUE THREAD

**Issue by taaem** [xournalpp/xournalpp#402]
As the title says I'm not able to open any dropdown menus, like the top row or the page background menu.
If I click on the menu it shows that it registeres the touch but if I stop touching it, it just goes to back to normal instead of opening the menu.
The consequence is I need to use my touchpad/mouse to change *any* setting.

**Comment by andreasb242** [comment]
I can also not reproduce this Problem, can you tell us which Distribution in which version you are using, and if you configured something special (whatever, I don't know, exotic Compiz Plugin etc.)

Thank you.

**Comment by morrolinux** [comment]
I maybe also have this issue when using touch. 
When I click on a dropdown menu, it opens, but I cannot click any of the options available as the touch seem not to get registered. Does not happen with the pen for me.
As this happens on all applications on my system, I think it could be more a DE/Xorg/input driver issue than a Xournalpp one.
Please let us know if you have this issue also with other gtk2 and 3 applications

**Comment by taaem** [comment]
So I'm using Fedora 29 on Gnome 3.30 and the latest Gtk.
I just tested this and this only happens on Wayland if I'm switching back to X everything works fine!

**Comment by taaem** [comment]
Oh I just tested this with Evolution and there I have the same issue on Wayland!
So this is probably a Gtk bug then.

**Comment by andreasb242** [comment]
I didn't test Wayland at all. May I should.
This is not a Xournal Bug, and we cannot fix it. I'm currently not sure where you have to report such a bug, on GTK, Fedore, Wayland?

However, I'll close this bug, but if you report the Bug somewhere else, please post the Link here. Even if the bug is close, it will may be found by searching, and then it's really helpful to find the real issue.
(you can also comment closed ticket)

If you get a hint, how it can be fixed in Xournal++ you can reopen the ticket at any time.

**Comment by taaem** [comment]
Upstrea bug: https://gitlab.gnome.org/GNOME/gtk/issues/1490
