### ISSUE TITLE
Unnecessary includes in header files should be removed or replaced by forward declarations

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#4095]
The header files contain a lot of unnecessary includes, and a lot of them can be replaced by forward declarations.

Fixing this would greatly improve on build time, especially when rebuilding after minor changes in a small part of the code.

As an example, building the app, touching src/util/RAII_wrappers.h in #4082 and rebuilding triggers a rebuild of almost every .o targets. Replacing the include of gui/PageView.h by a forward declaration in every header reduces this rebuild to a dozen of files.

There are tools out there to automatize this process ([cppclean](https://github.com/myint/cppclean) or [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use))
 
@xournalpp/core Does anyone have experience with either of those tools (or another one)?
Would applying one of them to our source tree be a good idea?

**Comment by LittleHuba** [comment]
Yes this is something that is a problem since quite some time.

I have used IWYU previously. It does it's job. Cppclean seems like a tool that will tell us a bunch of other stuff as well that has nothing to do with includes.

Keep in mind that both tools will just give you hints what to change but you'll still have to change it yourself.

**Comment by Febbe** [comment]
After reading the documentation, it should be very easy to use:

```
cd /path/to/xournalpp
git switch -c iwuu_test
cd build
cmake -GNinja ..
iwyu_tool.py -p .
```

This is, because we already create a compilation database for the use with clang-tidy.
