### ISSUE TITLE
how to make the bounding box have less space between objects

### ISSUE THREAD

**Issue by vladQll** [xournalpp/xournalpp#4173]
**Versions affected:**
 - OPERATING SYSTEM: [Windows].
 - What version of libgtk do you use [3.24.34].
 - Xournal++ version: [1.1.1+dev]
 - Installation method: [.exe]

**Describe the bug**
the bounding box of some objects are too big even when this object is very small the difficulty starts to be perceived as I increase the number of objects, pencil strokes, highlighter strokes sometimes it is a bit annoying to select them if I would like to change their color or just drag them. 

**Expected behavior**
I would like to know if there is a way to delimit the object frame as minimal as possible as in inkscape or illustrator.

![image](https://user-images.githubusercontent.com/28522011/181907678-331701db-b9a6-41fa-a34b-6d5b22aa80dd.png)

**Comment by bhennion** [comment]
What you see when you select an object is not its bounding box: a padding is being added, for display purposes. The bounding box itself, in the case of your red circle for instance, contains exactly the circle.

So your report is confusing to me: what issue do you actually encounter when trying to select things?

We can of course discuss why a padding is added in the display of selections, but I think it was intentional, so not a bug.

**Comment by vladQll** [comment]
I understand I thought that was the bounding box, the problem I find some cases is that when I am superimposing several strokes and would like to select a stroke or text that I place at the beginning and sometimes as I do not draw very large is difficult to select them because when I try to select the object that is above is selected and I thought it was because of the space occupied by the fill box that you mention that is called , It is not something that can take screen shot, and it is not something that bothers me much but if it happens again I will try to record and send a short video, as to why I put it with the ticket bug honestly did not know where to put it, since it is not a request for new function or problem with the input.
