### ISSUE TITLE
I want to buy a surface, I want to know if this software can call surface's rear camera to insert the picture directly.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [xournalpp/xournalpp#4250]
**Is your feature request related to a problem? Please describe.**
It's as easy as a mobile terminal.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WillNilges** [comment]
I personally am not aware of any WebCam integration in this app, but it would certainly be a useful feature. GTK3 might make it pretty easy

**Comment by hyperupcall** [comment]
If you want to check kernel support for Surface cameras, you can check the [linux-surface](https://github.com/linux-surface/linux-surface) repository for more information. I own a Surface Pro 5 and I can tell you that the camera doesn't work with the stock kernel.
But umm, this issue should really be closed because your question isn't specific to xournalpp, and if it was, the place to ask would be [Discussions](https://github.com/xournalpp/xournalpp/discussions)

**Comment by Benjamin-Watson0** [comment]
> I personally am not aware of any WebCam integration in this app, but it would certainly be a useful feature. GTK3 might make it pretty easy

Thank you for your reply.

**Comment by Benjamin-Watson0** [comment]
> If you want to check kernel support for Surface cameras, you can check the [linux-surface](https://github.com/linux-surface/linux-surface) repository for more information. I own a Surface Pro 5 and I can tell you that the camera doesn't work with the stock kernel.
> But umm, this issue should really be closed because your question isn't specific to xournalpp, and if it was, the place to ask would be [Discussions](https://github.com/xournalpp/xournalpp/discussions)

Thank you for reminding me, I have raised this in the discussion.
