### ISSUE TITLE
Unwanted straight lines appear when drawing ellipses via pen input

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#4316]
**Affects versions :**
 - OS: Arch Linux / X11
 - libgtk: 3.24.34
 - Version of Xournal++: 31d7dad7ba8d566a17cc6480bd62df7b17870489 or after (master)
 - Installation method: build from source

**Describe the bug**
Unwanted straight lines appear when drawing ellipses.

**To Reproduce**
1. Start with Pen tool.
2. Set draw type 'ellipse'.
3. You can draw ellipses or circles as before, but weired segments can be seen.
4. If you only touch and  don't move the pen tool, only the weired segment is drawn.
5. Repat the step4, then you can see weired long lines.

**Expected behavior**
No straight line is displayed.

**Screenshots of Problem**

https://user-images.githubusercontent.com/6355486/195683632-73b1ce70-53f5-4ab6-9c4f-b882e520d510.mp4

**Additional context**
I feel that ellipses are displayed not so smooth as before the commit 31d7dad7ba8d566a17cc6480bd62df7b17870489.
Edit: I've created another issue #4318 on this point.

**Comment by tattsan** [comment]
@bhennion  your recent energetic commits are really great! Could you please look at this report?

**Comment by bhennion** [comment]
I opened a PR which may fix this. @tattsan would you mind trying it out and report in #4317?

**Comment by bhennion** [comment]
This only happens when using the pen (see https://github.com/xournalpp/xournalpp/pull/4317#issuecomment-1278547276), and I can reproduce as well.

The root of the problem is that pen input sequences start with a ButtonPress event, followed by a MotionNotify event (without any motion), while mouse input sequence do not. This should be homogenized.

In any case, fixing the straight lines is really easy: just set BaseShapeHandler::currPoint upon the ButtonPress event. The following MotionNotify event will then be filtered out (as the motion is null, thus to small to satisfy validMotion == true). I'll add this to #4317.
