### ISSUE TITLE
Quality of life changes for Color PIcker

### ISSUE THREAD

**Issue by Lolol4572** [xournalpp/xournalpp#4569]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when picking a new color using the hex tool. When I select a color and go to the custom color picker, it always selects red, rather than the hex of the color I was on.

**Describe the solution you'd like**
I would like it to go to the hex value of that color, like it does on Google Docs, which makes me able to figure out the hex value and make slight adjustments without screenshotting it and going to a color picker website.

**Describe alternatives you've considered**
Addition of a color picker tool, maybe?

**Additional context**

**Comment by rolandlo** [comment]
@Lolol4572 If I understand correctly you click on the custom color button in the toolbar, choose one of the predefined colors and want to adjust it a little. Instead of clicking on the `+`-button you should right-click on the chosen predefined color and choose `customize`. Does that already solve your problem?
![grafik](https://user-images.githubusercontent.com/40485433/212478887-6b35ec6a-cef7-4ca8-a5f5-56a660013e0d.png)

**Comment by Lolol4572** [comment]
Oopsie-daisies! I didn't know about that until now. I'm a fairly new user btw. I may as well close this issue now.

**Comment by Technius** [comment]
As originally suggested, we can still improve the UX of using the hex color picker, so reopening. Also see #4575 which would address this problem.
