### ISSUE TITLE
Reduce rerendering of large areas

### ISSUE THREAD

**Issue by hrdl-github** [xournalpp/xournalpp#4580]
https://github.com/xournalpp/xournalpp/pull/4502 and https://github.com/xournalpp/xournalpp/pull/4493 reduce the size of repaint areas. In combination they decrease the lag significantly on the PINE64 PineNote, which features a electrophoretic display.

In addition I use https://github.com/xournalpp/xournalpp/commit/1639cc0cf26bbbf90203b4339227e46701fb27a2 and https://github.com/xournalpp/xournalpp/commit/05ffd0449a8aae53ed4f4ed65de0a997ccbb22c5 to prevent regular completed strokes from being repainted, which avoids large damage region to avoid occasional delays due to how the display driver processes damage regions.

I also skip rerendering and repainting pages upon change entirely (https://github.com/xournalpp/xournalpp/commit/e949b630004add56fab63e6317bb1c5afab762a9) for the same reason. At the moment this means that a changed background is not rerendered and repainted until e.g. the page is changed.

I have two questions:

1. Do you have an idea when rerendering and repainting is required or desired? Besides the delayed change of background I haven't noticed any difference in the rendered output. I've disabled rerendering only for the pen tool at the moment (https://github.com/xournalpp/xournalpp/commit/05ffd0449a8aae53ed4f4ed65de0a997ccbb22c5).
2. Would you be interested in merging these contributions once they are mature? They add a small amount of complexity to the rerendering logic and possibly don't yield any noticeable improvement for the majority of users / devices.

**Comment by rolandlo** [comment]
About 2.: Performance is one of the major goals of Xournal++, so yes, even if it adds a small amount of complexity to the rendering logic and the majority of users/devices wouldn't feel any noticeable improvement, it would be great to have those contributions.

**Comment by bhennion** [comment]
First, some comments about the patches you wrote, then I'll try and answer your question 1.

> In addition I use [1639cc0](https://github.com/xournalpp/xournalpp/commit/1639cc0cf26bbbf90203b4339227e46701fb27a2) and [05ffd04](https://github.com/xournalpp/xournalpp/commit/05ffd0449a8aae53ed4f4ed65de0a997ccbb22c5) to prevent regular completed strokes from being repainted, which avoids large damage region to avoid occasional delays due to how the display driver processes damage regions.

Those patches only do something because of a bug in `StrokeHandler`: when a stroke is finished, `fireElementChanged()` is called, leading to a call of `PageView::elementChanged()`. But during this call, `PageView::inputHandler` is assigned to the `StrokeHandler` instance, and the test

https://github.com/xournalpp/xournalpp/blob/be94f16236288eed82dba7702e28d31c58d5bd36/src/core/gui/PageView.cpp#L1177-L1179

should avoid any rerendering in this case. This is somehow broken, but I think this is fixed in #4158 (although this PR is not quite ready as you can in its discussion thread).


> I also skip rerendering and repainting pages upon change entirely ([e949b63](https://github.com/xournalpp/xournalpp/commit/e949b630004add56fab63e6317bb1c5afab762a9)) for the same reason. At the moment this means that a changed background is not rerendered and repainted until e.g. the page is changed.

This is a bit drastic, but limiting calls to repaint/rerenderPage is a good idea.
There is one thing that could be experimented on though: there is a timer triggering a rerender of every modified page every 5 seconds

https://github.com/xournalpp/xournalpp/blob/be94f16236288eed82dba7702e28d31c58d5bd36/src/core/control/Control.cpp#L158
https://github.com/xournalpp/xournalpp/blob/be94f16236288eed82dba7702e28d31c58d5bd36/src/core/control/Control.cpp#L272-L288

Those total rerenderings (and the repaintings that come with it) mostly unecessary as the tool handlers should always trigger the necessary renderings and repaints themselves. I do see only one use for them: when writing to a lower layer, the strokes are first displayed on top, and this timer-thingy rerenders them below the upper layers:

https://user-images.githubusercontent.com/17818041/212303324-6f640613-6e46-43cf-b829-57b9ad2385c2.mp4

So, to remove this timer entirely, one needs to address this question. I'm not sure how though.


I'll try to explain how the rerendering/repainting business works, it may help with the above and answer your question 1.

So, the app keeps a buffer (i.e. an image) for each of the most recently displayed pages. This buffer contains (more or less) exactly a drawing of all the elements belonging to the page. Note that an element which is being created (like a stroke), or being edited, selected, moved, and so on, **does not belong to the page and thus is does not appear on the page buffer**. Those elements are displayed by their handlers (or their views after the ongoing refactoring).

In the code base, `Rerender` always means "refreshing this buffer and then repaint".

`Repaint` on the other hand means updating what is actually on screen. This means showing (part of) the page buffer, and possible additional stuff (Overlays -- e.g. elements under edition, drawing aids, setsquare, highlighing of search results, ...)

**Comment by rolandlo** [comment]
> There is one thing that could be experimented on though: there is a timer triggering a rerender of every modified page every 5 seconds
> 
> https://github.com/xournalpp/xournalpp/blob/be94f16236288eed82dba7702e28d31c58d5bd36/src/core/control/Control.cpp#L158

As I understand this timer triggers rerenders of the pages on the sidebar every 5 seconds. Those pages are not updated automatically. Maybe that's all that this timer should do, not rerender the pages on the XournalWidget.
