### ISSUE TITLE
PDF links not working after drawing on page

### ISSUE THREAD

**Issue by stscheff** [xournalpp/xournalpp#4627]
**Affects versions :**
 - OS: Windows 10 Pro 22H2 / 2019 IoT Ent
 - Which version of libgtk do you use: 3.24.36
 - Version of Xournal++: 1.1.3+dev nightly 20230126
 - Installation method: portable

**Describe the bug**
I can follow internal links with the new text select tool in a freshly opened PDF file. Those links stop working on pages that have been drawn on. I assume that's not the intended behavior?

**To Reproduce**
1. open PDF
2. draw on Page with the pen tool
3. click on link

**Expected behavior**
jump to link destination

**Additional context**
That's on an HP Envy X360 and an ELO I-Series PC. Both with "touch drawing" enabled for the screen.

**Comment by rolandlo** [comment]
Oh, that's bad! I can confirm. We need to fix this.

**Comment by rolandlo** [comment]
@stscheff Seems that's intended actually. You should just press `Alt` while clicking. See
https://github.com/xournalpp/xournalpp/blob/53ddf0c21efb1d3c84e705de30a248108c5a21f0/src/core/gui/PageView.cpp#L712-L717

**Comment by rolandlo** [comment]
> > @stscheff Seems that's intended actually. You should just press Alt while clicking. See
> 
> Does this make sense though? Under what circumstances [cw]ould one select anything when using one of the two PDF selection tools?

I also don't see the point of it. Looking at the PR's implementing the feature it seems that holding `Alt` was introduced when the usual selection tools were used instead of the PDF selection tools for following links. See https://github.com/Technius/xournalpp/pull/1/commits/887cd1d2d30509a925bb012b345757e8504e182b
So back then it made sense to require Alt being pressed as one could select strokes, but now it doesn't make sense any more.

@Technius Can we simply remove the condition ` isBackgroundLayer || !layer->isAnnotated() || pos.isAltDown()` altogether?

**Comment by hmpthcs** [comment]
I noticed this as well. Not sure if you have an additional issue though, as I can get links working again by switching to the background layer AND choosing pdf tools. Not sure why toggling on pdf tools can't just automatically go to what is presumably the only layer with pdf links in it (background).

**Comment by Technius** [comment]
> @Technius Can we simply remove the condition  isBackgroundLayer || !layer->isAnnotated() || pos.isAltDown() altogether?

Yes, that should be removed altogether--it's an artifact from when the prototype version used the normal selection tools rather than PDF selection tools.
