### ISSUE TITLE
Preserve folder when exporting to PDF

### ISSUE THREAD

**Issue by markwmuller** [xournalpp/xournalpp#463]
When selecting "export to PDF", the dialogue box always opens at ~. Preferable would be behaviour like "save as", where the dialogue opens at current folder (where original file was).

**Comment by andreasb242** [comment]
Look at bool Control::showSaveDialog()
This is working now...

Generalisation is already done for the Open Dialog:
XojOpenDlg

For the Export / Save Dialog was it not done, because the Export configuration was displayed in a custom Save Dialog. Since I refactored this (Export Setting is an independent dialog now), also the Save Dialog can be generalized like the open Dialog.

**Comment by andreasb242** [comment]
@peetCreative

I'm going to try to fix PDF Stuff today I think.
I'll probably do a Cairo only PDF Export, to fix all this bugs we have now, and to get a build without Poppler private Libs.

So I probably change Export stuff. If you didn't start yet on this issue please wait.

**Comment by peetCreative** [comment]
I've done a bit generalization and I pushed my stuff to. I didn't had time for testing, it should compile. Use it as you want.
https://github.com/peetCreative/xournalpp/tree/fix_export_autonames

**Comment by andreasb242** [comment]
Ok, It didn't compile. Therefore I cannot merge it now. I try not to change something with affects you.
