### ISSUE TITLE
Huion HS610 Stylus Pressure settings don't do anything

### ISSUE THREAD

**Issue by jeffreyes900** [xournalpp/xournalpp#4649]
**Affects versions :**
 - OS:  Windows 10
 - Version of libgtk: 3.24.34
 - Version of Xournal++: 1.1.3

**Describe the bug**

**To Reproduce**
1. Find Pressure Sensitivity settings in Edit > Preferences > Stylus
2. Ensure that Enable Pressure Sensitivity is checked and latest Huion drivers are installed for the HS610 tablet
3. Attempt to write with the pen tool and apply various amounts of pressure after trying various different pressure settings

**Expected behavior**
Various drawing widths

**Screenshots of Problem**
(Optional) If applicable, add screenshots to help explain your problem.

![xournalpp_Gf5tSmnBci](https://user-images.githubusercontent.com/61217933/218288301-f0265641-8637-4c80-b5ba-7bd64dda75ce.png)

**Additional context**

Smoothing settings seem to work just fine, and there was no problems with detecting that I had a stylus and drawing tablet, so I'm just wondering if I've done something wrong or what.

**Comment by rodiecko** [comment]
Hi, on Windows I also could not use the pen pressure in xournalpp, oneNote, FoxitPDF and others. The pressure stops working when starting the tablet driver. working only in Krita and maybe in other drawing software (I didn't test).
So I disabled Windows Ink by Registry Tweak and checked the enable Windows Ink option in the tablet driver. It works now.
https://softwarekeep.com/help-center/how-to-disable-windows-ink
Tablets I use: Gaomon M10K Pro; Happens with Huion HS64 too.
It must be some conflict with the driver and Windows Ink because I was able to use it with OpenTabletDriver, but it doesn't have all the functionality of the Gaomon driver. 
On Arch Linux the pressure works with both the Gaomon driver and the DIGImend driver. 

Translated with www.DeepL.com/Translator (free version)

**Comment by jeffreyes900** [comment]
> So I disabled Windows Ink by Registry Tweak and checked the enable Windows Ink option in the tablet driver. It works now. 

I just noticed that I hadn't ticked the Enable Windows Ink option and tried it before even attempting the other solution you mentioned, and that seemed to have done it. I hadn't even noticed it was there in my driver settings. Thanks a lot.
