### ISSUE TITLE
The Wayland logo is being displayed in the top left corner of Xournal++ windows instead of the Xournal++ icon.

### ISSUE THREAD

**Issue by K4LCIFER** [xournalpp/xournalpp#4870]
**Affects versions :**
 - OS: Arch Linux
 - (Linux only) Desktop environment: KDE Plasma v5.27.5, Wayland
 - Which version of libgtk do you use v3.24.37
 - Version of Xournal++: 1.1.3 2dbd16d2
 - Installation method: Flatpak

**Describe the bug**
The Wayland logo is being displayed in the top left corner of all Xournal++ windows

**To Reproduce**
N/A

**Expected behavior**
I expect that the Xournal++ logo would be displayed in the top left corner

**Screenshots of Problem**
![image](https://github.com/xournalpp/xournalpp/assets/7829231/7f17c8ba-68cc-4b62-a538-8ea242f0a507)

**Comment by nicolasfella** [comment]
This is happening because there is a mismatch between the app id the window sets and the name of the desktop file.

Running `WAYLAND_DEBUG=1 xournalpp` shows the call `xdg_toplevel@33.set_app_id("xournalpp")`. However this should be `com.github.xournalpp.xournalpp`, because that's the name of the desktop file.

See https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id
