### ISSUE TITLE
PDF Export without paper style

### ISSUE THREAD

**Issue by morrolinux** [xournalpp/xournalpp#490]
It would be nice to be able to export pdf(s) without paper style (e.g: dotted, graph, lined, ruled, plain..) 
I've thought about two ways of doing this:
* Create an option to apply a chosen paper style to all pages at once, and export with "plain" style applied
* Create a checkbox to decide weather the paper style should be exported or not

**Comment by andreasb242** [comment]
Page Background: #69

I first need to fix the travis build for the new dependencies...

**Comment by Rmano** [comment]
Yep. sorry, I've been cryptic. Suppose you want to prepare an overlay page with some data and maybe a signature with `xournalpp`, and then "stamp" it on a series of documents... I prepared an example, see this zip file: 
[stamping-pdfs.zip](https://github.com/xournalpp/xournalpp/files/2660905/stamping-pdfs.zip)



So, I have prepared a signature with `xournalpp` (see the file `signing.xopp`); 

![image](https://user-images.githubusercontent.com/6414907/49701606-5912e980-fbee-11e8-9129-8fb101a17cef.png)

then I use for example `pdftk` (available as a snap at https://snapcraft.io/pdftk) and I issue:

```
pdftk lilla.pdf stamp signing.pdf output stamped.pdf
``` 

![image](https://user-images.githubusercontent.com/6414907/49701613-73e55e00-fbee-11e8-8508-2ebfddd031c2.png)

as you can see, the result has the "signing" with the white background in it. 

I can solve the problem opening the `signing.pdf` file with `inkscape`, ungrouping everything, and delete the blank page underneath the signature (the resulting file is `signing-inkscape.pdf`); now when "stamping" it over the same file: 
```
pdftk lilla.pdf stamp signing-inkscape.pdf output stamped-inkscape.pdf
```
the result is quite different:

![image](https://user-images.githubusercontent.com/6414907/49701618-8790c480-fbee-11e8-903f-6117cb24cb53.png)

My idea is that it would be great to have a "transparent" or "no background" page, so that the resulting PDFs could be used to stamp over forms...

**Comment by morrolinux** [comment]
This should be done via PNG export with transparent background, I've opened another ticket about it

**Comment by andreasb242** [comment]
We paint always a Background to the PDF.
@morrolinux you would anayway a PDF export without Background, this may solve this issue as well without any additional work.
