### ISSUE TITLE
Do it support xml or txt？

### ISSUE THREAD

**Issue by xh542428798** [xournalpp/xournalpp#4949]
Hello, Thanks so much to develop this app! I really like this software, it's exactly what I was looking for to separate PDF annotations from the original file! I have a question to ask: what is the content of the saved .xopp file, and why can't it be saved as XML or TXT format? This would allow me to use Git version control.

**Comment by CruzeBlade** [comment]
Hi,

.xopp files are essentially XML files that are compressed using gzip for storage space efficiency. If you want to view the contents of a .xopp file, you can follow these steps:

1. Rename the file extension from ".xopp" to ".gz" (this step is not always necessary).
2. Use an archive utility like Ark or 7Zip to open the file.
3. Inside the archive, you will find a single XML file that you can open with a text editor of your choice.

So, technically, it is definitely possible to store an XOPP file as a simple XML format.

However, as of now, I am not aware of any direct way to save XOPP files as XML or TXT formats. There is an ongoing discussion about a new file format, which you can find more information about here: [#937](https://github.com/xournalpp/xournalpp/issues/937). It might be a good idea to share your suggestion on that thread, so that the developers can consider it.

**Comment by rolandlo** [comment]
Please check [this answer](https://github.com/xournalpp/xournalpp/issues/3412#issuecomment-1288169733) for how to use Git version control with .xopp-files.

**Comment by bhennion** [comment]
Cosing this as a dup of #3412
