### ISSUE TITLE
SegFault in AbstractItem::actionEnabledAction()

### ISSUE THREAD

**Issue by TiredPisces173** [xournalpp/xournalpp#5086]
[errorlog.20230817-164355.log](https://github.com/xournalpp/xournalpp/files/12429706/errorlog.20230817-164355.log)

**Comment by rolandlo** [comment]
Does this keep popping even if you deleted the crash log? The crash you experienced is quite recent. The crash happened in `AbstractItem::actionEnabledAction`, maybe due to a data race.
https://github.com/xournalpp/xournalpp/blob/9d30b54fb3f61a7bc3a07e33d980981a1239c223/src/core/gui/toolbarMenubar/AbstractItem.cpp#L69-L80
