### ISSUE TITLE
Use GSettings for saving app preferences

### ISSUE THREAD

**Issue by rolandlo** [xournalpp/xournalpp#5166]
### Feature Description

Remove the homegrown way to save and load settings (in the `settings.xml`) via the `Settings` class and replace it by using [`GSettings`](https://docs.gtk.org/gio/class.Settings.html). From the docs:
>A convenient feature of `GSettings` lets you bind `GObject` properties directly to settings, using `g_settings_bind()`. Once a GObject property has been bound to a setting, changes on either side are automatically propagated to the other side. 

It seems to me that using `GSettings` would reduce the complexity of the `Settings` class and the maintenance burden.

### Additional Context

There is no hurry in migrating to `GSettings`. I'm currently redesigning the preference dialog (and other UI components) with Libadwaita, see https://github.com/rolandlo/xournalpp-libadwaita-mockup
It would make sense to combine the migration with the redesign.

**Comment by bhennion** [comment]
I'm not sure about this. It would probably simplify the SettingDialog a little bit, but our own Settings class has advantages over using GSettings:

1. Most settings are independent of the GUI. Some are read very often (e.g. at every new stroke) and the access cost would be increased with GSettings (a single address access is cheaper than accessing a hash table).
2. Strong parameter types: when reading an enum type setting, the type of the corresponding member of Setting adds a welcome static check. This would not work with GSettings, unless we add an overlay that would increase the complexity.

Overall, for things that are not intrinsically related to the GUI, I think we should avoid relying on GLib and friends. Those libs have more bugs than the standard libs and are more subject to changes.
Also, limiting the use of those libs makes easier further porting (say if someone wants to make a Qt frontend to get the app to run on more platforms - like IPadOS).

That being said, our Settings class is as dirty as it gets and would deserve a better structure.
However, I would not say it has a high maintenance cost.
The maintenance cost is mostly due to changes to the dialog's glade file. Splitting that in e.g. one file per tab would help there I guess.

**Comment by rolandlo** [comment]
Thanks for the detailed explanations. I see your points. Closing therefore.
