### ISSUE TITLE
Segmentation fault on startup popup close

### ISSUE THREAD

**Issue by tmoerschell** [xournalpp/xournalpp#5197]
### Operating System

Linux

### (Linux only) Distribution

openSUSE Tumbleweed

### (Linux only) Desktop Environment

KDE Plasma

### (Linux Only) Display Server

Wayland

### Installation Method

Build from source

### Xournal++ Version

1.2.1+dev (a3686cf6)

### libgtk Version

3.24.38

### Bug Description

When an emergency save or an error log (or both) exist, a popup appears on startup to delete or restore the file, respectively to view/report the error log. Clicking on any of the buttons will execute the specified action but also cause a segmentation fault. 

### Expected Behaviour

Xournal++ should not throw a segmentation fault. 

### Steps to Reproduce

1. Create a file `~/.config/xournalpp/emergencysave.xopp`
2. Open Xournal++
3. Click on any of the buttons

### Additional Context

I have already tried to track down this issue a little: 
This function call:
https://github.com/xournalpp/xournalpp/blob/5fd2dd3703ef7b7cd07e63ef738fc0affcaa287f/src/util/gtk4_helper.cpp#L26
will throw the segmentation fault when called (undirectly) from the `XojMsgBox` destructor
https://github.com/xournalpp/xournalpp/blob/5fd2dd3703ef7b7cd07e63ef738fc0affcaa287f/src/util/include/util/XojMsgBox.h#L26

But I haven't found out what the underlying problem is. When in the debug console, `win` seems to be a valid gtk object. 
Has anyone else encountered this issue?

**Comment by Febbe** [comment]
@tmoerschell try to compile it with `-O1 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer`

**Comment by bhennion** [comment]
Does this also happen with other dialogs (e.g. if you run the app after cleaning out the crash logs and crash saves and open the Settings dialog) ?
Also, when it crashes, it should create a crashlog. Could you post that here?

**Comment by Febbe** [comment]
@bhennion we should merge the 1.2 branch again into the master, you are using bool as the return type for some slots. And we don't have the wrappers yet.

**Comment by tmoerschell** [comment]
There's no crash on other dialogs (settings, save on exit...). 
Compiling with the options above doesn't make it complain quite a bit about memory leaks: 
[sanitize_crash.txt](https://github.com/xournalpp/xournalpp/files/12807803/sanitize_crash.txt)
Although that is not significantly more than on a successful run:
[sanitize_normal.txt](https://github.com/xournalpp/xournalpp/files/12807826/sanitize_normal.txt)

Here's the crashlog:
[errorlog.20231004-213725.log](https://github.com/xournalpp/xournalpp/files/12807694/errorlog.20231004-213725.log)

And here's the backtrace and some other info I've found with gdb. There seems to be a double free on window->priv ? I wouldn't really know where to look further. 
[segfault_backtrace.txt](https://github.com/xournalpp/xournalpp/files/12807828/segfault_backtrace.txt)

**Comment by bhennion** [comment]
And does the main window appear normally (behind the crashlog dialog)? Or are you only seeing the dialog on startup?

**Comment by Febbe** [comment]
There are several issues with the askQuestionWithMarkup function:

Callbacks are all incompatible, the destroy data callback requires a `GClosure *` parameter. 
The handler itself should have a gpointer instead of an explicit pointer as parameter. 
The data removed, should be XojMsgBox itself, not a call to gtk_window_close, since this may trigger the call response again. 
gtk_window_destroy should be called directly from the response handler.

**Comment by bhennion** [comment]
> Callbacks are all incompatible, the destroy data callback requires a `GClosure *` parameter.
> The handler itself should have a gpointer instead of an explicit pointer as parameter.

That's correct, although I doubt that's what causing the issue (why here and not everywhere else in the code)

> The data removed, should be XojMsgBox itself, not a call to gtk_window_close, since this may trigger the call response again.
> gtk_window_destroy should be called directly from the response handler.

That's not how the PopupWindowWrapper works: in ordre to catch every possible window-closing paths, we tap into the delete-event signal (close-request in GTK4) and *replace* the default handler (a simple call to gtk_window_destroy) with our own PopupWindowWrapper::onCloseCallback.

This callback deletes the XojMsgBox instance, which in turn deletes the GtkWindowUPtr, which calls gtk_window_destroy().

The problem is that XojMsgBox() also connected to the response signal, and also called gtk_window_close(), so it got called twice, leading to calls to delete, and two gtk_window_destroy() indeed. See #5200 for a fix.
