### ISSUE TITLE
Export PDF with plain paper background option

### ISSUE THREAD

**Issue by ulthiel** [xournalpp/xournalpp#5262]
### Feature Description

I use a graph paper for my handwritten notes but when exporting them as PDF, I would like to have a plain paper background. The only option I currently see to do this is the following sequence of steps:
 
1. Paper background -> Plain
2. Paper background -> Apply to all pages
3. Export as PDF
4. Paper background -> Graph
5. Paper background -> Apply to all pages

Is there any shortcut for this? Could there be a tick box "Plain paper background" in the export as PDF window?

**Comment by rolandlo** [comment]
Instead of `File > Export as PDF` use `File > Export as...` and you will not only get the option between various formats, but also for PDF you get more options, which are presented in a dialog.

![grafik](https://github.com/xournalpp/xournalpp/assets/40485433/0b896a0e-307b-4e1e-a19f-85f706791acc)

Use "No ruling" here.

Alternatively exporting from command line or via a plugin is also possible.

**Comment by ulthiel** [comment]
Oh, this was not so obvious. Thank you very much!
