### ISSUE TITLE
Dark Theme won't go away

### ISSUE THREAD

**Issue by lamyergeier** [xournalpp/xournalpp#5422]
### Operating System

Linux

### (Linux only) Distribution

Fedora 39

### (Linux only) Desktop Environment

Gnome

### (Linux Only) Display Server

Wayland

### Installation Method

dnf 

### Xournal++ Version

1.2.2

### libgtk Version

3.24.38

### Bug Description

As you can see in the following image the dark theme is disabled but it persist even after I reboot my operating system:

![image](https://github.com/xournalpp/xournalpp/assets/42092626/1e320b89-3aac-4c4c-83f1-07e23fa35361)

Please may be provide a command line option to disable or enable dark mode as several options such as Latex have very bad visibility in dark mode. Its hard to identify icons due to poor contrast (see below screenshot: rendered latex equations can't be seen)!

![image](https://github.com/xournalpp/xournalpp/assets/42092626/84e07674-d459-4af1-8261-1f78dfe80af8)

### Expected Behaviour

Ability to disbale dark theme

### Steps to Reproduce

See screenshot above

### Requested Solution

Please provide a cli option to force light mode `--light` or dark mode `--dark`

**Comment by rolandlo** [comment]
The issue with the LaTeX background was fixed in #5307. It has been merged into the release-1.2 branch, not yet into master.

The "dark theme" setting only adjusts the icons and some css-styles (like for the sidebar). It must be set in conjunction with the system theme.

**Comment by tmoerschell** [comment]
The window theme can be adjusted by setting the `GTK_THEME` environment variable. If you don't find the exact name of a light theme, I think when the environment variable is set to something that doesn't exist, it defaults to a light theme. 

> The "dark theme" setting only adjusts the icons ...

Since there are a few system icons that will not be adjusted by this setting, I still had to use a hack to complete the custom theming: I extended the environment variable `XDG_DATA_DIRS=~/.icons-light:$XDG_DATA_DIRS`. Then I created a directory `~/.icons-light/icons/<default-theme>/` (e.g. `breeze-dark` in my case), and pasted the files from the light theme (found at `/usr/share/icons/<light-theme>/`) into that directory. 

I do wonder if those system icons could also be handled by the setting in Xournal++.
