### ISSUE TITLE
Crash on autosave

### ISSUE THREAD

**Issue by m0ku** [xournalpp/xournalpp#5502]
### Operating System

Linux

### (Linux only) Distribution

Ubuntu 22.04

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Flatpak

### Xournal++ Version

1.2.2, 09ae3333-dirty

### libgtk Version

3.24.39

### Bug Description

While writing xournalapp suddenly terminated, with no message or warning.
Log file seems to indicate a problem with libgtk while autosaving

### Expected Behaviour

Autosave should be performed without app crashing

### Steps to Reproduce

Only happened once, not able to reproduce

### Additional Context
[errorlog.20240211-105617.log](https://github.com/xournalpp/xournalpp/files/14231982/errorlog.20240211-105617.log)

**Comment by rolandlo** [comment]
Can you share the log file please?

**Comment by m0ku** [comment]
> Can you share the log file please?

I updated the issue with the log file

**Comment by rolandlo** [comment]
Thanks for the log file. I can see
```term
WARNING : xopp :: Renaming file /home/seb/Documents/Notes/Physics/Udemy/.kinematics_exercises.autosave.xopp to /home/seb/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.old.autosave.xopp failed with filesystem error: cannot rename: Invalid cross-device link [/home/seb/Documents/Notes/Physics/Udemy/.kinematics_exercises.autosave.xopp] [/home/seb/.var/app/com.github.xournalpp.xournalpp/cache/xournalpp/autosaves/2.old.autosave.xopp]. This may happen when source and target are on different filesystems. Attempt to copy the file.
```
That shouldn't happen in upcoming version 1.2.3 any more, since autosave files will only be generated in the same folder as the original file (see #5361). The fix has already been merged into the master branch, so you could use the [nightly build](https://github.com/xournalpp/xournalpp/releases/tag/nightly) to avoid that issue.

I'm closing the issue therefore.
