### ISSUE TITLE
Pressure sensitivity not working on Mac

### ISSUE THREAD

**Issue by ThoFrank** [xournalpp/xournalpp#569]
In Mac OS pressure sensitivity of my wacom bamboo tablet is not working.
I dug around in the code and found that pressure is read in
`src/gui/inputdevices/InputSequence.cpp: getInputDataRelativeToCurrentPage() : line 474`
The value of pos.pressure however does not change.  Currently unsure on how to tackle this.

In Gimp it is working correctly.

**Comment by andreasb242** [comment]
There is a GTK Example. May you can install it over macports or what you are using.

If not, compile it yoursel:
>gcc `pkg-config --cflags gtk+-3.0` exampleinput.c -o exampleinput `pkg-config --libs gtk+-3.0`

[exampleinput.c.zip](https://github.com/xournalpp/xournalpp/files/2705183/exampleinput.c.zip)

Gimp is using GTK2, we are using GTK3.

Currently macOS is not official supported by Xournal++, because no developer has currently time for this.
So if you have time, help is welcome, even if it's only to debug the input handling ;-)

**Comment by ThoFrank** [comment]
Thanks!
So here is what I found out:
gtk is currently not supporting advanced tablet features ( see [issue](https://gitlab.gnome.org/GNOME/gtk/issues/1392) ). Demo only shows pointer location and only default device.

For [myPaint](https://community.mypaint.org/t/how-to-build-mypaint-on-mac-osx-without-macports/344/2) there was a huge workaround using x11 and a few patches.
I will try to look into gimp's code to find their workaround. Maybe it could be used for Xournal++, too.

**Comment by andreasb242** [comment]
The issue you mentioned is not very old:
>Opened 2 months ago by

May we should check if we get a patch for GTK instead of trying to do it in Xournal++.
This example (which is not the right four us, for sure) is looking really simple.
https://developer-docs.wacom.com/display/DevDocs/macOS+X+Sample+Code+Downloads

**Comment by andreasb242** [comment]
On this bug is a patch attached!
https://bugzilla.gnome.org/show_bug.cgi?id=695701

It's not that much.
https://bug695701.bugzilla-attachments.gnome.org/attachment.cgi?id=241615

They migrate the Bugzilla to gitlab, because of this I put this patch also here as attachment:
[0001-Quartz-Tablet-pressure-support-draft-2.patch.zip](https://github.com/xournalpp/xournalpp/files/2705599/0001-Quartz-Tablet-pressure-support-draft-2.patch.zip)

But I won't do macOS development at the moment, I'm a Linux user and at the moment I'm already working on the Windows Port ;-)

**Comment by andreasb242** [comment]
I wrote to the GTK Mailing list for a contact person. It don't look like a big problem.

**Comment by andreasb242** [comment]
GTK Bug https://gitlab.gnome.org/GNOME/gtk/issues/1551

**Comment by andreasb242** [comment]
I got it working. The patch is not yet ready, but it's coming soon.

**Comment by andreasb242** [comment]
https://github.com/xournalpp/gtk/pull/1

**Comment by andreasb242** [comment]
GTK Pull Request, still not merged, because I get a lot of review issues.
https://gitlab.gnome.org/GNOME/gtk/merge_requests/541

**Comment by andreasb242** [comment]
This is fixed with the release 1.0.8, even not yet merged into official GTK Repo.

**Comment by cecilyen** [comment]
Any update about supporting pressure sensitivity in Mac?
