### ISSUE TITLE
Wrong UI Font

### ISSUE THREAD

**Issue by RobFro96** [xournalpp/xournalpp#5824]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release, same issue installer and portable

### Xournal++ Version

1.2.3

### libgtk Version

3.24.41

### Bug Description

GUI opens up with a wrong font.
Are some files missing on my PC? What font do I have to download?
![xournal_screenshot](https://github.com/user-attachments/assets/3982dc86-7a02-446d-a46c-83ecbb46632c)

### Expected Behaviour

I was expecting a sans-serif font on the GUI

### Steps to Reproduce

1. Download Xournal++ from Github → same for installer and portable
2. Install or unpack
3. Open Xournal++

**Comment by RobFro96** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

Looks like a virus to me.
https://www.virustotal.com/gui/file/83248e7c2675805c366abe338975b6820b520a16b782849e4c029a355f5f46e5?nocache=1

**Comment by RobFro96** [comment]
There was a comment from a user directing to this link. The comments are removed now. Sorry for the confusion.

**Comment by tmoerschell** [comment]
Just tried it on my Windows setup, and Xournal++ loads the Segoe UI font. That font should be shipped with Windows since Windows 7. Could you verify anyways that `C:\Windows\Fonts\segoeui.ttf` exists? 
Then could you check what font is loaded instead and from where? You can do this with [Procmon](https://winstall.app/apps/Microsoft.Sysinternals.ProcessMonitor), filtering for process "xournalpp.exe" and paths containing "C:\Windows\Fonts", ".ttf" or other font extensions.
I'm sorry I can't help much further for now from a distance...

**Comment by RobFro96** [comment]
Segoe UI was installed. After downloading procmon, I restarted Xournal++. Suddenly, the correct font is available. The issue fixed (itself). Maybe a Windows update? I do not know. Nevertheless, thanks for your help.
