### ISSUE TITLE
Is xournal++ a virus?

### ISSUE THREAD

**Issue by ankiman1** [xournalpp/xournalpp#6041]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

official release

### Xournal++ Version

1.2.4

### libgtk Version

-

### Bug Description

I use virustotal to scan the .exe file and it found a malwere, is a false positive? How can you prove it ?
![xournal_is_](https://github.com/user-attachments/assets/cf19d466-0042-4670-adf1-93e42f7f5c94)

### Expected Behaviour

-

### Steps to Reproduce

-

**Comment by ikanakova** [comment]
#5378

**Comment by Febbe** [comment]
No, xournalpp is not a virus, we have several problems:
 - Malicious software misuse the NSYS installer. Since we also use it, antivirus software will find code snippets which are shared between malicious software and the xournalpp installer.
 - we don't sign the installer and I don't have any experience with that to fix it, I/We don't want to sign them manually every time we release a version. A signed installer will mark us as trusted, so antivirus software won't analyze the installer.
 If you are still unsure, you can download the portable version and move it into Program Files.

**Comment by archisman-panigrahi** [comment]
Xournal++ is now on Microsoft Store and this version is (the same exe file converted to msix and) signed by Microsoft. This version would not be identified as a virus.

https://apps.microsoft.com/detail/9nn1hhct0p1x?hl=en-US&gl=US
