### ISSUE TITLE
MacOS blob building CI unstable

### ISSUE THREAD

**Issue by bhennion** [xournalpp/xournalpp#6046]
The MacOS CI's (from the Github Action version) often fail to build the dependency blobs, with errors of the like:
```
Error during phase checkout of gtksourceview3: file hash is incorrect (expected 7ec9d18fb283d1f84a3a3eff3b7a72b09a10c9c006597b3fbabbb5958420a87d, got 29695086c0060fea4aed51dc5922b9ced4b7c9b3305c89725659851469f4eb6a)
```
This happens at various stage of the build. We should strengthen this by allowing retries when downloading deps.

**Comment by rolandlo** [comment]
Maybe try this argument for `jbuild build` (see https://gitlab.gnome.org/GNOME/jhbuild/)
>`-C, --try-checkout`
  	If the build fails, and if supported by the version control system, force a checkout and run autogen.sh before retrying the build.

**Comment by rolandlo** [comment]
It might make sense to split the download and build parts, i.e. first do `jhbuild update ...` and when it succeeds `jhbuild build --no-network ...` in the hope that if the download part succeeds the build part will succeed as well. If it does not succeed, it will only take a fraction of the time to get to that point, since the build part is skipped. 

Also we should probably use the `--no-interact` option, since we can't interact in the CI.

Instead of using arguments like `--no-interact` and `--try-checkout` we could append them to the `jhbuildrc` via

```term
interact =  False
trycheckout = True
```

Here is the command reference by the way: https://gitlab.gnome.org/GNOME/jhbuild/-/blob/master/doc/command-reference.rst?ref_type=heads
