### ISSUE TITLE
Export xopp file to pdf from command line

### ISSUE THREAD

**Issue by student-sx** [xournalpp/xournalpp#681]
Is it possible to export a xopp file to pdf from commandline? In my case I have a directory containing many xopp files which I want to convert to pdf. To do this I have to open every file and click each time on the export button. 

Something like:

```
for file in *xopp;
do xournalpp --export $file;
done
```
would be much more elegant.

If not, I think this would be a nice feature for the future.

**Comment by andreasb242** [comment]
>xournalpp --help
Show the help. The texts are in your local language, if supported.

>xournalpp -p pdffile.pdf yourfile.xopp

So you can do your batch conversion.

**Comment by atticus-sullivan** [comment]
I just wanted to open a feature request for this on my own, since `xournalpp -p file.xopp` didn't work. Please add to the comandline help `xournalpp -h` how to use the options (which parameters are nessacary)

**Comment by PatrickMassot** [comment]
Indeed it would be nice if we had a version of this switch which simply replaces `.xopp` with `.pdf` instead of asking for a pdf file name. It would be much nicer for batch conversion.

**Comment by leonenethz** [comment]
Hello
I have the same issue, hovever
````bash
xournalpp --help
````
does not work on my computer (I'm currently on windows, want to switch to Linux in the future).  Maybe it's because I'm on windows right now and just downloaded the .exe from the github repo.
I want to use xournalapp for my studies, it would really help if I could convert all .xopp files in a folder to .pdf files (and vice versa) in one go, without having to open every single one of them.
Any idea how to do that? Or why xournalapp --help doesn't work?
Thanks!

**Comment by masongyli** [comment]
@leonenethz If you are on Linux or using Git Bash on Windows, you can use the following to convert all .xopp files in the current folder to .pdf files
```
for file in *.xopp ; do xournalpp -p "${file%.xopp}.pdf" "${file}" ; done ;
```

**Comment by rubyFeedback** [comment]
I got an error with this, both from the GUI as well as the commandline:

    (com.github.xournalpp.xournalpp:2863504): xopp-ERROR **: 16:06:43.170: Error while finalizing the PDF Cairo surface
    Cairo error: out of memory
    Trace/breakpoint trap (core dumped)

I compiled cairo from source, but used archlinux's binary package for xournalpp. So that error is most likely on me, but even then I find the error a bit strange, because I don't think the real error is "out of memory", so it appears as if the real error is swallowed here.
