### ISSUE TITLE
Git Filter

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#7]
In terms of elegant document version control, it should be possible in theory to use a Git filter and a script to store diff changes to the xournalpp XML. See, perhaps, https://github.com/DataWraith/gitfilters.

**Comment by xax** [comment]
> I've got a filter written […]
> ```shell
> #!/bin/bash
> […]
> 
> #To use, add the following to .git/config or ~/.gitconfig:
> # [diff "xoj"]
> #       binary = true
> #       textconv = /path/to/script/git_diff_xournal.sh
> ```

That diff driver only produces human readable **diffs** (bin→text); it does not prevent git from having to store **blobs** instead of diff deltas as objects in commit history (git would not be able to use the diffs to reconstruct bin ← from patched text). 

The workflow you intended would require (each collaborating user! lest not he forgets…) introducing a `filter.‹xopp›.clean` (checkin: bin→asc) and `filter.‹xopp›.smudge` (checkout: asc→bin).

Thus an option to store `.xopp` XML uncompressed (best defaulting to write changes to uncompressedly loaded `.xopp`s uncompressed again) would still be highly appreciated. (And that conflicts with the current drive to the new binary storage format…!)
