### ISSUE TITLE
Possible cleanup

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#716]
Hi!
Is there a specific reason in order to keep 4 different methods in `XojOpenDlg` which do the same thing?
I think that we could replace those with one method that accepts the name of the filter and the extension!

**Comment by andreasb242** [comment]
Which 4 Methods do you mean?

**Comment by luco5826** [comment]
```
void addFilterPdf();
void addFilterXoj();
void addFilterXopp();
void addFilterXopt();
```
They do basically the same thing

**Comment by andreasb242** [comment]
Yes, but they have different string, and this methods are called from different places. If add the Texts as parameter, you have provide the texts from different locations, which is not a good idea, because there is always the risk, that somebody edit only one location.

addFilterPdf adds two extensions, but you can create a Method, which is called from the other 3 Methods.

A new Method costs you 10 Lines of code, 1 Line header.
You save 3 * 3 Lines (you delete all 4 lines, and add a new to call the main method)

So in this case you add two lines.
But you are generally right, but in this case there is no space for improvements I think.
Generally I'm always for smaller code, extending classes, and extracting methods.

**Comment by luco5826** [comment]
Ok thank you!
