### ISSUE TITLE
Pen pointer

### ISSUE THREAD

**Issue by masac** [xournalpp/xournalpp#717]
I have a tablet Wacom Bamboo. I attached a small video clip.
https://drive.google.com/file/d/1tcnbeFB051O2Q64ymjZY-u27XeDFkz6G/view?usp=sharing

In Xournal everything works correctly. In the latest version of Xournal ++, when I release the delete button 
 of the pen, the cursor does not automatically change in pen pointer.

**Comment by andreasb242** [comment]
Input handling / multidevice. Do you know if the button is Button 1 / 2 of the Pen or does it make an eraser (other device) out of the pen?
If you don't know it's also not a big problem, I can test both.

**Comment by andreasb242** [comment]
I had today the exactly same error, but then I saw, there was a second layer. So the issue is probably in the layer handling (which is completely refactored for the new layer menu)

**Comment by andreasb242** [comment]
I deleted a commend, which I accidentally wrote to this ticket, but had nothing to do with it.

I found the bug, and could fix it.

**Comment by masac** [comment]
There is a small problem. During erasure, if the tip of the pen touches the tablet, the pen instead of delete, he draws lines.

**Comment by morrolinux** [comment]
@masac I know what you're talking about, but this is a driver configuration issue:
if you're using the wacom driver for instance, there is a setting "TPCButton / TabletPCButton" which enables the button (configured as a rubber in your case) to "engage" only when pressing and touching the screen (not when hovering). 
See:
https://github.com/morrolinux/SurfaceLinuxGoodies/blob/master/Note%20taking/config-wacom-libinput/usr/share/X11/xorg.conf.d/30-wacom.conf

Now I'm trying to do the same with libinput driver, but I haven't found out an equivalent parameter yet.
Please update us here if you know/find out what I'm talking about

**Comment by andreasb242** [comment]
@morrolinux I also know this, I think it should go to the Wiki and should be linked in the readme or so, this ticket is closed...

**Comment by morrolinux** [comment]
Right, I'll do this

**Comment by andreasb242** [comment]
@masac Xournal is written with GTK2, Xournal++ uses GTK3, and they have a lot of differences.

Try to find a package like gtk3-demo or so, and install it, there are a lot of tests, also some from mouse and pen stuff.
There you can do your tests. If this demo does the same as Xournal++, there is no bug in Xournal++, you have to figure out, how you can change the configuration. I have the same behavior as you describe in Xournal++.
If there is a difference, you can open a ticket here. Else you may need to search somewhere else (GTK? X11 I don't know), because e.g. I don't know how to change it.

**Comment by masac** [comment]
Thanks!
