### ISSUE TITLE
Export as image from CLI

### ISSUE THREAD

**Issue by anishmittal2020** [xournalpp/xournalpp#795]
1. It will be great if we could export (and import) the notes as `SVG`? 
    -   SVG is supported by modern web browsers
    -   SVG is text based
    -   there are Javascript libraries which allow drawing SVG in browsers (like [this one](https://github.com/SVG-Edit/svgedit)
    -   Markdown allows embedding SVG as images

---

2. Also, can we export as `png` (and `svg`) from CLI?  

I am motivated by this as I want to use `xournalpp` only for handwritten notes. I want to use  `Markdown` and `Pandoc` as a container of my notes. I want to make small handwritten notes as separate files and embed them inside my larger markdown file.

**Comment by andreasb242** [comment]
SVG Export was removed because there was an issue in exporting stuff (it was there, but not working).
But this is now fixed, SVG export is no Problem, as this is supported by cairo.
It's not that much work.

Commandline arguments is also not a big issue.

SVG Import is much work, because currently we do not support SVG rendering, so this is a new implementation. (and is not supported by cairo).

You can expect the SVG export in a much shorter time than the import. But also then, you may noticed how many tickets are currently written withing really short time...

**Comment by andreasb242** [comment]
Working, one issue: we need to export as SVG 1.2, and e.g. EOG does not display it correctly, Firefox does.
See xournalpp -h for the commands.
