### ISSUE TITLE
Objects disappear when deselected or while working

### ISSUE THREAD

**Issue by luco5826** [xournalpp/xournalpp#840]
Hi!
I experienced this issue while using LaTeX, I was a lot of images deep when suddendly one or two started disappearing.
I don't know what caused it, but I think it has something to do with the selection mode, because the first object disappeared when I switched do "Select Object" mode

![ezgif-4-221a629e1527](https://user-images.githubusercontent.com/38291180/52228537-e56e1f80-28b2-11e9-9bed-b3370db43fa8.gif)

**Comment by andreasb242** [comment]
Selection has anway a lot of issues - I think I'll need to rewrite selection, then I cal also solve this...

**Comment by LittleHuba** [comment]
If you rewrite the selection this would also resolve issue #810.

**Comment by morrolinux** [comment]
If you eventually do rewrite the selection, keep in mind we would need to rotate images as well in the future

**Comment by LittleHuba** [comment]
> If you eventually do rewrite the selection, keep in mind we would need to rotate images as well in the future

Best would be if we could just rotate everything.

**Comment by andreasb242** [comment]
We should do the selection like libreoffice:

![grafik](https://user-images.githubusercontent.com/822958/52519740-a8ae7980-2c60-11e9-8386-cb677e7a0f6a.png)

**Comment by RiccardoBuscicchio** [comment]
If it is any useful solving the issue, I noticed a few things:

- copying objects into a new `.xopp` file fixes its "disappearing" behaviour.
- copies of a "disappearing" object does not change its "disappearing" behaviour

Currently running on `Ubuntu 20.04` with  `1.1.0+dev` version.

**Comment by rolandlo** [comment]
@luco5826 @RiccardoBuscicchio 
Can you check your xopp-files with disappearing objects once more? Maybe you have the same issue as in #2168 which was caused by invalid strokes. You need to copy/rename it to .gz ending and gunzip the file to see the underlying xml-file.

**Comment by ha7ilm** [comment]
For me objects also started to disappear... My workaround was so far: 
- copy objects to a blank file
- now select them with group selection (Ctrl+Shift+G)
- copy back to original file
- do not use rectangular selection again...

**Comment by tbdk** [comment]
> @luco5826 @RiccardoBuscicchio
> Can you check your xopp-files with disappearing objects once more? Maybe you have the same issue as in #2168 which was caused by invalid strokes. You need to copy/rename it to .gz ending and gunzip the file to see the underlying xml-file.

As of June 2021, I ran into this issue also! Following rolandlo's directions, renaming the .xopp file to end in .gz and then unzipping it and opening it with a text editor, I found out that it had some <stroke> elements in it, that had a width of "nan" and content nan. I deleted these elements, so that I was back to having the minimum for the page, i.e. a <page>, <background> and <layer> element. 

**What produced it:** Trying to copy a picture from a Google Doc into the xopp journal. It's my observation that copying a picture from Google Docs into, say Paint or Pinta or any other graphical manipulation software is not possible, and result in a error message saying that the clipboard does not contain an image. However, if trying to insert into Libre Docs, Word, etc. it works. So copying a Google Doc picture results in _something_ being in the clipboard, but it cannot succesfully be interpretet by a graphical manipulation program. Whereas other programs seem to detect this (?) and either throw an error message or not react to it, XJournal seems to actually insert a stroke of "nan" width and nan content.

**Comment by rolandlo** [comment]
> **What produced it:** Trying to copy a picture from a Google Doc into the xopp journal. It's my observation that copying a picture from Google Docs into, say Paint or Pinta or any other graphical manipulation software is not possible, and result in a error message saying that the clipboard does not contain an image. However, if trying to insert into Libre Docs, Word, etc. it works. So copying a Google Doc picture results in _something_ being in the clipboard, but it cannot succesfully be interpretet by a graphical manipulation program. Whereas other programs seem to detect this (?) and either throw an error message or not react to it, XJournal seems to actually insert a stroke of "nan" width and nan content?
> 
> Using Xjournal++ Version 1.0.20

More likely it was a combination of this insertion with a undo action. This should not happen in version 1.1.0+dev anymore.

**Comment by Technius** [comment]
Is anyone still encountering this bug?

**Comment by bhennion** [comment]
This seems to have been fixed with #2857. Closing.
Feel free to reopen if you're still encountering the issue.
