### ISSUE TITLE
Scrollbars "flashing" while writing

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#876]
Again, this is better explained here: 

![recorded](https://user-images.githubusercontent.com/6414907/52733060-0e349a00-2fc2-11e9-8579-15781944daeb.gif)

Every time the pen touches the tablet, scrollbars change, and the flashing effect is quite disturbing. I know I can hide them, but still...

**Comment by andreasb242** [comment]
For me this looks like a bug of GKT or your Distribution. I cannot reproduce it.
Please open a Gedit window, write some text and some empty lines, so that you get scrollbars in both directions, and then draw with the pen on it. (yes I know: Gedit won't draw it ;-))

If there is the same behavior we cannot fix it, if there is a difference, let us know, then I'll have a look at it.

**Comment by LittleHuba** [comment]
I can reproduce the bug on Arch Linux with KDE Plasma 5.
It lookslike the flashing occurs because the scroll bars "loose focus" or something similar when the pen touches the surface of the screen.

I'm not quite sure how we can fix that without using ugly hacks like manually forcing focus on the scrollbars... Obviously it would be easy if we could use proximity events but you mentioned the are not working in GDK @andreasb242?

**Comment by Rmano** [comment]
Maybe the problem is that I have `focus follow mouse` focus policy. Will try to switch to click-to-focus and see... as soon as I am at my PC again.

**Comment by andreasb242** [comment]
You can try the scrollbar hack (Touch settings, allow Touch for drawing).
Both did not respond to my question, is it the same with Gedit?

**Comment by Rmano** [comment]
Just checked (I had to recover my Wacom tablet):
- it happens exactly the same with `gedit`
- It does not depend on click-to-focus or focus-follow-mouse

**Comment by andreasb242** [comment]
So first: if it happens to Gedit, this is not a Xournal++ bug. And we probably don't solve it.

Select GTK Touch / Scrolling workaround in the Touch Settings tab. It my solve the problem.
We can still discuss here - but I close the bug. You may report it to GTK, or to Arch.

**Comment by t3e** [comment]
I still have this and it's very annoying.
