### ISSUE TITLE
get dpi from environment

### ISSUE THREAD

**Issue by cbm755** [xournalpp/xournalpp#897]
This is low priority.

I can query my X server for the current DPI:
```
$ xdpyinfo  | grep dots
  resolution:    210x215 dots per inch
```
In the bad ol' days, this was often garbage but I assume (perhaps incorrectly) that we can now get a reasonable value which takes HiDPI etc into account.

Anyway, might be nice if that value was used by default.  The current "Zoom, put a ruler on screen" preference could then by behind a checkbox:
```
[ ] Override autodetected dpi value (currently: 210)
Put a ruler on your screen etc etc
```

**Comment by andreasb242** [comment]
We currently support macOS, Windows and Linux with X11 or Wayland, therefore this is no option.
HighDPI is working, we already get the information from GTK (we get a scale factor, not a DPI).
GTK Automatically scale the most stuff, the rest is scaled by Xournal++.

**Comment by cbm755** [comment]
Maybe I've misunderstood: when I started Xournal++, the dpi was set to 72...  And I had to go and do the ruler thing in preferences to get "100 %" zoom to look reasonable.

This is Gnome on Fedora 29.

**Comment by andreasb242** [comment]
Thats right, your bug report is correct. We only get a scale factor from GTK, e.g. 2 for high DPI Displays.
But Query X11 is no option.

May gdk_screen_get_resolution delivers a Value, but I even then don't expect that the value will be right, maybe except on macOS, where the HighDPI Stuff is really good handled (because they know the Hardware), on Linux / Windows it requires usually manual configuration.

I'll do a short check, I have multiple devices here, and if it returns the right value, I have a look at it.

**Comment by andreasb242** [comment]
Definitive not working - the DPI value is wrong, therefor using this value makes absolute no sense.

It might be working on some devices, but if it's not working on all devices it makes no sense to implement it.

**Comment by andreasb242** [comment]
Your bug report is correct, but cannot be solved. Therefore it's closed, we leave only bugs open which can be solved by Xournal++, else there are so many, we don't find the real one.
