### ISSUE TITLE
Point.h crash

### ISSUE THREAD

**Issue by wbrenna** [xournalpp/xournalpp#92]
Crashes at Point.h and/or gives double free error:
```
[bt] #13 ./xournalpp(_ZN12DocumentView10drawStrokeEP6_cairoP6Strokeid+0x392) [0x50b912]
/home/wilson/etc/xournalpp/src/view/../model/Point.h:17
[bt] #14 ./xournalpp(_ZN12DocumentView9drawLayerEP6_cairoP5Layer+0x1bc) [0x50c1fc]
/home/wilson/etc/xournalpp/src/view/DocumentView.cpp:295
[bt] #15 ./xournalpp(_ZN12DocumentView8drawPageE7PageRefP6_cairob+0x1a4) [0x50cfd4]
/home/wilson/etc/xournalpp/src/view/DocumentView.cpp:469

*** glibc detected *** ./xournalpp: double free or corruption (!prev): 0x00000000011df650 ***
```

**Comment by andreasb242** [comment]
I looked at the code, this error cannot happen at this location, this means the memory has been corrupted before.
With this stacktrace and without other information it will not be possible to fix the issue.

Because of this I close this issue, if somebody get a simmilar stacktrace and google for it, it should be possible to find this ticket, and it can be reopened.
