### ISSUE TITLE
Paper background "apply to all pages" strange behavior? 

### ISSUE THREAD

**Issue by Rmano** [xournalpp/xournalpp#951]
I supposed that "apply to all pages" should be a simple switch --- but it's acting (and looking) quite strange here (recently compiled, says it's 1.0.9): 

![recorded](https://user-images.githubusercontent.com/6414907/53656213-df215800-3c52-11e9-9013-d7fe1f039442.gif)

(do not mind the flashing lines, it's a `byzanz` (the gif recorder) artifact.

**Comment by andreasb242** [comment]
No this is correct. You select the background for new pages below and can also apply it to all pages, which cannot be a switch, how should it work then?

**Comment by Rmano** [comment]
But I have "graph with border" selected, and choosing "applying to all pages" made the page blank...

**Comment by andreasb242** [comment]
Please explain this in the first post - I didn't notice that...

**Comment by Rmano** [comment]
> Please explain this in the first post - I didn't notice that...

Sorry.... Too fast. Thanks...

**Comment by Rmano** [comment]
I have another video showing that "apply to all pages" is doing random things; moreover, the fact that the tick is always on is confusing. I think that the "apply to all pages" should be just a toggle, switching from activated to not activated, and then do the proper action when the background is chosen. Now what it does is switching back to the default background, and only in the current page: 

![copyandpaste](https://user-images.githubusercontent.com/6414907/55548816-a69eef00-56d4-11e9-9d6b-cdafcabc4316.gif)

**Comment by Technius** [comment]
Looks like the issue is that `Apply to all pages` in `Journal > Paper Background` is based on the paper background selection of the dropdown menu in the toolbar, while the page type options in `Journal > Paper Background` don't use the background selection of the toolbar dropdown. Using the menu option to set an individual page's background isn't calling the same code as using the toolbar dropdown to do the same thing.

**Comment by Technius** [comment]
I found the root cause of this bug. The page background can be selected from two locations: from `Journal > ...` and the toolbar. In each location, we have a separate `PageTypeMenu` instance in which the selection state is stored. `Apply to all pages` only uses the state of the `PageTypeMenu` in the toolbar, which why we have the observed behavior. To fix this, `PageTypeMenu` should not  be storing any state whatsoever and should delegate all selection state logic to `PageBackgroundChangeController`.

**Comment by Technius** [comment]
I looked into this more closely today. The issues can be summarized as follows:
* The toolbar popup is meant to apply to "new pages" (same as the one in the `Journal > Configure Page Template` dialog). Thus, the page selected there will apply to newly created pages.
* The menu popup is meant to be the "current page" dialog. However, the page type in the menu popup is not updated when the new page popup is used to "apply to all pages".
* The "apply to all pages" in the menu popup uses the selected page in the "new page" popup.
