### ISSUE TITLE
Arrow:  tip change size as length increases.

### ISSUE THREAD

**Issue by deragon** [xournalpp/xournalpp#967]
When creating an arrow, the tip of the arrow changes size as the length increases.  That means that multiple arrows of different lengths on the same page do not look the same.

At a minimum, the tip should remain the same regarding the length of the arrow.

Also, a tip selection tool would be welcomed.  I would like to be able to choose tips on both ends.  But I should create a separate issue about this.  On the main webpage of this fantastic tool (I discovered Xournal++ 30 minutes ago), there is no mention on how to get support.  That is why I am writing here more than I should here.  I would one go to discuss issue with the author(s) before submitting an official issue?

**Comment by andreasb242** [comment]
> That is why I am writing here more than I should here. I would one go to discuss issue with the author(s) before submitting an official issue?

This issues are a good way to contact us, and we also do discussions here, at least on some issues.
So feel free to create an issue, also for discussion.

Additional there is a link to gitter on the Readme on top. But the most technical discussions happen here on the issues.

Back to the technical Question:
It should be relative easy to implement different tips, and let the user select them. But only BEFORE drawing, because an arrow will be drawed as 3 lines on the document (because of this you can also erase some parts), so changing the tips after drawing will not be possible.
Would this be Ok, or would you like to change the arrows after drawing? (You can request it - even if it will not be possible at the Moment ;-))

**Comment by Rmano** [comment]
My opinion is that the tip size should be proportional to the line thickness, not to the length...

And yes, the most useful way to implements tips is to make them a property of the line, so that you will be able to change them after-the-fact. 

But just implementing the first point would make them usable (now they have little usability, I think.)

**Comment by LittleHuba** [comment]
We could allow late modification of the tips by doing the following: 

Create another object class for arrows and store the actual arrow line separately from the lines of the tips. Allow modifying of the tips in that class, Erasing of sections of the arrow can also be handled in this class. 

Storing is more of a problem as we would need to increment the file version number and introduce a new element to the format. Therefore I'd say we postpone this until we have the new format. There we can also enforce requirements on the client reading a file and throw an error when finding an unknown element.

**Comment by deragon** [comment]
Unless you are willing to implement shortly all the bells and whistles required for proper arrow support, I believe that this issue should just tackle a quick fix to ensure that the tip remains of the same size regardless of length.  Other issues could be created to tackle the more sophisticated and demanding changes, such as tip selection and tip change once the arrow is drawn.

Arrows are often used when annotating existing documents, particularly PDFs.   Xournal++ would gain more notoriety if it could support them properly, with all the suggestions you are bringing up.

**Comment by Photon89** [comment]
Hi guys, xournalpp just hit the Manjaro repos substituting the old xournal and I'm right now playing around with it and it's freaking awesome! The arrow tips issue is one of the minor things which I'd also like to be able to change. Maybe have two types of arrows, say "arrows" and "vectors"? I could in principle imagine that somebody wants arrow tips to scale with the length of the arrow, but vectors should allow different lengths with no change in the tip size.

**Comment by LittleHuba** [comment]
We will stick to the quick fix for now. The more sophisticated solution might even be out of scope if I think about it. Xournal++ is a notetaking application and no graphics application. Just draw the tip by hand if you need it :wink:

**Comment by redweasel** [comment]
I have made a little fix for this and the problem with the coordinate system, the Patch should be linked here
[toolusability.txt](https://github.com/xournalpp/xournalpp/files/3854421/toolusability.txt)

I think xournalpp should have better tools for drawing in physics class. I will see what I can add in when I have time

**Comment by LittleHuba** [comment]
Thanks for providing the fix @redweasel! Would you mind doing a PR with the changes included?
